.gitignore, changelog.md, crates/telio-model/src/api_config.rs, crates/telio-nurse/src/config.rs, nat-lab/tests/telio_features.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_telio_features.py, nat-lab/tests/test_telio_tasks.py
Add a configurable parameter within feature config, defining how long should libtelio wait until sending first heartbeat event.
=> add initial heartbeat interval to feature config

Cargo.lock, crates/telio-firewall/Cargo.toml, crates/telio-firewall/src/firewall.rs, crates/telio-utils/Cargo.toml, crates/telio-utils/proptest-regressions/lru_cache.txt, crates/telio-utils/src/lib.rs, crates/telio-utils/src/lru_cache.rs
**Already reviewed**
This MR improves the performance of telio-firewall as measured by the internal benchmarks. Improvements are separated into distinct commits for easier reviewing:
- Replace default hashing algorithm of standard hash map with a rustc_hash. The default one in known to be quite slow but gives some benefits (eg. protection against [Hash flooding](https://en.wikipedia.org/wiki/Collision_attack#Hash_flooding)). The new one is used in the rustc compiler and is much faster and works well for relatively small keys.
- The common path for the outbound tcp packets has been cleaned up to avoid any unnecessary work.
- LRU cache has been reimplemented. The one we used previously was using BTreeMap which is in general slower than HashMap and [it also performed many operations in …
=> Llt 3626 firewall speedup

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/dod.yml, .github/workflows/fuzzing.yml, .github/workflows/gitlab.yml, .github/workflows/linters.yml, .github/workflows/scorecard.yml, .github/workflows/tests.yml
Few improvements to the CI:
1. Gitlab pipeline is run automatically for PRs where feature branch is residing inside NordSecurity repository. This way there is no need to add `run tests` label in order to trigger gitlab pipelines for internal PRs.
2. build, linters, tests and fuzzing were put into one `CI` workflow in order to use `check-all-green` and `skip-duplicate-actions` actions more easily
3. `skip-duplicate-actions` is used to skip actions if multiple of them are running for the same sha. We have this situation because we run our actions for both `push` and `pull_request` events. Alternatively we could also not run them for push (leave only push to master) but the advantage of keeping both of them is that you can push your feature branch and check the actions without needing to …
=> CI improvements

.github/workflows/gitlab.yml
I messed up a little with previous PR. I didn't spot that we now run gitlab pipelines twice for pull_requests. I am not yet sure if we can use `skip-duplicate-actions` for gitlab workflow so for now lets quickly disable them on pushes to feature branches to not overload our gitlab runners
=> CI Improvements: run gitlab pipelines only on push to main branch

.github/workflows/benchmarks.yml, .github/workflows/ci.yml
This job is just to keep the benchmarks from being broken. This is why the durations are reduced - we only care that it compiles and runs correctly. The timings on CI are not useful since the machine they are run on can be arbitrarily configured and loaded.
=> Add telio-firewall benchmarks CI job

.github/workflows/benchmarks.yml, crates/telio-firewall/benches/firewall_bench.rs, crates/telio-firewall/src/firewall.rs
Packets sent/received in benchmarks are abstracted to allow for uniform handling of both IPv4 and IPv6 packets (in the same way as we did in the firewall tests). This doubles number of benchmarks.
At the same time different number of packets to send/receive is removed and only the bigger number of packets is used. This halves the number of benchmarks which in the end results in keeping the same number of benchmarks overall.
*--write your description here--*
=> [LLT-3626] Add firewall benchmarks for IPv6

.github/workflows/ci.yml, .github/workflows/gitlab.yml, .github/workflows/linters.yml
1. Move clippy-mac from gitlab pipeline and unify arguments between linux, win and mac jobs
2. Remove skip-duplicate-actions and replace it with our own check. The idea is as follows: for all internal PRs `push` trigger is enough. It basically is equivalent to how pipelines work on gitlab. `pull request` trigger is only needed because pipelines would not otherwise be triggered for PRs from fork because obviously `push` is not triggered for them. So lets just run our pipelines only for `push` and  lets use  `pull request` trigger only for pull requests from forks.
3. Improve gitlab triggering: Again, similarly to point 2 run them only on 'push' trigger for our PRs and  'pull request target' in case of PRs from forks, but run them for forks only once when 'run tests' label is added. 
One …
=> Next CI improvements

.github/workflows/linters.yml
This job is right now just a dummy. It builds dylint but runs zero checks with it. Since it didn't use specific version of dylint, it started to fail when the dylint executable started to require rust version newer than what we use. Instead of fixing it now, let's remove it now. It can be re-added once we have our lints open sourced and ready to be used here.
=> Remove nagger job

changelog.md, crates/telio-firewall/src/firewall.rs, crates/telio-utils/src/lru_cache.rs, nat-lab/tests/test_mesh_firewall.py
when analyzing the following sequence from perspective of Node1:
The rx_alive as well as tx_alive will both be set to false whenever the FIN&ACK packet is sent out, consequently, the tcp_cache entry will be removed here: https://github.com/NordSecurity/libtelio/blob/main/crates/telio-firewall/src/firewall.rs#L454C1-L454C44. Thus upon receiving the ACK no tcp_cache entry will exist and the packet will be dropped.
1. Using boringtun start meshnet
2. Add one peer to meshnet which is not allowed to do the incoming connections
3. Create TCP connection using nc between those nodes
4. Shutdown the connection from the peer (added in step 2) side
5. Observe connection left over in LAST_ACK stage
After FIN is being sent/recieved, shutdown tx / rx and then wait for last ACK before removing …
=> Resolve LLT-4012: fix firewall, so tcp won't be stuck in last_ack state

nat-lab/tests/test_connection_states.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_verify_pk_on_packets.py
whenever flaky test appeared, we disabled it by skipping it. Sometimes losing some important information.
mark them as `possible to fail` using XFAIL. XFAIL mark allows to indicate that tests might fail (being falky). Test will run, but no traceback will be reported when it fails. And also, end result (exit code) will not be affected
=> Resolve LLT-4051: Reenable flaky tests with XFAIL pytest

crates/telio-firewall/src/firewall.rs
Increased sleep duration tiny bit, to prevent race condition when waiting for tcp cache entry to timeout.
=> Fix firewall test timeout after fin

nat-lab/tests/derp_cli.py, nat-lab/tests/telio.py, nat-lab/tests/telio_test.py, nat-lab/tests/test_connection_states.py, nat-lab/tests/test_derp_connect.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_dns_through_exit.py, nat-lab/tests/test_events.py, nat-lab/tests/test_fire_connecting_event.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_mesh_remove_node.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_node_state_flickering.py, nat-lab/tests/test_reconnections.py, nat-lab/tests/test_tcli.py, nat-lab/tests/test_upnp_connection.py, nat-lab/tests/test_verify_pk_on_packets.py, nat-lab/tests/test_vpn.py
Some nat-lab tests were not handling events correctly, causing flakyness. After initial investigation on test_direct_connection_endpoint_gone() flakyness it was found that most calls to wait_for_event functions were checking historic events where they should instead be waiting for new events/states (node & derp servers). Also it was using wait_for_any_derp_state which looks for a state in any derp, where they should be checking on every derp (eg: blocking every derp servers connection).
In this PR, the checks were splitted into two distint category of functions, `wait_for_state_<derp/peer>` and `wait_for_event_<derp/peer>`. `wait_for_state_<derp/peer>` functions wait for a state report that matches with the given arguments, and `wait_for_event_<derp/peer>` functions wait for a new event …
=> nat-lab: Refactor event handling

.github/workflows/build.yml
Cache for build jobs
In the positive scenario, where the cache is hit it cuts the the time by ~half.
Without cache: https://github.com/NordSecurity/libtelio/actions/runs/5752168035/usage Total time: ~3h40m
With cache: https://github.com/NordSecurity/libtelio/actions/runs/5755230159/usage Total time: ~1h50m
This cache caches on a workspace level, not single compilation units like sccache. So if the feature branch changes dependencies inside Cargo .toml/.lock files the first run will be a cache miss and will require complete rebuild. 
It should be compared to the sccache, but I think it is worth enabling now anyway.
=> CI: Enable caching for build jobs

.github/workflows/gitlab.yml, .gitlab-ci.yml
We skip version 0.1.3 - there was nothing wrong with it, just no-one got to updating github to use it.
=> Start gitlab pipelive with version 0.1.4

.github/workflows/gitlab.yml
Start gitlab pipelines every 30 minutes during the night. This is very similar to the old gitlab based scheduled pipelines. We use the new functionality of the action to mark our scheduled pipelines. This will be used later on to collect them and generate summaries and statistics of the failing nat-lab tests.
The schedule is slightly different from the old gitlab one, to avoid the crowded full hour mark.
=> Add scheduled gitlab runs

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, changelog.md, docs/git_commit_messages_requirements.md, dod.yml
Adding document that indictates how project's commit messages should look like.
=> Add git commit message requirements

nat-lab/tests/test_network_switch.py, nat-lab/tests/utils/asyncio_util.py, nat-lab/tests/utils/process/docker_process.py, nat-lab/tests/utils/process/ssh_process.py
Problem:  
- During failed tests, most of the exception are suppressed by `asyncio_util::run_async`. When exception occurs and it is not `asyncio.CancelledError`, it goes to general exception handler. There it calls `sys.exit(1)`, which mostly does nothing when exception is raised and basically works as `pass`. This behavior suppresses exceptions and doesn't allow program to handle them, which might lead to improper cleanup, causing instability in next running tests.
Solution:  
- Remove `sys.exit(1)` from `asyncio_util` and let exceptions through.
- Also ignore exit code from processes when they are cancelled.
**Note:** Log output was not affected like the comments said.
=> LLT-4100: natlab fix exception handling during failure

nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_mesh_plus_vpn.py
Tests `test_vpn_plus_mesh_over_different_connection_types` and `test_direct_connection_endpoint_gone` are flaky.
For now mark them as xfail. In future investigate.
=> Mark flaky tests with xfail for future investigation

.github/workflows/gitlab.yml
Previous version of gitlab pipeline trigger action used too restrictive whitelist.
This new version allows additionally cron schedules to start new gitlab pipelines. This should fix the overnight pipelines and allow them to start new gitlab pipelines.
=> Use action allowing scheduled jobs

changelog.md, crates/telio-firewall/src/firewall.rs, ffi/tests/test_panic.c, nat-lab/docker-compose.yml, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/connection_util.py, src/device/mod.rs, src/device/wg_controller.rs
1. Bugfix for LLT-4119 - consolidate_firewall function was removing exit_node from firewall. This commit fixes it.
2. consolidate_firewall now uses whitlists from firewall itself as a current state insted of relying on wg interface
3. connect_exit_node was fixed. Previous implementation contained a bug when it was called twice with the same vpn server as an exit_node. In that case the function assumed it is not a vpn server because it already had such peer in wg interface. Fixed it by differentiating between vpn server and mesh peer by just looking at the endpoint field.
4. consolidate_firewall was not removing peers from firewall's whitelists when one of their permissions was stripped. E.g. if the peer was previously allowed for incomming connections and to send files and later it was …
=> Fixing issues in telio-firewall

nat-lab/bin/derp-server, nat-lab/conftest.py, nat-lab/docker-compose.yml, nat-lab/pyproject.toml, nat-lab/tests/test_connection_states.py, nat-lab/tests/test_derp_client_message_forward.py, nat-lab/tests/test_derp_connect.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_direct_feature.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_dns_through_exit.py, nat-lab/tests/test_events.py, nat-lab/tests/test_fire_connecting_event.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_mesh_remove_node.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_node_state_flickering.py, nat-lab/tests/test_pinger.py, nat-lab/tests/test_reconnections.py, nat-lab/tests/test_tcli.py, nat-lab/tests/test_telio_tasks.py, nat-lab/tests/test_upnp_connection.py, nat-lab/tests/test_verify_pk_on_packets.py, nat-lab/tests/test_vpn.py
- Some of test when run after some specific test, will run slower, make connections harder, causing tests to be flaky. Custom order in `conftest.py` was attempt of a workaround, which doesn't always help.
- Bug itself is know, but it is in Boringtun and only affects our natlab specific case (LLT-4112), because of that, it is very low priority.
- Reset vpn/derp servers, but without actually needing to restart docker containers.
**P.S.** This actually improve test speed quite abit. For example:
Running `pytest test/test_vpn.py` with custom order, takes 100~ seconds, but with current solution it takes 80~
**P.S.S.** This might also have side effect of improving stability for tests.
=> Resolve LLT-4102: Remove natlab test order and improve stability

Cargo.lock, changelog.md, crates/telio-relay/Cargo.toml, crates/telio-relay/src/derp/http.rs
There's a new DoS vulnerability in `webpki` crate reported by RustSec. (see https://rustsec.org/advisories/RUSTSEC-2023-0052)
`webpki` is an indirect dependency of `telio-relay`and this caused deny linter job to fail.
`telio-relay`-> `tokio-rustls` -> `rustls` -> `webpki`
Update `tokio-rustls`.
=> telio-relay: Bump tokio-rustls version

changelog.md, src/device/wg_controller.rs
Wireguard mandates that every connected peer has a unique IP address. So far we haven't validated that that is the case in our meshnet config. 
We have two types of peers, internal and external. Internal peers will never have IP collisions with each other, but external peers might have collisions with internal and/or external peers. Added here is a deduplication step where overlapping IPs are removed from external peers. If two or more external peers have the same IP, only the first one specified in the config will keep the IP.
=> LLT-3913: Deduplicate IPs of external meshent peers

.gitignore, changelog.md, crates/telio-dns/src/dns.rs, crates/telio-dns/src/nameserver.rs, crates/telio-dns/tests/nameserver.rs
We need support for IPv6 DNS requests
Handle IPv6 packets in a similar way as we handle IPv4 packets
=> Add support for IPv6 packet handling in telio-dns

nat-lab/tests/test_lana.py, nat-lab/tests/utils/process/docker_process.py
`test_event_content_meshnet_node_upgrade_direct` and `test_lana_with_second_node_joining_later_meshnet_id_can_change` are flaky.
`test_event_content_meshnet_node_upgrade_direct` failed due to a unhandled utf-8 decode error, which this PR fixes.
`test_lana_with_second_node_joining_later_meshnet_id_can_change` flakyness cause is unknown and might be a caught bug by the test. This PR marks it as flaky.
=> Natlab police fix flaky tests

changelog.md, crates/telio-relay/src/derp/mod.rs, nat-lab/tests/test_events.py, nat-lab/tests/test_fire_connecting_event.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_reconnections.py
Telio sometimes tries to reconnect with Derp server when already stopped
Ensure that Derp doesn't try to reconnect when the Multiplexer channel is closed
=> [LLT-3875] Fix derp disconnections

.github/workflows/gitlab.yml, .gitlab-ci.yml, changelog.md, crates/telio-lana/Cargo.toml, crates/telio-lana/src/event_log_file.rs, crates/telio-lana/src/lib.rs, crates/telio-lana/src/moose_callbacks.rs, crates/telio-nurse/src/data.rs, crates/telio-nurse/src/heartbeat.rs, crates/telio-nurse/src/nurse.rs, src/device/mod.rs
Since version 4.0, we have been sending quality events for both meshnet and VPN. To differentiate whether the library is used solely for VPN or with meshnet, a 'meshnet_enabled' field has been added.
It not possible to know from analytics if meshnet is being used.
Added 'meshnet_enabled' field.
=> Update moose, add 'meshnet_enabled' field

nat-lab/tests/test_client_basic_stun.py
Two pipelines failed recently due test_client_basic_stun timeouts on Windows VMs.
In this PR, we mark the test as flaky and create an issue to investigate the timeouts: LLT-4213
=> Natlab police Mark test_client_basic_stun as flaky

nat-lab/tests/conftest.py, nat-lab/tests/telio.py, nat-lab/tests/utils/process/docker_process.py, nat-lab/tests/utils/process/process.py, nat-lab/tests/utils/process/ssh_process.py
Until now, if an exception was thrown during test execution, whether for timing out or any other reason, context managers were not able to properly exit. For instance, when timing out from pytest-timeout, the plugin throws a TimeOutError exception and it doesn't allow the user to catch it. Instead it handles it internally and replaces it by a pytest.fail() call, which in its turn raises a Fail exception.
Our actual implementation doesn't handle every kind of exception, naturally, and in every test whether we have an active ssh or docker connection the teardown needs to be carefully handled so that the cleanup takes place.
There was two main issues:
- After exception was thrown, event loop would close before cleanup takes place (mainly for docker/ssh connections)
- Client instance would …
=> natlab: Fix test teardown

nat-lab/tests/test_network_switch.py, nat-lab/tests/test_reconnections.py
Tests test_mesh_network_switch and test_mesh_reconnect are passing constantly, so they shouldn't be marked as flaky.
Remove their flaky marks.
=> Natlab police: unmark passing tests

linkers/dld
Sed command works a bit differently in mac, hence in its current state it wasn't possible to build shared library for android applications.
Add support for sed command in the dld script for mac as well.
=> Add support for sed in mac

changelog.md, nat-lab/tests/test_dns.py, src/device/mod.rs
*MagicDNS does not include self-domain in the `.nord` authority zone*
*Add self nordname as well as self IP address to the DNS records*
=> Add self host and ip to DNS records

Cargo.lock, crates/telio-utils/Cargo.toml, crates/telio-utils/src/repeated_actions.rs
It was previously disabled due to failing on tarpaulin builds. No more information was available but when run without tarpaulin it also seemingly randomly failed. It turns out that the loop run 4 iterations and the last one was for the 300ms which should have triggered both the 100ms and 150ms action. Since it selected them in a random order, the test failed.
This change removes the loop + spawn which only made it less clear what is happening. Instead we explicitly spell out each assertion for each action we expect to happen. The last part where both actions are expected is verified using sets to make sure that the order doesn't matter.
=> Reenable RepeatedActions test

changelog.md, crates/telio-traversal/src/endpoint_providers/stun.rs
The problem with failing STUN session was already fixed in https://github.com/NordSecurity/libtelio/pull/115, but the task demands also some test for the correct behavior. 
Because the session fail was caused by starting STUN session when the corresponding WG peer was not ready, this commit adds a test to check if STUN endpoint provider correctly waits until the desired WG peer appears.
=> [LLT-4179] Add test for stun with no WG peer

Cargo.lock, changelog.md, crates/telio-lana/Cargo.toml, crates/telio-lana/src/event_log_file.rs, crates/telio-lana/src/lib.rs, crates/telio-lana/src/moose_callbacks.rs, src/device/mod.rs
Libtelio updated moose to a new async version which report’s it’s errors not by return but by callback.
One of the callbacks, `moose::InitCallback`, should be waited for and in case of error, analytics should be disabled entirely.
Wait for `moose::InitCallback` value with a 2s timeout and in case there's an error, lana initialization fails with just an error message, continuing libtelio startup.
=> lana: Add moose init callback validation

.github/workflows/gitlab.yml, changelog.md, nat-lab/tests/config.py, nat-lab/tests/test_process.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/network_switcher/network_switcher_windows.py, nat-lab/tests/utils/vm/mac_vm_util.py, nat-lab/tests/utils/vm/windows_vm_util.py, release.py
MacOS VM has been updated to Catalina (previously Big-Sierra). Catalina
has different directory structure, and `/workspace` is not writeable.
Instead, copy the requires files to `/var/root/workspace`.
For some reason with libvirt Windows network interface names are not
consistent across different machines, i.e. the names are different when
running on my computer and when running on CI. Add some code to detect
the names of interfaces by their IP address.
`test_process_run_fail` was failing because of different error messgage
from ping. Rewrite the test to use `bash -c exit 77`.
=> Migrate natlab VMs to libvirt

nat-lab/tests/test_mesh_plus_vpn.py
*test_vpn_plus_mesh_over_direct[ConnectionTag.WINDOWS_VM-AdapterType.WireguardGo] is flaky*
*Marked test_vpn_plus_mesh_over_direct[ConnectionTag.WINDOWS_VM-AdapterType.WireguardGo] as xfail until it's properly fixed*
=> Add xfail mark to test_vpn_plus_mesh_over_direct

nat-lab/tests/test_direct_connection.py
Direct working path is failing on natlab nightly, hence being marked xfail.
=> Mark direct test xfail

nat-lab/tests/test_process.py
*test_process_run_not_found is flaky*
*Disabling it for now, marking as flaky and submitted a ticket to properly fix it*
=> mark test_process_run_not_found as flaky

nat-lab/tests/test_mesh_plus_vpn.py
*test_vpn_plus_mesh_over_different_connection_types[ConnectionTag.WINDOWS_VM-AdapterType.WireguardGo] test is flaky*
*Marking it as xfail until it's fixed*
=> Add xfail mark to flaky test

Cargo.lock, Cargo.toml, changelog.md, clis/derpcli/Cargo.toml, clis/interderpcli/Cargo.toml, clis/tcli/Cargo.toml, crates/telio-crypto/Cargo.toml, crates/telio-dns/Cargo.toml, crates/telio-firewall/Cargo.toml, crates/telio-lana/Cargo.toml, crates/telio-model/Cargo.toml, crates/telio-nat-detect/Cargo.toml, crates/telio-nurse/Cargo.toml, crates/telio-proto/Cargo.toml, crates/telio-proxy/Cargo.toml, crates/telio-relay/Cargo.toml, crates/telio-sockets/Cargo.toml, crates/telio-task/Cargo.toml, crates/telio-traversal/Cargo.toml, crates/telio-utils/Cargo.toml, crates/telio-wg/Cargo.toml, docs/cargo_dependency_ordering.md, wireguard-go-rust-wrapper/Cargo.toml
There are a lot of dependencies that are shared between our crates, making it easy to miss something when updating those shared dependencies. Also, our dependencies were not very well organized everywhere.
In this PR, workspace dependencies are used for any dependency that's used at least twice, with the exception of our fuzzer crates and `wireguard-go-rust-wrapper`. The dependencies are now also reorganized, where the sections are ordered `dependencies, dev-dependencies, build-dependencies`, with platform-specific dependencies coming after that, with their internal ordering the same. Within each dependency section, the dependencies are now group as `non-workspace deps, workspace deps, git deps, internal crates`, and each such group has been alphabetized.
=> LLT-3451: Use workspace dependencies

Cargo.lock, crates/telio-sockets/Cargo.toml
Before this change, when building this crate from `crates/telio-sockets` directory the compilation would fail. Because cargo would select socket2 in the 0.4.x version which lacks functions used in this crate. When build from top level libtelio directory cargo would select newer version 0.5.x which would work correctly. Which is why bumping to 0.5.x is safe since it is eitherway the only version that compiles and one which is selected when whole libtelio is being built.
=> Fix test building inside of the telio-sockets crate

nat-lab/tests/test_process.py, nat-lab/tests/utils/process/docker_process.py, nat-lab/tests/utils/process/process.py, nat-lab/tests/utils/process/ssh_process.py
The assertion which checks if the not existing executable is on the list of running processes, would **always** fails. But it's almost never reached in the test since at almost the same time the subprocess creation is throwing expected exception which most of the time is slightly faster/earlier. This is because we only wait for the stdout ready event which happens before we check the exit code and trigger an exception.
Since the assertion would always fail when reached and is occasionally reached, it is safe to remove it since it is incorrect.
This has been confirmed with additional logging and also by adding a sleep before the `raise` in the `DockerProcess.execute` which causes consistent test failures due to wrong exception being thrown.
Snippet of run with additional logging:
``` …
```
=> Remove assertion which always fails but races with the rest of the test

changelog.md, crates/telio-traversal/src/endpoint_providers/stun.rs, src/device/mod.rs, src/device/wg_controller.rs
An infinite loop was created in our STUN handler because a timeout was set too late. The timeout determines if we should try to start a STUN session or wait, but it was set after trying to start the STUN session. In cases where starting the STUN session failed, the timeout would never be updated, making the code think that we should start a STUN session, even though we just tried, leading to an infinite loop.
Add error handling to the affected call site to transition to the right state
There will be a follow-up PR to add tests for this case. For this PR, there is just manual verification that it solves the issue
=> LLT-4306 Fix infinite loop in STUN handler

nat-lab/tests/test_direct_connection.py, nat-lab/tests/utils/router/linux_router.py, src/device/wg_controller.rs
After migrating to libvirt test_direct_working_paths was failing occasionally, the ping after establishing direct connection fails. Looking at the [logs](https://bucket.digitalarsenal.net/low-level-hacks/vpn/client/libtelio-build/-/jobs/9259504#L1938) we can see that the connections is downgraded to the Relay path after blocking derp relay connection.
It happens mostly with:
```
(
STUN_PROVIDER,
ConnectionTag.DOCKER_SYMMETRIC_CLIENT_1,
ConnectionTag.DOCKER_OPEN_INTERNET_CLIENT_1,
DOCKER_OPEN_INTERNET_CLIENT_1_IP,
),
(
LOCAL_PROVIDER,
ConnectionTag.DOCKER_SYMMETRIC_CLIENT_1,
ConnectionTag.DOCKER_OPEN_INTERNET_CLIENT_1,
DOCKER_OPEN_INTERNET_CLIENT_1_IP,
),
(
LOCAL_PROVIDER,
ConnectionTag.DOCKER_CONE_CLIENT_1,
ConnectionTag.DOCKER_OPEN_INTERNET_CLIENT_1,
DOCKER_OPEN_INTERNET_CLIENT_1_IP,
), …
```
=> Fix test_direct_working_paths

nat-lab/tests/test_connection_states.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_network_switch.py
Some tests were passing while marked as flaky and there are some new tests which need to be marked as flaky.
Update `python.xfail` marks in our natlab tests
=> Natlab police: update flaky tests marks

Cargo.lock, crates/telio-lana/Cargo.toml, crates/telio-sockets/Cargo.toml, crates/telio-sockets/src/protector/linux.rs, crates/telio-sockets/src/protector/windows.rs, crates/telio-sockets/src/socket_pool.rs
There was no tests that verify telio-sockets with ipv6.
Added tests that verify both ip v4 and v6.
=> Add tests that verify working ip v4/v6 sockets.

.github/workflows/ci.yml, .github/workflows/coverage.yml, crates/telio-sockets/src/protector/linux.rs
This is a port from previous version of CI and uses the same command as previously.
There might seem to be multiple other and better ways to do it but they are all broken in some ways.
We could use the action https://github.com/actions-rs/tarpaulin but that one is no longer maintained. The last version of tarpaulin it works with is 0.22 from October 2022 and the fix is still not merged in after multiple months: https://github.com/actions-rs/tarpaulin/pull/23 . Additionally there are discussions to deprecate this action: https://github.com/actions-rs/tarpaulin/issues/6
Alternatively we could have used the 'official' docker image of tarpaulin: https://hub.docker.com/r/xd009642/tarpaulin . This will not work since when github action runs in a docker, the container is not started with enough …
=> Add tarpaulin based code coverage job

.github/workflows/gitlab.yml
The new version no longer runs tarpaulin job since it is now run on github.
=> Use latest 0.2.3 version of downstream pipeline

.cargo/config_apple_tvos, Cargo.lock, changelog.md, crates/telio-dns/src/bind_tun.rs, crates/telio-nurse/src/heartbeat.rs, crates/telio-sockets/Cargo.toml, crates/telio-sockets/src/native.rs, crates/telio-sockets/src/protector/apple.rs, crates/telio-sockets/src/protector/mod.rs, crates/telio-sockets/src/socket_params.rs, crates/telio-sockets/src/socket_pool.rs, crates/telio-wg/src/adapter/boring.rs, crates/telio-wg/src/adapter/mod.rs, crates/telio-wg/src/wg.rs, src/device/mod.rs
Apple team is evaluating needed work for having NordVPN app for apple TV. And for that libtelio should be compiled for that target as well.
For the time being, aarch64-apple-tvos is a [Tier 3 rustc target](https://doc.rust-lang.org/nightly/rustc/platform-support/apple-tvos.html) so it doesn't have official rust support, this means there's no rust std lib available and many crates doesn't support it neither.
This PR makes the necessary changes to make libtelio compatible with this target, and adds a patch section to cargo manifest that is used only when this target is used, as demonstrated in: [libtelio-build!104 (diffs)](https://bucket.digitalarsenal.net/low-level-hacks/vpn/client/libtelio-build/-/merge_requests/104/diffs).
=> Build libtelio for apple tvOS target on arm64 

.github/workflows/gitlab.yml, .gitlab-ci.yml
apple-tvos build job has been integrated into libtelio-build CI and a new tag has been release, now its reference has to be updated.
Bump libtelio-build reference.
=> [LLT-4361] build: Bump libtelio-build ref

crates/telio-nurse/src/heartbeat.rs, crates/telio-nurse/src/qos.rs
After a few analytic interval long pause, telio sends analytic data one after another to catch up. Setting the tick to skip the missed ticks.
=> LLT-4106: Skip ticks on analytics interval after telio was paused

changelog.md, crates/telio-firewall/src/firewall.rs
So far there has been no conntrack logic for ICMP. The firewall flow for an inbound ICMP packet has been:
1. If peer is on whitelist, allow
2. If ICMP packet type is blocked, block
3. Allow
With these changes, outbound ICMP connections create cache entries, and the firewall flow becomes:
1. If peer is on whitelist, allow
2. If peer connection is in the cache, allow
3. If ICMP packet type is blocked, block
4. Allow
=> LLT-4013: Add conntrack logic for ICMP

Cargo.lock, changelog.md, crates/telio-model/src/api_config.rs, crates/telio-traversal/Cargo.toml, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/last_handshake_time_provider.rs, crates/telio-traversal/src/lib.rs, src/device/mod.rs
When peer is not responsive we still send messages to it from CrossPingCheck which causes increased energy usage.
Suspend CPC for unresponsive peers.
When the last handshake time for a given peer is above 180s we should suspend the CrossPingCheck tasks for that peer.
I've run the whole nat-lab with this feature turned on and it all passed. Separate MR will add nat-lab test(s) with this feature explicitly tested.
=> Suspend CPC and SessionKeeper for unresponsive peers.

nat-lab/tests/test_direct_connection.py, nat-lab/tests/utils/router/linux_router.py, nat-lab/tests/utils/router/mac_router.py, nat-lab/tests/utils/router/router.py, nat-lab/tests/utils/router/windows_router.py
There was a bug in our STUN handler that would cause an infinite loop in some scenarios recently. We prioritized getting a fix out, leaving the task of adding a regression test for later. This is that regression test.
The bug was triggered when there was a socket error to the STUN server after already establishing a STUN session.
1. Establish direct connection between two nodes
2. Break UDP connection to derp servers to make STUN unreachable
3. Verify that there aren't many STUN requests being made
To fail the test, comment out line `558` in `stun.rs` and run the test.
=> LLT-4306: Add regression test for STUN infinite loop

.github/workflows/gitlab.yml, .gitlab-ci.yml
Problem
Release pipelines still use rust in version 1.68.0. This updates release pipelines to the new version 1.72.0
Solution
Bump telio-bulid to v0.3.3
=> Bump libtelio-build to v0.3.3

dod.yml
During one of the libtelio team retro's, a wish was expressed to add more attention to tests. E.g. every new functionality should be covered by tests. This PR adds a reminder in Definition of Done checks to write those tests.
=> Add a reminder about tests in DoD

crates/telio-model/src/api_config.rs, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/last_handshake_time_provider.rs, nat-lab/tests/telio.py, nat-lab/tests/telio_features.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_telio_tasks.py, src/device/mod.rs
In the test we wait for cross ping check to stop sending CMM due to the detection of peer as unresponsive and only after that we reenable the peer and check that direct connection is reestablished.
As discussed in previous PR, feature flag is moved under the direct feature and turned on by default: https://github.com/NordSecurity/libtelio/pull/160#discussion_r1357869247
=> Add test that verifies succesful reconnection with skip_unresponsive_peers feature

changelog.md, crates/telio-nurse/src/heartbeat.rs, crates/telio-relay/src/multiplexer/mod.rs, crates/telio-traversal/src/endpoint_providers/stun.rs
During the rust version update there were left some clippy allow exceptions. 
Fix them.
I also updated the changelog. I forgot to do that in the rust version update PR.
=> Fix clippy allows

changelog.md, crates/telio-firewall/src/firewall.rs
A previous PR added logic to the firewall for dealing with ICMP packets. That PR didn't include handling of ICMP error types, in order to keep the PRs simple. This PR handles that.
An ICMP error packet contains the original packet as it's body. The ICMP cache key builder will now, when it sees an error type, unpack the body and try to build a cache key from that.
=> LLT-4286: Add logic for ICMP error types in firewall

nat-lab/tests/test_direct_feature.py, src/device/mod.rs
This reverts commit bf7c8e7dff9e098c12c8586cebf6721897886610.
Disable upnp from default direct features  while fixing this issue LLT-4335
=> RemoveUpnp to Default direct features

.cargo/config_apple_tvos, Cargo.lock, changelog.md, crates/telio-sockets/Cargo.toml
There are “undefined refernce to kSCNetworkInterfaceTypeIrDA” errors when one tries to build iOS application with libtelio v4.1.1
We need to use a bit modified version (our fork) of `system-configuration` crate
=> [LLT-4432] Fix iOS linking issue

.github/workflows/gitlab.yml, .gitlab-ci.yml, Cargo.lock, changelog.md, crates/telio-lana/src/event_log_file.rs, crates/telio-lana/src/lib.rs, crates/telio-model/Cargo.toml, crates/telio-model/src/event.rs, crates/telio-model/src/mesh.rs, crates/telio-nurse/src/data.rs, crates/telio-nurse/src/heartbeat.rs, crates/telio-nurse/src/nurse.rs, crates/telio-nurse/src/qos.rs, crates/telio-nurse/src/rtt/ping.rs, crates/telio-traversal/src/session_keeper.rs, crates/telio-utils/src/dual_target.rs, crates/telio-utils/src/lib.rs, crates/telio-utils/src/repeated_actions.rs, crates/telio-wg/src/uapi.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_lana.py, nat-lab/tests/test_lana_validator.py, nat-lab/tests/utils/analytics/event_loader.py, nat-lab/tests/utils/analytics/event_validator.py, src/device/wg_controller.rs
We need to collect analytics on IPv6 usage. But current WG implementations does not distinguish data between IP protocols.
The following solution is being used:
- Add IPv4/IPv6 flags/bits in connectivity matrix.
- Add `rtt6` collection, using `ICMPv6` protocol. Additionally, to get a more clear picture of IP protocol health, `rtt_loss` / `rtt6_loss`  which collects percentages of lost `ICMP` / `ICMPv6` packets.
=> LLT-3951 IPv6 analytics

changelog.md, src/device/mod.rs
Before this change, failing call to wait_for_listen_port could make the disabling of meshnet (set_config with None) fail. There is no reason for that so the call to wait_for_listen_port is moved to the part executed only when the meshnet is enabled.
=> When disabling meshnet, don't wait for wg listen port

dod.yml
Before this change the rendered link was:
https://github.com/NordSecurity/blob/main/docs/git_commit_messages_requirements.md
but should be:
https://github.com/NordSecurity/libtelio/blob/main/docs/git_commit_messages_requirements.md
=> Correct the git commit guidelines link in dod

changelog.md, crates/telio-model/src/lib.rs, crates/telio-model/src/validation.rs, nat-lab/tests/test_dns.py, src/device/mod.rs, src/ffi/mod.rs
As we start allowing users to rename peer, magic DNS needs to support both the “official” name and these custom names.
Parse nickname records and add them to dns resolver so that we can properly resolve both “official” and custom names.
=> Add magicdns support for two dns bindings

changelog.md, crates/telio-firewall/benches/firewall_bench.rs, crates/telio-firewall/src/firewall.rs, crates/telio-model/src/api_config.rs, crates/telio-model/src/mesh.rs, crates/telio-nurse/src/qos.rs, crates/telio-traversal/src/session_keeper.rs, crates/telio-utils/src/dual_target.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/telio.py, nat-lab/tests/telio_features.py, nat-lab/tests/test_dns.py, src/device/mod.rs, src/device/wg_controller.rs
There is no feature flag for the introduced IPv6 changes which are meant to be disabled by default, but which should be tested with all of the new changes.
Add IPv6 feature flag, so we will be able to use battle-tested IPv4 implementation on production, but also a possibility to test our new changes with newly introduced IPv6 support.
=> [LLT-4124] Add IPv6 feature

.github/workflows/ci.yml, .github/workflows/nagger.yml
Nagger is not run on github for libtelio
Use the latest nagger version available on github.
=> Add nagger job using the latest (2.0) version

crates/telio-model/src/api_config.rs, nat-lab/tests/telio_features.py, nat-lab/tests/test_dns.py, src/device/mod.rs, src/device/wg_controller.rs
Upserting dns records with nicknames is already implemented, this just adds the capability to turn it on/off via feature config. Default is off.
Note to myself - update feature config page after merge
=> add nicknames to features

nat-lab/tests/test_dns.py
This test is the most common failed test in the last night run. In local reproduction it was seen that the nslookup call sometimes takes more time, so a timeout is increased.
=> Fix flaky test_dns_duplicate_requests_on_multiple_forward_servers

nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_dns.py
Couple of tests, which uses `tcpdump`'s stdout, waits predefined amount of time, to check the output. Sometimes it lags, and tests fails (are flaky).
Use unbuffered  `tcpdump`'s mode.
=> Fix flaky natlab's tests with tcpdump

changelog.md, crates/telio-lana/src/event_log_file.rs, crates/telio-lana/src/event_log_moose.rs
When receiving heartbeat events on analytics there is no way to filter/group/analyze those events by NordVPN application versions. Thus some of the dashboard filters cannot be implemented.
Copy NordVPN application version context field from nordvpnapp tracker.
=> lana: Add nordvpn app version to moose context

Cargo.lock, Cargo.toml, changelog.md, crates/telio-lana/src/event_log_file.rs, crates/telio-lana/src/event_log_moose.rs
When receiving heartbeat events on analytics there is no way to filter/group/analyze those events by NordVPN application versions. Thus some of the dashboard filters cannot be implemented.
Copy NordVPN application version context field from nordvpnapp tracker.
=> [Backport] lana: Add nordvpn app version to moose context

crates/telio-lana/src/event_log_moose.rs
Previous changes introduced the parsing of meshnet specific data from the nordvpnapp tracker context, which is never set.
Stop parsing absent data from nordvpnapp tracker context.
=> fix: lana: Stop parsing meshnet info from nordvpnapp tracker

ci/build_libtelio.py, nat-lab/tests/config.py, nat-lab/tests/mac_wg.py, nat-lab/tests/mesh_api.py, nat-lab/tests/test_mesh_api.py, nat-lab/tests/test_verify_pk_on_packets.py, nat-lab/tests/utils/connection_tracker.py
Changes:
1. python-wireguard hardcodes opening of `*.so` file which obviously fails on macos. To fix that alternative, pure python implementation of the key derivation is provided.
2. `conntrack` cli is not available on macos, so on macos conntrack python wrapper always return no out of limits
3. the official architecture name of arm on macos is `arm64` but the corresponding name in the rust world is `aarch64` so some translation is added.
This results in most of the tests passing, example end result:
`47 failed, 177 passed, 1 skipped, 181 deselected, 15 xfailed, 36 xpassed`
=> Changes for running nat-lab from macos host

Cargo.lock, changelog.md, crates/telio-dns/Cargo.toml, crates/telio-dns/src/forward.rs, crates/telio-dns/src/nameserver.rs, crates/telio-dns/src/resolver.rs, crates/telio-dns/src/zone.rs, crates/telio-dns/tests/nameserver.rs, nat-lab/tests/test_dns.py
The initial problem was that if the forward lookup from trust-dns fails, the failure is not indicated to libtelio. Instead the response buffer was filled with an empty lookup response. This, combined with the doubled retry mechanism (OS and trust-dns) produced some issues on IOS.
Patched the trust-dns so now it indicates the failure and from libtelio side we try to copy the server behavior and do not respond to this requests.
=> Do not answer to DNS request if forward lookup fails

changelog.md, nat-lab/tests/telio.py, nat-lab/tests/test_mesh_exit_through_peer.py, src/device/mod.rs
Make sure that exit node events are marked as exit node ones.
When a node stops begin exit node, an event is presented 
Just base "is_exit" field in event on the ip_addresses, not the existence of the ExitNode in the requested state.
=> [LLT-4427] Fix exit node events

nat-lab/requirements.txt
`aiohttp` updated during the weekend and broke all nat-lab pipelines. This forces `aiohttp` version to 3.8.6 in order to unblock the pipelines.
=> Update requirements.txt or nat-lab by enforcing exact version of aiohttp

nat-lab/tests/test_dns.py
Seems that sometimes on CI the second server is selected by trust-dns. So instead of expecting that the *first* server is always asked about the A record, we can check that only one server is asked for A.
Before this change, when the test failed the `tcpdump` output was:
```
14:19:02.883980 IP 192.168.101.104.60221 > 1.1.1.1.53: 30843+ A? google.com. (28)
14:19:02.890200 IP 1.1.1.1.53 > 192.168.101.104.60221: 30843 1/0/0 A 142.250.185.78 (44)
14:19:02.890753 IP 192.168.101.104.54107 > 8.8.8.8.53: 3410+ AAAA? google.com. (28)
14:19:02.903749 IP 8.8.8.8.53 > 192.168.101.104.54107: 3410 1/0/0 AAAA 2a00:1450:4001:80b::200e (56)
```
=> Fix test_dns_duplicate_requests_on_multiple_forward_servers

nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_events.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_vpn.py
There are a lot of tests which are failing, which makes CI quite unreliable.
This PR marks with `xfail` those of them which are failing more often, or the way in which they failed is alarming.
=> [nl-police] Mark flaky tests

Cargo.lock, changelog.md, crates/telio-traversal/src/endpoint_providers/mod.rs, crates/telio-traversal/src/endpoint_providers/stun.rs, crates/telio-wg/Cargo.toml, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_events.py, src/device/mod.rs
Our wg-stun implementation does not support IPv6.
Add support for IPv6 in the wg-stun implementation, bump libtelio-build to version which uses Nordderper supporting that feature as well.
=> Llt 3950 wg stun ipv6 support

changelog.md, crates/telio-firewall/src/firewall.rs
The TCP connection can be dropped by spoofing ICMP error packets. It's because the peer public key is not matched to the TCP connection conntrack thus allowing different peers to affect the connection
This PR adds a validation of the peer's public key before any action on the TCP connection is done
=> LLT-4502: Perform connection state tracking in telio firewall for each peer separately

nat-lab/tests/test_lana.py, nat-lab/tests/test_reconnections.py
Marked tests as flaky
- LLT-4591: test_lana_with_same_meshnet
- LLT-4593: test_mesh_reconnect
=> Mark test_mesh_reconnect and test_lana_with_same_meshnet as flaky

Cargo.lock, clis/tcli/Cargo.toml, clis/tcli/src/cli.rs, clis/tcli/src/main.rs, nat-lab/tests/telio.py
It would be nice to have timestamps in the tcli events command output.
The timestamps of events are recorded and displayed alongside events.
=> LLT-4584: Add timestamps to the tcli `events` output

nat-lab/tests/test_lana.py
During the weekend, lana tests has been failing several times. Lets mark them as flaky and attempt to fix later.
=> Mark several lana integration tests as flaky

nat-lab/tests/test_events.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_vpn.py
In the last week we have seen some failurs in windows tests. Some of the tests already have been marked as flaky for Wireguard-NT adapter type, but not for WireGuard-go. Weekly report shows, that flakyness is not dependant on the WG implementation, therefore marking WG-GO tests flaky as well.
=> Mark some windows tests as flaky

changelog.md
`changelog.md` wasn't reflecting what has been released, with more entries than should have been in the unreleased section.
Create section for each released version and move released features to the correct section
=> Update changelog.md to reflect recent releases

Cargo.lock, Cargo.toml, changelog.md
Branching off release v4.2 line, but would be nice to merge `Cargo.toml` version changes and `Cargo.lock` back into `main`
=> Release-candidate v4.2.0

.github/workflows/gitlab.yml, .gitlab-ci.yml, changelog.md, nat-lab/bin/client, nat-lab/bin/cone-gw, nat-lab/bin/fullcone-gw, nat-lab/bin/internal-symmetric-gw, nat-lab/bin/symmetric-gw, nat-lab/bin/upnp-gw, nat-lab/bin/vpn-server, nat-lab/docker-compose.yml, nat-lab/tests/utils/vm/windows_vm_util.py
At the moment nat-lab docker containers are being ran with root privileges, thus have all the kernel capabilities enabled, which is unsafe and not necessary. 
This PR restricts these containers capabilities, following the least privilege principle, and also adds other unrelated changes:
- Remove Windows VM firewall disablement for every test (done now during VM startup).
- Remove previously added windows VM debug logs which are no longer needed.
- Add custom peer names integration test that asserts the nodes can have their nicknames changed/removed.
=> LLT-4006: Restrict nat-lab containers capabilities

nat-lab/tests/test_dns.py
The failing tcpdump as logged in gitlab:
```
[2023-12-07 14:05:33] FAILED tests/test_dns.py::test_dns_duplicate_requests_on_multiple_forward_servers - AssertionError: 13:45:54.047097 IP 192.168.101.104.55778 > 1.1.1.1.53: 40350+ A? google.com. (28)
[2023-12-07 14:05:33]   13:45:54.047795 IP 192.168.101.104.58864 > 1.1.1.1.53: 2779+ A? google.com. (28)13:45:54.053094 IP 1.1.1.1.53 > 192.168.101.104.55778: 40350 1/0/0 A 142.250.184.206 (44)13:45:54.053593 IP 1.1.1.1.53 > 192.168.101.104.58864: 2779 1/0/0 A 142.250.185.110 (44)13:45:54.053713 IP 192.168.101.104.53814 > 8.8.8.8.53: 56612+ AAAA? google.com. (28)13:45:54.054460 IP 192.168.101.104.52010 > 8.8.8.8.53: 8245+ AAAA? google.com. (28)13:45:54.067647 IP 8.8.8.8.53 > 192.168.101.104.53814: 56612 1/0/0 AAAA 2a00:1450:4001:810::200e …
```
=> Sometimes trust-dns sends 2 requests to the same server for the same hostname - align tests

nat-lab/tests/test_network_switch.py, nat-lab/tests/utils/network_switcher/network_switcher_mac.py, nat-lab/tests/utils/router/mac_router.py
Both VPN and linux gateways were being added to the routing table as default destinations, so when switching to the secondary network, deleting the default route would also delete the VPN route.
Specify on the routing table the subnet destination of the packets that should be routed through the VPN interface. This way we can delete the default route while switching networks without touching the VPN route.
=> natlab: Specify destination on macos VPN routing rule

changelog.md, wireguard-go-rust-wrapper/wireguard-go/bind_std.go, wireguard-go-rust-wrapper/wireguard-go/bind_windows.go, wireguard-go-rust-wrapper/wireguard-go/mark_default.go, wireguard-go-rust-wrapper/wireguard-go/platform_specific_windows.go
Wireguard-go could crash if winrio initization fails. That is because in that case StdNetBind is returned from NewDefaultBind function instead of WinRingBind. Later this object was casted to the WinRingBind in order to call OpenOnLocalhost method. This commit adds new method OpenOnLocalhost to our interface FullBind and implements is for both WinRingBind and StdNetBind. It requires us to copy StdNetBind implementation for the upstream.
This is port of: https://github.com/NordSecurity/libtelio/pull/246
=> Fix crash in wireguard-go - port to release/v4.1

changelog.md, wireguard-go-rust-wrapper/wireguard-go/bind_std.go, wireguard-go-rust-wrapper/wireguard-go/bind_windows.go, wireguard-go-rust-wrapper/wireguard-go/mark_default.go, wireguard-go-rust-wrapper/wireguard-go/platform_specific_windows.go
Wireguard-go could crash if winrio initization fails. That is because in that case StdNetBind is returned from NewDefaultBind function instead of WinRingBind. Later this object was casted to the WinRingBind in order to call OpenOnLocalhost method. This commit adds new method OpenOnLocalhost to our interface FullBind and implements is for both WinRingBind and StdNetBind. It requires us to copy StdNetBind implementation for the upstream.
=> Fix crash in wireguard-go

Cargo.lock, Cargo.toml, changelog.md
Boringtun performs spurious rekeying
Use fixed boringtun (https://github.com/NordSecurity/boringtun/pull/8)
=> Use newer version of boringtun

.github/workflows/gitlab.yml, .gitlab-ci.yml
New version disables unattended-upgrades of linux vm.
Unattended upgrades were happening on linux vm causing pipelines to fail.
Disable them in libtelio build project.
=> Resolve LLT-4623: Update ref to libtelio build.

nat-lab/tests/helpers.py, nat-lab/tests/telio_features.py
Python3.11 doesn't allow mutable default values that contains `default_factory`.
[reference](https://docs.python.org/3/library/dataclasses.html#:~:text=default_factory%3A%20If%20provided%2C%20it%20must%20be%20a%20zero%2Dargument%20callable%20that%20will%20be%20called%20when%20a%20default%20value%20is%20needed%20for%20this%20field.%20Among%20other%20purposes%2C%20this%20can%20be%20used%20to%20specify%20fields%20with%20mutable%20default%20values%2C%20as%20discussed%20below.%20It%20is%20an%20error%20to%20specify%20both%20default%20and%20default_factory.)
Therefore `default_factory` has to be used.
=> Resolve LLT-4617: fix pytest collection error on python3.11

changelog.md, nat-lab/tests/test_dns.py, src/device/mod.rs
Currently it is not possible to use <something>.<nickname/hostname>.nord as a domain name. It is quite useful when single server in meshnet hosts multiple services.
Add wildcarded entries to the dns records list.
=> Add wildcarded subdomains to peers dns records

nat-lab/tests/test_client_basic_stun.py, nat-lab/tests/test_connection_states.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_events.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_mesh_remove_node.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_vpn.py
Some tests haven't failed for over a week, thus are considered no longer as flaky.
Some other tests failed during scheduled pipelines.
Remove/add flaky marks.
=> natlab police: Mark/unmark natlab tests

Cargo.lock, changelog.md
=> Update rustix v0.37.24 -> v0.37.27

nat-lab/tests/utils/process/docker_process.py
When `panic!` happens we don't get a full backtrace on nat-lab.
Enable backtrace printing via `RUST_BACKTRACE` environment variable. VMs are not supported since ssh process has no api to configure environment.
=> Set RUST_BACKTRACE=full in environment when starting processes on docker

Cargo.lock, Cargo.toml, changelog.md
Some tests panic in boringtun due to duration overflow when subtracting.
Update to boringtun 1.1.7 which likely fixes panic in duration overflow wen subtracting.
=> Update boringtun to 1.1.7 which uses saturating_sub to avoid duration overflow

Cargo.lock, Cargo.toml, changelog.md, crates/telio-model/src/config.rs, crates/telio-model/src/mesh.rs, crates/telio-utils/src/hidden.rs, src/device/mod.rs, src/ffi/mod.rs, src/ffi/types.rs
To have a better idea on during debugging, it is better if we have an idea of the ffi calls.
#instrument from tracing crate is not used as there is a separate task to add span ids which isn't implemented yet.
Log most of ffi calls and their parameters.
=> [LLT-4543] log ffi calls

crates/telio-nurse/src/nurse.rs
Nightly tests fails about 2-7% of the time due to missing moose events. Therefore lets add additional logging on moose calls to figure out whether nurse actually succeeded in event generation, and whether the event was in-fact passed into moose.
=> Collect information about moose callsites

.github/workflows/fuzzing.yml, Cargo.lock, changelog.md, clis/tcli/src/main.rs, crates/telio-crypto/src/lib.rs, crates/telio-dns/src/dns.rs, crates/telio-model/src/api_config.rs, crates/telio-wg/Cargo.toml, crates/telio-wg/fuzz/Cargo.toml, crates/telio-wg/fuzz/fuzz_targets/parse_get_packet.rs, crates/telio-wg/src/lib.rs, crates/telio-wg/src/pq.rs, crates/telio-wg/src/uapi.rs, src/device/mod.rs, src/device/wg_controller.rs
We want to make the VPN tunnel post-quantum safe.
The solution performs an initial wireguard connection during which a preshared key is established as the shared secret of the kyber768 key exchange mechanism.
The preshared key is used for the subsequent wireguard tunnel being created just after the  initial handshake
There isn't any unit or integration test because that's a separate task and @LukasPukenis is responsible for this one.
The PR doesn't contain the rekey mechanism for similar reasons, it's going to be implemented in subsequent PRs.
=> LLT-4614: implement wg post quantum handshake in libtelio codebase

crates/telio-sockets/src/protector/apple.rs
For some unknown reason, `socket2` API for binding sockets to interfaces does not work (Apple's case).
Reverting to _old_ method.
=> Revert apple's socket protector api

.github/workflows/gitlab.yml, .gitlab-ci.yml, Cargo.lock, Cargo.toml, android/templates/build.gradle, android/templates/init.gradle, android/templates/settings.gradle, changelog.md, clis/derpcli/src/conf.rs, clis/derpcli/src/main.rs, crates/telio-model/src/api_config.rs, crates/telio-relay/Cargo.toml, crates/telio-relay/src/derp/http.rs, crates/telio-relay/src/derp/mod.rs, deny.toml, ffi/bindings/android/java/com/nordsec/telio/Telio.java, ffi/bindings/android/java/com/nordsec/telio/libtelioJNI.java, ffi/bindings/android/wrap/java_wrap.c, ffi/bindings/linux/go/teliogo.go, ffi/bindings/linux/wrap/go_wrap.c, ffi/bindings/telio.h, ffi/telio.i, ffi/teliojava.i, linkers/dld, src/device/mod.rs, src/ffi/mod.rs
Libtelio is using hardcoded list of root certificate authorities (from Mozilla) to verify https certificates when connecting to derp. This can cause out of date / insecure / revoked certificates to be used if we don't update the hardcoded list on time.
Us operating system, built in mechanisms to validate certificates, since those are automatically (from our pov) updated when needed.
Tested on:
=> Use OS certificates instead of hardcoded mozilla list

.github/workflows/fuzzing.yml
The fuzzing CI jobs are failing on `cargo-fuzz` install stage or on the compilations stage, depending on the nightly version
Update nightly rustc 2023-06-01 seems to be the working middle ground
=> Fix fuzzing CI jobs

nat-lab/tests/test_events_link_state.py
Mark link state tests as flaky.
=> Mark link state tests as flaky

nat-lab/tests/test_dns.py, nat-lab/tests/test_events.py, nat-lab/tests/test_network_switch.py
- Removed `xfail` mark from tests that didn't fail in last 7 days.
- `test_vpn_network_switch` (with a MAC_VM) marked as flaky since it recently failed
=> Remove xfail marks form stable tests

Cargo.lock, Cargo.toml, changelog.md
This should fix rare crash during startup caused by negative duration.
=> Use boringtun with saturating duration it timers.rs

changelog.md, crates/telio-sockets/src/protector/apple.rs
When libtelio is selecting interfaces candidates to bind to for
underlying VPN configuration, multiple candidates may be available, in
certain circumstances libtelio would select interface without access to
the internet meaning, that VPN connection fails to be established. This
Pull requests adds additional requirement for interface to have "Router"
property when building candidate list.
=> LLT-4633 bind to interfaces which has router property only

changelog.md, crates/telio-sockets/src/protector/apple.rs
When libtelio is selecting interfaces candidates to bind to for underlying VPN configuration, multiple candidates may be available, in certain circumstances libtelio would select interface without access to the internet meaning, that VPN connection fails to be established. This Pull requests adds additional requirement for interface to have "Router" property when building candidate list.
=> Backport to main: LLT-4633 bind to interfaces which has router property only

Cargo.lock, Cargo.toml, changelog.md
The changes include more logging and better error handling on socket methods failure.
Boringtun is silently ignoring `sendto()/recvfrom()` errors
Log errors in boringtun crate
=> Update boringtun to v1.1.9

.github/workflows/coverage.yml, crates/telio-sockets/src/protector/linux.rs, crates/telio-sockets/src/socket_pool.rs
Add privilege to make all tests passing under tarpaulin
Some tests lacked privileges to pass when run under tarpaulin
Run the tarpaulin with `sudo`
=> [LLT-4366] Make tests passing under tarpaulin

changelog.md, crates/telio-traversal/src/endpoint_providers/local.rs, crates/telio-traversal/src/endpoint_providers/mod.rs, crates/telio-traversal/src/endpoint_providers/stun.rs, crates/telio-traversal/src/endpoint_providers/upnp/mod.rs, src/device/mod.rs, src/device/wg_controller.rs
- `WG-STUN` currently works with either `IPv6` or `IPv4`.
- Exp. back-off is being reset by `wg_controller` on every poll.
- Introduce IPv6 -> IPv4 fallback before rotating to next `WG-STUN` server.
- Do not reset exp. back-off on  `wg_controller` poll, when in `BackingOff` state.
- Increase exp. backoff only when server list is exhausted.
=> LLT-4598 LLT-4698 WG-STUN IPv6 -> IPv4 fallback, exp backoff fixes

changelog.md, crates/telio-nurse/src/heartbeat.rs, crates/telio-nurse/src/lib.rs, crates/telio-nurse/src/nurse.rs, src/device/mod.rs, src/device/wg_controller.rs
Endpoint providers, CPC, SessionKeeper, upgrade_sync proxy and relay should be started only after the meshnet is started and configured. Also they should be stopped when the meshnet config is set to `None`.
Move Meshnet entities start to `set_config` method.
=> Llt 4490 start endpoint providers after meshnet

Cargo.lock, changelog.md, crates/telio-traversal/Cargo.toml, crates/telio-traversal/src/endpoint_providers/upnp/mod.rs, nat-lab/tests/test_upnp_connection.py
UPnP started blocking whole libtelio due to blocking sockets used in igd crate. In this case, a call to search_gateway() in third party igd crate blocks processing loop for UPnP endpoint provider, blocking all task_exec!()'s as well, including cross_ping_check pinging and its processing loop, then all CPC's functions using task_exec!() are blocked too and eventually blocks the device processing loop that uses CPC for endpoint validation. From there the whole libtelio is blocked.
Spawn a thread to run `search_gateway()` call on a dedicated pool for blocking tasks, using `tokio::task::spawn_blocking()`.
Also, during implementation it was found that the backing off was not working as expected, after the first iteration when the `PinnedSleep` completed a new instance was never being …
=> traversal: Fix libtelio block on upnp gateway search

Cargo.lock, Cargo.toml, crates/telio-relay/Cargo.toml, deny.toml
Recently `rust-security-framework` got a PR that includes all the changes we needed for tvOS. There's no release yet, but latest main branch contains all that we need so let's use an updated for of `rustls-platform-verifier` that uses official `rust-security-framework` repository.
=> Use rustls-platform-verifier without a dependency on custom rust-security-framework

.github/workflows/gitlab.yml, .gitlab-ci.yml
Maven upload may fail after os certificate issue.
Use more memory for maven upload to accommodate for the cargo metadata json that needs to be constructed.
=> Use v0.4.9 triggered-ref

nat-lab/tests/test_events_link_state.py
Sometimes the nodes fail to connect when the persistent keepalive periods are set to a low value, like 5 seconds. As this has nothing to do with the no-link detection mechanism, I removed them until the LLT-4718 will be fixed.
=> Remove link state testcase scenarios with short keepalive periods

changelog.md, crates/telio-nurse/src/qos.rs, crates/telio-nurse/src/rtt/ping.rs, crates/telio-utils/src/dual_target.rs, crates/telio-wg/src/uapi.rs, nat-lab/tests/test_lana.py
A few lana tests were failing as events were not being listed on the fetched database.
Initial investigation shown that if we have 2 nodes, where alpha supports only ipv6 and beta both ipv4 and ipv6, alpha's QoS fails to ping beta addresses (expectedly) as it doesn't support it. This way QoS will be busy pinging ([see](https://github.com/NordSecurity/libtelio/blob/b9fd30ad227195d46d8a0206d67857d09641220c/crates/telio-nurse/src/qos.rs#L186)), blocking the sending of the heartbeat event [here](https://github.com/NordSecurity/libtelio/blob/de92d11233a084645698ec0b04f5f183dd49c15d/crates/telio-nurse/src/nurse.rs#L228). 
Make QoS ping asynchronous, launching non-blocking parallel pings.
=> LLT-4616: Make QoS ping asynchronous

.github/workflows/gitlab.yml, .gitlab-ci.yml
Update reference to libtelio-build, which now checks out libtelio sources during upload to maven job in order to generate manifest.
=> Update reference to libtelio-build

nat-lab/tests/test_dns.py, nat-lab/tests/test_dns_through_exit.py, nat-lab/tests/utils/dns.py
`test_dns_through_exit` would sometimes fail. Local testing showed that `nslookup` was sometimes not returning any results. 
`test_dns.py` had abstracted calls to `nslookup` to a dedicated function but that function was not used in `test_dns_through_exit.py`. That function is now moved to a dedicated utils file to make it easier to share. Additionally, the function was made more stable by slightly increasing how long the test waits for a DNS response, removing the retry option passed to `nslookup` to allow it to retry infinitely, and lastly by setting the internal timeout for `nslookup` to only a second, which means it will retry over and over instead of just waiting.
Before the fix I could reliably reproduce the flakiness of `test_dns_through_exit`, with one of the variants failing on …
=> LLT-4674: Stabilize DNS queries in natlab tests

nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_events.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_mesh_remove_node.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_reconnections.py, nat-lab/tests/test_vpn.py
Xfail has given us more problems than benefits, by allowing us to let our natlab test suite deteriorate and by hiding test failures during development. We are now removing it, and disallowing it moving forward, to foster test quality and increase confidence in our tests.
Remove the remaining xfail marks.
=> LLT-4797: Remove xfail from all tests

Cargo.lock, crates/telio-wg/Cargo.toml
The wireguard-nt `get_config_uapi` call returns a garbage preshared key, even when not used for the peer.
Update `wireguard-nt-rust-wrapper` to 1.0.4 so that to include changes from https://github.com/NordSecurity/wireguard-nt-rust-wrapper/pull/4
=> Update wireguard-nt-rust to 1.0.4

nat-lab/tests/utils/connection/docker_connection.py, nat-lab/tests/utils/connection/ssh_connection.py, nat-lab/tests/utils/network_switcher/network_switcher_windows.py, nat-lab/tests/utils/vm/container_util.py
libvirt uses management interface to configure and/or provision the virtual machines, unfortunately this interface is completely controlled by libvirt and can issue/renew DHCP leases any time, especially if default route to it has been deleted (we used to do that in tests). This introduces competition against primary/secondary interfaces default routes which is used for testing. During tests - management interface should never be used, therefore this PR ensures, that this interface is disabled during tests.
Note that this will cause `vagrant ssh` to not work during tests, but one can always use `ssh vagrant@10.55.0.11` to connect to windows machines.
=> LLT-4799 Disable management interface during tests

crates/telio-wg/src/windows/tunnel/interfacewatcher.rs, crates/telio-wg/src/windows/tunnel/mtumonitor.rs
There are a few places that can deadlock on `dev stop` due to incorrect use of [CancelMibChangeNotify2](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-cancelmibchangenotify2#remarks).
Specifically:
-  https://github.com/NordSecurity/libtelio/blob/main/crates/telio-wg/src/windows/tunnel/interfacewatcher.rs#L108
- https://github.com/NordSecurity/libtelio/blob/main/crates/telio-wg/src/windows/tunnel/interfacewatcher.rs#
and
- https://github.com/NordSecurity/libtelio/blob/main/crates/telio-wg/src/windows/tunnel/mtumonitor.rs#L99
- https://github.com/NordSecurity/libtelio/blob/main/crates/telio-wg/src/windows/tunnel/mtumonitor.rs#L110
- https://github.com/NordSecurity/libtelio/blob/main/crates/telio-wg/src/windows/tunnel/mtumonitor.rs#L138
- …
=> LLT-4799: wg: Fix deadlock on interface callbacks when stopping

nat-lab/tests/test_dns.py, nat-lab/tests/utils/dns.py
On `test_dns_port`, `dig` command is used which has by default 5 seconds timeout for each retry (3 tries by default). 
Enabling magic_dns can take sometimes more than we expect and the 1s timeout from `wait_normal` might not be enough.
Increase command timeout from `wait_normal`->`wait_long` and assert we get process error when the 3 tries are finished.
There might be still an issue with libtelio, however as I could not reproduce the issue locally and the logs are no longer available these changes should place us in a better position to debug it if the test fails again in the future.
=> natlab: Add dig timeout to allow process failure

nat-lab/tests/test_network_switch.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/network_switcher/network_switcher.py, nat-lab/tests/utils/network_switcher/network_switcher_docker.py, nat-lab/tests/utils/network_switcher/network_switcher_mac.py, nat-lab/tests/utils/network_switcher/network_switcher_windows.py
Windows management interface is beind disabled during tests, but never reenabled, causing `vagrant ssh windows` to not work. 
Reenable windows management interface once test is done.
=> Resolve LLT-4812: Reenable windows management interface on natlab.

android/templates/init.gradle, changelog.md
Gradle invokes project in to ci/cd jobs
package-aar and upload-maven and in both of them
gradle project is in different dirs.
Using absolute path from build_libetlio script
causes an error as both of them ar run in
different jobs and as such path also changes.
This implementation switches to using file(..)
function that get paths relative to project dir.
They can be either android_aar or android_aar/main
due to gradle weirdness :/.
findManifest checks 4 possible locations.
=> [LLT-4729] Fix upload-maven ci/cd job

changelog.md, crates/telio-sockets/src/protector/apple.rs
After turning off meshnet on macOs, there are a series of "Unable to bind" error messages.
This happens because during cleanup sockets waiters are notified which tries to rebind to all the sockets again. As it is during cleanup, default interface sockets have already been closed and it is not able to bind hence the error message.
Removing the notify fixes the problem.
=> Dont notify socket waiter after cleanup

.github/workflows/wg_go_version_check.yml, crates/telio-wg/src/adapter/wireguard_go.rs, wireguard-go-rust-wrapper/src/lib.rs, wireguard-go-rust-wrapper/wireguard-go/main.go
1. There is a bug somewhere in our build system. Because of that it might happen that the old version of wireguard-go is linked into the release package. The bug is not found yet but this should protect us from releasing incorrect package.
2. Wireguard-go logs from panic are lost when telio.dll is run inside a windows service.
1. Temporary solution is to add an export with a version string in it to the wireguard-go library. Because it requires manual effort to update it a github actions job is added to monitor that the version is updated every time there are changes done to the wireguard-go lib itself. 
2. Print stacktrace to our logger in case of a panic
=> Llt 4827 wireguard go version check

.github/workflows/wg_go_version_check.yml, Cargo.lock, Cargo.toml, changelog.md, crates/telio-wg/src/adapter/wireguard_go.rs, wireguard-go-rust-wrapper/src/lib.rs, wireguard-go-rust-wrapper/wireguard-go/main.go
This is port of: https://github.com/NordSecurity/libtelio/pull/318
Additionally it bumps libtelio version for a new v4.1.6 release
=> Llt 4827 wireguard go version check + new release

nat-lab/tests/test_network_switch.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/network_switcher/network_switcher.py, nat-lab/tests/utils/network_switcher/network_switcher_docker.py, nat-lab/tests/utils/network_switcher/network_switcher_mac.py, nat-lab/tests/utils/network_switcher/network_switcher_windows.py
Windows network switcher function `get_network_interfaces` would return wrong interface list due to incorrect regex.
```
Configuration for interface "Ethernet Instance 0"
DHCP enabled:                         No
IP Address:                           10.55.0.11
Subnet Prefix:                        10.55.0.0/24 (mask 255.255.255.0)
Default Gateway:                      10.55.0.10
Gateway Metric:                       256
InterfaceMetric:                      15
Configuration for interface "Ethernet 2"
DHCP enabled:                         Yes
InterfaceMetric:                      15
Configuration for interface "Ethernet 3"
DHCP enabled:                         No
IP Address:                           10.66.0.11
Subnet Prefix:                        10.66.0.0/24 (mask 255.255.255.0) …
```
=> Resolve LLT-4812: Reenable windows management interface on natlab."

nat-lab/tests/telio.py
It is currently difficult to reproduce LLT-4600 and a couple of more Mac VM related flaky NAT-Lab tests.
Added network interface name and IP, routing table and the last 20 lines of syslog to a separate log file for MAC VM.
=> Add network info to Mac VM logs

nat-lab/tests/telio.py
Moved MacVM network info gathering earlier before telio is closed and cleaned up, because previously a lot of useful information had been missing due to the cleanup
Network gathering is now done before Telio is closed.
=> Moved MacVM network info gathering earlier before telio is closed.

Cargo.lock, Cargo.toml, build.rs, crates/telio-model/src/api_config.rs, crates/telio-utils/src/hidden.rs, src/device/mod.rs, src/device/wg_controller.rs, src/ffi/mod.rs, src/ffi/types.rs, src/lib.rs, src/libtelio.udl, tests/logger.rs, tests/uniffi_logger.rs
This PR is the first introduction of UniFFI into libtelio, but so far UniFFI isn't actually used. That comes in a later PR. 
With UniFFI we can make changes to our FFI code that is incompatible with SWIG and do general cleanup, so UniFFI is a breaking change, but this PR doesn't actually break anything yet. Instead it duplicates out FFI code and then cleans up the duplicate, but fear not, the duplication is not going to be long-lived.
=> Define UniFFI UDL

Cargo.lock, Cargo.toml, changelog.md, src/ffi/mod.rs
With the argument logging PR, we have accidentally introduced a check, which forbids NULL values in telio_connect_to_exit_node() arguments. Which is expected when client application attempts to route traffic.
=> Allow null values for telio_connect_to_exit_node() call

Cargo.lock, Cargo.toml, crates/telio-model/src/config.rs, src/ffi/mod.rs, src/libtelio.udl
The FFI functions for Telio currently take strongly typed objects, but consumers might have a platform-specific representation of those types and would have an easier time passing json-encoded strings. 
To make it easier for those consumers, this commit introduces functions to create objects from such strings. At this time we only see a need to do that for Features and Config, so the conversion functions have only been implemented for those types
=> LLT-4874: Add FFI functions to create Features and Config objects from JSON strings

nat-lab/tests/test_dns.py
test_dns_duplicate_requests_on_multiple_forward_servers has been flaky and we don't have proper output in the logs because tcpdump has empty stdout.
Improves the printing by labeling the stdout print to make it easier to identify when stdout was empty, and starts printing stderr as well in case something just went wrong
=> LLT-4899: Improve printing in test_dns_duplicate_requests_on_multiple_forward_servers

changelog.md, crates/telio-model/src/api_config.rs, crates/telio-traversal/src/endpoint_providers/mod.rs, crates/telio-traversal/src/endpoint_providers/stun.rs, crates/telio-traversal/src/endpoint_providers/upnp/mod.rs, nat-lab/tests/telio_features.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_network_switch.py, src/device/mod.rs, src/device/wg_controller.rs, src/libtelio.udl
Stun and upnp providers should not send packets when there is no peer that wants to upgrade to direct connection. That happens when all peers are either offline or already directly connected.
Pause Stun/Upnp providers in that case.
=> Stop stun and upnp when not needed

.github/workflows/fuzzing.yml, .github/workflows/gitlab.yml, .github/workflows/nagger.yml, .gitlab-ci.yml, Cargo.lock, Cargo.toml, changelog.md, clis/tcli/src/main.rs, crates/telio-crypto/src/lib.rs, crates/telio-dns/src/dns.rs, crates/telio-model/src/api_config.rs, crates/telio-pq/Cargo.toml, crates/telio-pq/fuzz/Cargo.toml, crates/telio-pq/fuzz/fuzz_targets/parse_get_packet.rs, crates/telio-pq/fuzz/fuzz_targets/parse_rekey_packet.rs, crates/telio-pq/src/conn.rs, crates/telio-pq/src/entity.rs, crates/telio-pq/src/lib.rs, crates/telio-pq/src/proto.rs, crates/telio-wg/Cargo.toml, crates/telio-wg/src/uapi.rs, crates/telio-wg/src/wg.rs, src/device/mod.rs, src/device/wg_controller.rs
It turned out that the problem was not with the PQ implementation but with the usage of sccahce in CI/CD which breaks `libtelio.a` in case it's built with a native C static library.
The `libteliio.a` static lib failed to link with with executable on Mac and Linux. The problem is solved by now in the build repo.
Revert the revert
=> LLT-4870 bring back post quantum

crates/telio-wg/src/link_detection.rs
The previous implementation returned a Some() value for time_since_last_rx even if the rx_bytes count was 0, which is wrong.
=> Fix time_since_last_rx

changelog.md, crates/telio-firewall/src/firewall.rs, crates/telio-nurse/src/qos.rs, crates/telio-nurse/src/rtt/ping.rs, crates/telio-wg/src/wg.rs
Ping timeout errors were being spammed into the logs of release versions of libtelio.
Besides changing the log level of this [specific log](https://github.com/NordSecurity/libtelio/pull/352/files#diff-5f3177de9978ef3efc6f9a22d22bba482cd008c98e79b921c2b7188268973fd3L150) to `DEBUG` the following changes were made:
- Clean or decrease the level of some logs.
- Skip analytics ping for unconnected peers and don't touch any data as analytics can still compute if the node is connected or not by analysing the connection time and the heartbeat interval.
=> LLT-4913: Decrease ping failure logs level

crates/telio-dns/src/zone.rs, nat-lab/tests/test_dns.py, rustfmt.toml
There was a few small leftovers from configurable ttl.
Clean up in this MR.
=> [LLT-4938] Fix up leftovers form configurable ttl.

changelog.md, crates/telio-model/src/validation.rs, nat-lab/tests/mesh_api.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_events.py, nat-lab/tests/test_mesh_api.py, src/device/mod.rs
Nickname RFC allows nicknames to be passed
in any case. So there is no valid reason
to filter out nicknames that are only in
lowercase.
It was also agreed that nickname passed
with node event should be identical to one
passed via meshnet config.
Remove validation that expects nicknames to be only in lowercase.
TrustDNS already handles these cases in an expected
manner. After passing a domain name, we can
query in any case.
=> [LLT-4916] Allow any case nickname

crates/telio-nurse/src/qos.rs, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/endpoint_providers/local.rs, crates/telio-traversal/src/upgrade_sync.rs, crates/telio-utils/src/repeated_actions.rs, crates/telio-wg/src/wg.rs, src/device/mod.rs
We were, for our purposes, incorrectly handling the cases where tokio misses one or more ticks when doing work based on an interval.
We now set the missed tick behavior to delay, instead of the default burst. For more info, see:
https://docs.rs/tokio/latest/tokio/time/enum.MissedTickBehavior.html
=> LLT-4948: Set missing tick behavior for tokio intervals

crates/telio-nurse/src/qos.rs, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/endpoint_providers/local.rs, crates/telio-traversal/src/upgrade_sync.rs, crates/telio-utils/src/repeated_actions.rs, crates/telio-wg/src/wg.rs, src/device/mod.rs
We were, for our purposes, incorrectly handling the cases where tokio misses one or more ticks when doing work based on an interval. 
We now set the missed tick behavior to delay, instead of the default burst. For more info, see:
https://docs.rs/tokio/latest/tokio/time/enum.MissedTickBehavior.html
=> Backport LLT-4948 to 4.2

Cargo.lock, changelog.md, crates/telio-model/src/api_config.rs, crates/telio-nurse/Cargo.toml, crates/telio-nurse/src/aggregator.rs, crates/telio-nurse/src/lib.rs, src/libtelio.udl
We need to prepare some API for NAT-traversal and Relay connections data gathering, which supports:
- collecting events about:
- changes in the connectivity to Relay servers
- current state of the connections with the other Meshnet peers
- processing the events of both types and represent the gathered information as ready-to-serialize format, as it was described in the corresponding RFC.
In this PR I introduce an aggregator struct, which allows to store Relay (`change_relay_state` method) and NAT-traversal connection events (`change_peer_state_relayed` for relayed peers and `change_peer_state_direct` for the peers connected directly) and provides an API for `telio-nurse` module, so it can just download almost-serialized data and then effortlessly send it to the analytics server.
For the …
=> [LLT-4855] Create connectivity events aggregation data model

nat-lab/bin/kill_process_by_natlab_id, nat-lab/tests/utils/process/docker_process.py
It improves the experience of running the tests locally in two ways:
- on some setups you can't just kill the docker process from host (even with sudo)
- some tests won't need entering sudoer password anymore
While running locally tests have sometimes problems with killing docker processes
We can map the host PID to the PID inside the container and then kill it inside, which is done in this commit
=> [LLT-4420] Fix killing docker processes

src/ffi/mod.rs
`String` was converted to a slice of bytes, from which a point was created. This doesn't guarantee that a resulting pointer points to an array ending with a nul byte.
Printing that string in lldb shows that it can end with 'random' bytes:
```
(lldb) set set target.max-string-summary-length 100000000
(lldb) p ptr
"aaa(...)aaaaa\xe8$N%\U00000002"
```
Use `CString` to have a guaranteed null terminated c style string.
=> Use null terminated strings in uniffi test for path length

changelog.md, crates/telio-wg/src/wg.rs
Do not configure listen_port in wireguard adapter if it is already configured to the same value. At least in some implementations it is not a no-op and reconfiguring it causes the underlying socket to be closed and recreated
=> Do not update wg listen_port when not needed

.github/workflows/tests.yml, crates/telio-nurse/src/qos.rs, crates/telio-sockets/src/socket_pool.rs, crates/telio-traversal/src/endpoint_providers/stun.rs, test_runner.sh
Tests are not run at all on the mac, which causes accidental breakage. Additionally the test runner reruns the tests when they fail.
Add a unit tests job on a mac runner. The tests that are currently not working will have separate tickets created to investigate them and fix them.
The test runner is modified so that it only runs the tests once.
=> Unit tests on mac

nat-lab/tests/telio_features.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_events_link_state.py
Persistent keepalive periods feature was not working and left with default values in tests because there was a mistake in the format.
Previous/wrong version was like: "wireguard": {"proxy": 25, "direct": 5, etc}
The correct version is: "wireguard: {"persistent_keepalive": {"proxy":
25, "direct": 5, etc}}"
=> Fix persistent keepalive feature in nat-lab

crates/telio-traversal/src/session_keeper.rs, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_pinging.py, nat-lab/tests/utils/connection_util.py
We do not have any integration tests, that checks telio's modules that sends ICMP packets (`QoS` and `SessionKeeper`). In addition to that, while writing tests, one bug in `SessionKeeper` was was caught and fixed (primary socket was used instead of secondary on the second attempt). 
Add natlab tests for both modules.
=> LLT-4658 LLT-4659 session_keeper and QOS tests

changelog.md, src/device/mod.rs
There is a leftover stun peer after meshnet is set off, but it's already fixed in main
Backport the fix from main into release v4.2
=> Fix (backport) leftover stun peer after meshnet is set off

changelog.md, crates/telio-model/src/api_config.rs, crates/telio-nurse/src/config.rs, crates/telio-nurse/src/heartbeat.rs
initial_heartbeat_interval represents the time between the start of libtelio and the first analytics event. Until now, when it was missing from the config, it defaulted to None and the first event was generated after heartbeat_interval time which by default is 1 hour. It was requested that we use a default value of 5 minutes for initial_heartbeat_interval.
=> Make initial_heartbeat_interval to default at 5 minutes

nat-lab/tests/test_pinging.py
Leftovers from [368](https://github.com/NordSecurity/libtelio/pull/368), that fails python lints.
Remove leftovers.
=> Remove unnecessary Wireguard() from test params

changelog.md, crates/telio-model/src/constants.rs, crates/telio-model/src/lib.rs, crates/telio-nurse/src/aggregator.rs, crates/telio-nurse/src/qos.rs, crates/telio-nurse/src/rtt/ping.rs, crates/telio-utils/src/dual_target.rs, crates/telio-wg/src/uapi.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_lana.py, nat-lab/tests/test_lana_validator.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/utils/analytics/event_validator.py, nat-lab/tests/utils/connection_util.py, src/device/wg_controller.rs
QoS ping was being done over ip addresses retrieved from the subnets on `allowed_ips` field. This led to issues on missing data for exit node peers that have `0.0.0.0/0` subnet.
This PR adds an additional field to `Peer` structs so that we can track which meshnet address a specific peer was given.
VPN peers have `[100.64.0.1, 10.5.0.1]` ip addresses assigned, however when meshnet is enabled `100.64.0.1` is reachable otherwise it isn't. Therefore`100.64.0.1` is treated as the default address to ping and `10.5.0.1` as alternative when the other is not reachable. Both should be reachable at normal circumstances.
Eg.:
```
{
...
"context": {
"application": {
"arch": "x86_64",
"libtelioapp": {
"config": {
"external_links": "vpn:6c980a87b6607f5b60d0bd57470f66fe:6",
"internal_meshnet": { …
```
=> LLT-4850: Add missing VPN peer meshnet address to analytics

changelog.md, crates/telio-proxy/src/proxy.rs, nat-lab/run_local.py
We were getting the wrong endpoint map from the proxy when trying to configure the wg controller. There was recently some error handling added which made the problem visible, but the problem was there for longer. The root of the issue was that if there was a socket error, StateIngress would swallow the error while StateEgress would actually handle it, yet when we were fetching the endpoint map for the wg controller, we would get it from StateIngress. As a result, if there was a socket error, ingress and egress could be out of sync, and we would get the wrong values passed to the wg controller.
There is now synchronization logic added for ingress and egress, and the endpoint map is fetched from egress
Also, with this PR, it's possible to pass the `-x` flag to `run_local.py` and have that …
=> LLT-4980: Missing sync in telio-proxy

changelog.md, crates/telio-model/src/api_config.rs, crates/telio-nurse/src/config.rs, crates/telio-nurse/src/heartbeat.rs
BACKPORT
initial_heartbeat_interval represents the time between the start of libtelio and the first analytics event. Until now, when it was missing from the config, it defaulted to None and the first event was generated after heartbeat_interval time which by default is 1 hour. It was requested that we use a default value of 5 minutes for initial_heartbeat_interval.
=> Backport Make initial_heartbeat_interval to default at 5 minutes

changelog.md, nat-lab/tests/telio_features.py, src/device/mod.rs
A leftover STUN peer remains after meshnet is turned off causing issues
Added code to properly clear the wg stun server config when stopping meshnet
=> Fix leftover stun peer after meshnet is set off

Cargo.lock, Cargo.toml, changelog.md, crates/telio-model/src/constants.rs, crates/telio-model/src/lib.rs, crates/telio-nurse/src/qos.rs, crates/telio-nurse/src/rtt/ping.rs, crates/telio-proxy/Cargo.toml, crates/telio-proxy/src/proxy.rs, crates/telio-utils/src/dual_target.rs, crates/telio-wg/src/adapter/mod.rs, crates/telio-wg/src/uapi.rs, crates/telio-wg/src/wg.rs, src/device/mod.rs, src/device/wg_controller.rs
Prepartion for release, backports of:
* LLT-4850: Add missing VPN meshnet address to analytics
* LLT-4917: Fix the issue with wireguard-go failing to bind to a port on some devices
* LLT-4406: Implement error handling for proxy egress
* LLT-4980: Introduce synchronization for the endpoint map in telio-proxy
=> Prepare v4.2.5

crates/telio-proxy/src/proxy.rs
New telio-proxy error logging is to spamy
Switch to warn, don't treat would block as a reportable error on ingress
=> Fix spammy logs in telio-proxy

nat-lab/tests/test_mesh_exit_through_peer.py
Test was failing due to incorrect conntracker values.
Increase icmpv6 packet account.
=> Remove ping6 from conntracker ipv6_exit test

changelog.md, crates/telio-proto/protos/upgrade.proto, crates/telio-proto/src/packet/mod.rs, crates/telio-proto/src/packet/relayed/upgrade.rs, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/connectivity_check/mod.rs, crates/telio-traversal/src/upgrade_sync.rs, nat-lab/tests/telio.py, nat-lab/tests/test_direct_connection.py, src/device/mod.rs, src/device/wg_controller.rs
This will be used to decide if upgrade is accepted or rejected in LLT-4858. For now it is used to detect situations when the recipient of Upgrade message is unaware of the associated session id, most likely due to restart.
Currently there is no way to distinguish initiators in a upgrade procedures when 2 procedures start at the same time. Furthermore when the other side is restarted after it sent CMM response, it will accept any update request as valid.
Implement RFC LLT-0058 which prepares us for detecting initiator and solves the rejection of unknown update requests (e.g. after a restart).
`Upgrade` message is extended with a `session` field and a new message `UpgradeDecision` is added to be sent as a reply for the `Upgrade. The decision let's the other side reject unknown requests.
=> Add UpgradeDecision message and session field to Upgrade message

Cargo.lock, crates/telio-model/Cargo.toml, crates/telio-model/src/config.rs, crates/telio-nurse/Cargo.toml, crates/telio-nurse/src/aggregator.rs, crates/telio-nurse/src/lib.rs, crates/telio-nurse/src/nurse.rs
Current aggregator API for DERP events is a bit hard to use from Derp module
Change the aggregator API for Derp events, so it uses `Server` instead of `AnalyticsEvent`
=> Llt 4859 fix aggregation for derp

changelog.md, crates/telio-wg/src/uapi.rs
The zero-valued preshared key is reported for certain interfaces
Validate the key
=> LLT-5002: Preshared key comparison detect's non exsistant state change

Cargo.lock
This fixes https://rustsec.org/advisories/RUSTSEC-2024-0019
-
-
=> Backport "Update mio to 0.8.11" into 4.2

Cargo.lock
This fixes https://rustsec.org/advisories/RUSTSEC-2024-0019
-
-
=> Backport "Update mio to 0.8.11" into 4.3

nat-lab/tests/test_mesh_off.py
Check for leftover peers after setting mesh to off.
In case of a bug, there may be leftover peers after turning mesh off and that can cause issues and even lead to IP leaks.
Added a NAT-Lab test which checks if there are any leftover peers after turning mesh off.
Also note since this is an internal test commit, not adding any entry to the changelog as this information is not useful to app teams who are the consumers of the changelog.
=> Add NAT-Lab test for checking if there are any leftover WireGuard

changelog.md, crates/telio-wg/src/uapi.rs
Backport of https://github.com/NordSecurity/libtelio/pull/409 into 4.2
The zero-valued preshared key is reported for certain interfaces
Validate the key
=> Backport of LLT-5002 into v4.2

nat-lab/tests/test_events_link_state.py
The link_state tests sometimes fails with timeout error due to a race condition in LinuxNative Wireguard implementation (described in LLT-5014).
This commit removes the flaky configs. We have to add them back when the issue is fixed.
=> Remove link_state flaky configurations

nat-lab/bin/configure_route.sh
`configure_route.sh` fails on new Vagrant runners. My theory is that the new runners have much faster CPUs, and that causes a racey condition to happen. Container entrypoint executes faster than interfaces are initialized.
Allow a little bit of time for interfaces to be initialized before using the interfaces.
=> Synchronize racey configure_route.sh

changelog.md, crates/telio-nurse/src/qos.rs, crates/telio-wg/src/uapi.rs, src/device/wg_controller.rs
Virtual peers (DNS, Stun, etc.) are being added to QoS which is neither expected nor useful, wasting resources.
Stop adding these peers to QoS.
=> [LLT-4996] nurse: Stop adding virtual peers to qos

.github/workflows/gitlab.yml, .gitlab-ci.yml
Bumping `libtelio-build` to `v1.0.0`.
=> Bump libtelio-build to v1.0.0

changelog.md, crates/telio-model/src/lib.rs, crates/telio-model/src/mesh.rs, crates/telio-proxy/src/proxy.rs, nat-lab/tests/test_proxy.py, nat-lab/tests/utils/router/linux_router.py, nat-lab/tests/utils/router/mac_router.py, nat-lab/tests/utils/router/router.py, nat-lab/tests/utils/router/windows_router.py, src/device/mod.rs, src/device/wg_controller.rs
There was recently a commit that introduced synchronization for the endpoint maps of StateIngress and StateEgress, which fixed an issue where StateEgress would update it's endpoint map on socket error, but StateIngress would be used as the source of truth, leading to an incorrect endpoint map being used. 
This commit improves that work in a few ways. It:
- Adds a test to check that the scenario works
- Makes wg_controller know about both the old endpoint and the new endpoint
- Resends the data to make libtelio adapt to endpoint changes quicker
=> LLT-4980: Improve proxy endpoint update logic

android/templates/build.gradle
Update com.android.tools.build:gradle to v4.2.2
Update org.jfro.buildinfo:build-info-extractor-gradle:4.33.13 Due to reported vulnerabilities.
=> Update gradle dependencies for build scripts

crates/telio-wg/src/uapi.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_network_switch.py, src/device/mod.rs, src/device/wg_controller.rs
Original task was already done in the solution for LLT-4981. We need to additionaly remove timeout from network_switch_direct test which should now be obsolete. But after removing it , so we move downgrade handling to mod/device.rs, to make it more robust.
In this PR we remove the mentioned timeout, it also simplifies select_endpoint_for_peer function a bit
=> [LLT-4802]Move downgrade handling to mod/device.rs

changelog.md, crates/telio-nurse/src/aggregator.rs, crates/telio-nurse/src/heartbeat.rs, src/device/mod.rs, src/ffi/mod.rs, src/libtelio.udl
NAT and DERP data aggregator needs to be notified when the system is going to sleep, and when it wakes up in order to not take those timings into consideration.
- a small bug in the aggregator was also found and fixed.
When the system goes to sleep, simply gather all the unacknowledged segments and clear the rest.
At wakeup, do an additional clearing of current segments to handle the race condition where a new segment might begin after clearing the segments when system goes to sleep. The beginning of new segment would be handled by wg notifications.
=> LLT_4954 handle sleeping state

Cargo.lock, Cargo.toml
`cargo-deny` job started to fail due to RUSTSEC-2024-0332 found in the `h2` crate.
Upgrade crate: `h2 v0.3.24` -> `h2 v0.3.26`
=> build: Update h2 dependency to patch RUSTSEC-2024-0332

.github/workflows/gitlab.yml, .gitlab-ci.yml, nat-lab/bin/configure_route.sh, nat-lab/docker-compose.yml
Bug no. 1: Bug in docker compose: https://github.com/docker/compose/issues/11510
This bug randomly causes missing network interfaces in started containers. We just updated docker compose version to the version which is not affected.
Bug no. 2: Bug in docker daemon: https://github.com/moby/moby/issues/47619
Because of this bug eth0 is not created before sysctls are being set so it is not possible to set any sysctls related to the specific interfaces.
We can create a workaround by not setting eth0. Instead we can set default so eth0 will have this value assigned later when created.
=> LLT-5040 Fix nat-lab issues around dockers

.cargo/config, Cargo.toml, ci/build_libtelio.py
This PR is part of the set of tasks to reduce the application binary sizes. For that, dynamic libraries are necessary to achieve isolation and the ability to use size optimization features that otherwise would be locked, due to possible c symbol collisions.
It replaces static for dynamic libs (*.so, *.dylib) on linux and apple builds. Android, Windows builds are already compiling dynamic libraries.
It also removes bitcode from apple binaries and add linker flag `-s` for apple builds as this flag is now removed from `rust_build_utils` repo in order to allow future customizations.
=> build: Set libtelio as cdylib crate type

crates/telio-relay/src/derp/mod.rs, nat-lab/tests/telio.py
Wait for derp connection join handle to finish when aborting. Not waiting sometimes prevents some other tasks from stopping. It is because of strong pointer being still held.
Derp holds strong pointer to aggregator, which hold strong pointer to wireguard. When stopping Derp, strong pointer of aggregator not released on time, therefore wireguard pointer from aggregator is not released also, preventing wireguard task from stopping.
Wait for derp connection join handle to finish when aborting.
=> Fix derp disconnect

changelog.md, src/doc/integrating_telio.md, src/doc/introduction.md, src/doc/telio_events.md, src/lib.rs
A need arose to have an in-repo documentation system for Libtelio
Added mdbook documentation system skeleton to libtelio repo so that it can be populated by further PR's, but after discussions in this PR we've decided that it'd be simpler to use doc rs according to how [the Clap crate](https://docs.rs/clap/latest/clap/index.html) used it to document their tutorials instead.
The current documentation can be viewed by using `cargo doc --open` in the libtelio level of the repo. Proper generation by CI will be added with later PRs
=> Add in-repo documentation system skeleton

Cargo.toml, changelog.md
After switching to dynamic linked libraries, we're able to reduce the size of the binaries even further by enabling optimization flags on the compiler.
For convenience, builds were made locally on a linux x86_64 machine, comparing with CI there's an error tolerance of +/- 1%.
Also, by default debug symbols are split into a separate file (329 MB) and stripped from the final binary (ie. `strip = "debug"`).
| linux-x86_64 optimizations | size (MB) | reduction gain (%) | Description                                                                                                      |
| -------------------------- | --------- | ------------------ | ---------------------------------------------------------------------------------------------------------------- |
| opt-level = 3 (default)    | …
=> build: Enable size reduction compiler flags

changelog.md, crates/telio-proxy/src/proxy.rs
`tokio::select!` can panic, if branches are disabled. This was observed when killing `proxy` task. 
Update all (exception - tests) `tokio::select!` invokations with `else`, to avoid panics.
=> LLT-5078 proxy panics when being killed

Cargo.lock, Cargo.toml, changelog.md, crates/telio-proxy/src/proxy.rs
`tokio::select!` can panic, if branches are disabled. This was observed when killing `proxy` task. 
Update all (exception - tests) `tokio::select!` invokations with `else`, to avoid panics.
=> LLT-5078 proxy panics when being killed backport release/4.2

changelog.md, crates/telio-proxy/src/proxy.rs
`tokio::select!` can panic, if branches are disabled. This was observed when killing `proxy` task. 
Update all (exception - tests) `tokio::select!` invokations with `else`, to avoid panics.
=> LLT-5078 proxy panics when being killed forwardport

changelog.md, crates/telio-wg/src/uapi.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_proxy.py, src/device/wg_controller.rs
Changing time by few minutes, caused telio to report disconnect (even if the underlying wireguard connection was fine).
Instead of using a system time based 'last handshake time', track the time (using monotonic clock) of the last received bytes. This way changes to the system time (by the user or ntp like service) will not affect our perception of how long ago did we last seen a packet from the other side.
=> Make connection state reporting unaffected by system time changes

changelog.md, crates/telio-dns/src/forward.rs, nat-lab/bin/dns-server, nat-lab/tests/test_dns.py
In debug mode, trust-dns asserts that `NoError` error type is never converted. But in practice seems that we sometimes receive such cases.
Convert such errors to `ServFail` to avoid panic.
=> Convert dns failures with NoError to ServFail

.cargo/config_apple_tvos, Cargo.lock, changelog.md, crates/telio-sockets/Cargo.toml, crates/telio-traversal/Cargo.toml, crates/telio-traversal/src/endpoint_providers/local.rs
We are using forked versions of some crates that already contain tvOS support in latest upstream versions.
Where possible removed the in house forks of the crates with added tvOS support and replaced with latest upstream versions that already contain tvOS support. Crates replaced with upstream versions:
- cc
- if-addrs
- socket2
- ring
- parking_lot_core
- nix
After this, there are still 2 crates not updated upstream:
- block
- objc
=> Replace custom tvOS versions of crates, with updated upstream ones

.github/workflows/gh-pages.yml, Cargo.lock, Cargo.toml, README.md, src/doc/integrating_telio.md
Rust doc will be build and uploaded to libtelio GitHub Pages website by GitHub Actions when manually triggered.
There's no convenient way to transfer libtelio documentation to app teams.
Rust Doc are now built and the resulting artifact is uploaded to GitHub pages for the app teams to easily access.
Currently the gh-pages generation is triggered manually from CI, because it is not clear on how to best trigger it, because versioning isn't implemented for the documentation and build promotion is still in progress
>NOTE: The gh-pages workflow cannot be triggered manually before it is merged into the default branch. I've tested the gh-pages generation by adding a temporary CI workflow trigger from pushing to this branch, but have removed it for the final merge.
The documentation is already …
=> Add rustdoc deployment to gh-pages

crates/telio-utils/src/lru_cache.rs
Hi, :wave:,  just simplification of `LruCache::peek` logic
1. Use `?` to get `key` value or return `None`
2. Invert `if` condition to transform it into a guard statement
=> Simplify peek method

Cargo.lock
=> Update rustls to 0.21.11 to fix CVE-2024-32650 / RUSTSEC-2024-0336

Cargo.lock, changelog.md, nat-lab/tests/test_mesh_off.py, src/device/mod.rs, src/device/wg_controller.rs
When meshnet is being turned off, save all the needed state so that it's possible to compute the correct (as it was just before turning off) path type of each peer.
When reporting events for peers after turning off the meshnet, we always reported path type 'relayed', regardless of what was the actual path type just before turning off the meshnet.
When meshnet is being turned off, save all the needed state so that it's possible to compute the correct (as it was just before turning off) path type of each peer.
=> When meshnet is off, use the last known state to determine path type

Cargo.lock, Cargo.toml
uapi set/get didn't throw an error when device was closed
Throw uapi error when adapter is dead and exit
event is generated. Mirror fix, as for wireguard-go at https://github.com/NordSecurity/libtelio/pull/496
=> Resolve LLT-5096: Bump boringtun version

clis/tcli/src/main.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/telio.py, nat-lab/tests/test_adapter_gone.py, src/device/mod.rs
Whenever interface was gone, we just increased fail counter, but didn't do anything.
Send critical event to registered event callback, so library users can act on it.
Boringtun bump commit will be gone, once this https://github.com/NordSecurity/boringtun/pull/17 and this https://github.com/NordSecurity/libtelio/pull/499 PRs will be merged to main.
=> Resolve LLT-5095: send critical event to app when adapter dead

.github/workflows/build.yml, .github/workflows/scorecard.yml, .github/workflows/tests.yml
Reverts NordSecurity/libtelio#503
After bump, github job became flaky
=> Revert "Bump actions/upload-artifact from 3.1.2 to 4.3.2"

clis/tcli/src/cli.rs, crates/telio-nurse/src/heartbeat.rs, crates/telio-nurse/src/nurse.rs, crates/telio-nurse/src/qos.rs, nat-lab/tests/telio.py, nat-lab/tests/test_lana.py, src/device/mod.rs
The `QoS` collection is not aligned by events to collecting heartbeat events and/or stopping the nodes, but by `rtt_interval`. Therefore it is very prone to race conditions during the tests.
Make a manual `QoS` job trigger in `tcli` and use it in `test_lana_with_disconnected_node` test.
=> Add manual QoS trigger in tcli

.github/workflows/changelog.yml, .github/workflows/dod.yml
Dependabot PRs fail changelog entry file check, because it does not create changelog files at all and we require at least empty changelog files to be present in a PR. 
Exclude Dependabot from this check entirely
=> Exclude Dependabot from changelog entry file check

.github/workflows/gitlab.yml, .gitlab-ci.yml, .unreleased/LLT-5005, nat-lab/tests/config.py, nat-lab/tests/test_adapter_gone.py, nat-lab/tests/test_client_basic_stun.py, nat-lab/tests/test_connection_states.py, nat-lab/tests/test_derp_client_message_forward.py, nat-lab/tests/test_events.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_mesh_remove_node.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_node_state_flickering.py, nat-lab/tests/test_pq.py, nat-lab/tests/test_process.py, nat-lab/tests/test_reconnections.py, nat-lab/tests/test_upnp_connection.py, nat-lab/tests/test_vpn.py, nat-lab/tests/test_wg_adapter.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/vm/mac_vm_util.py, nat-lab/tests/utils/vm/windows_vm_util.py
Missing state flickering test for direct connection.
- Update libtelio-build ref (add second windows vm)
- Add state flickering test for direct connection
=> Resolve LLT-5005: add direct connection test for same adapter types

.github/workflows/changelog.yml
Changelog CI check is not working, it should fail if no file had been created in the .unreleased directory
Fix
=> Move changelog check into dod

crates/telio-utils/src/exponential_backoff.rs
Hi :wave:, nothing big - `ExponentialBackoff::new` can be simplified + `Errors` doc section
1. Use `is_some_and` instead of `map(..).unwrap_or(false)`
2. Add `Errors` section to method docs
=> Simplify exponential backoff constructor

.github/workflows/nagger.yml, .unreleased/LLT-5036, Cargo.lock, clis/interderpcli/Cargo.toml, crates/telio-dns/Cargo.toml, crates/telio-lana/Cargo.toml, crates/telio-nurse/Cargo.toml, crates/telio-pq/Cargo.toml, crates/telio-relay/Cargo.toml, crates/telio-traversal/Cargo.toml, crates/telio-wg/Cargo.toml
Telio has features enabled, that are not used and just adds to the size of the final artifact.
- Run `cargo-unused-features` and remove those unused features. 
- Update `Cargo.lock`.
- Update nagger version to a newer toolchain.
- Update toolchain for tvOS builds (`rust_build_utils` tag bump)
=> [LLT-5036] Remove unused dependency features

.cargo/config, .github/workflows/gh-pages.yml, .unreleased/LLT-5102, rustdoc/footer.html, rustdoc/header.html, rustdoc/multi-code.html, src/doc/integrating_telio.md, src/lib.rs
We want to have more documentation live in the repo so it's open to anyone who wants to integrate telio. For this PR in particular, we just want to port some existing integration docs to instead use rustdoc.
The existing page was copied, and code examples updated from C to the different languages that are relevant to us.
Note: At this point it's okay if the code examples are not 100% correct. There will be a sync with the different app teams on what the API will actually look like and at the same time they will have input on the code examples, so mostly correct is good enough for now.
[Page in gh-pages](https://nordsecurity.github.io/libtelio/telio/_telio_integration_documentation/index.html)
=> LLT-5102 Add integration docs

.unreleased/LLT-5119, nat-lab/tests/helpers.py, nat-lab/tests/mesh_api.py, nat-lab/tests/telio.py, nat-lab/tests/utils/testing.py
When debugging issues related to VPN it's sometimes usefull to see the traffic from the point of view of the vpn server.
Collect tcpdump traces from all vpn servers and store them in a similar way as the log files.
=> Tcpdump traces collection from the vpn servers in nat-lab added

nat-lab/tests/utils/network_switcher/network_switcher_windows.py
I have a suspicion that we still have some race conditions with DHCP on management interface for windows VMs, which causes non-deterministic test failures. I would like to observe how much and what tests are affected to be able to better decide on next actions, but for that, DHCP on management interface needs to not be reenabled. This PR makes that happen.
**Note:**
When management interface is disabled on windows VM:
```bash
vagrant ssh windows-1
```
will not work anymore, and one will have to use primary or secondary interface to access the VM, for example:
```bash
ssh vagrant@10.55.0.13
```
will be equivalent to the above command.
=> Do not reenable management interface

.github/workflows/gitlab.yml, .unreleased/LLT-3474, .unreleased/LLT-5008, android/templates/build.gradle, android/templates/init.gradle, ci/build_libtelio.py
Currently windows, linux and android artifact do not ship interface bindings.
Updated build script's to package them.
=> Add bindings to build artifacts.

Cargo.lock, changelog.md, crates/telio-sockets/Cargo.toml, crates/telio-sockets/src/protector/apple.rs, src/device/mod.rs
Using only interfaces with the router property is incorrect since when using static IPs it's possible to have an interface without router property. Additionally, interfaces returned by the dynamic store are not in any particular order. After this, change, we use the interfaces collected from the NWPathMonitor. Those are ordered in the same way as the OS would prefer them.
I will try to add some sort of tests when merging to main.
=> Use NWPathMonitor to get interfaces in order of preference for socket protector on apple platforms

.unreleased/LLT-5145, src/ffi/mod.rs
This function was accidentally removed without a replacement previously, but it's necessary to make libtelio work on android.
Re-add the method, but updated to conform to uniffi and how the FFI code looks now.
Additionally, `TelioError::UnknownError` now has a `String` instead of `anyhow::Error`. This change is not strictly necessary for this PR, but it does make things easier, and the change would have been made anyways when migrating natlab to uniffi, so it was done here.
=> LLT-5145 Restore missing init_cert_store method

.unreleased/fix-wg-adapter-gone-test, nat-lab/tests/test_wg_adapter.py
If tcli still exists, it is not possible to create or delete adapter with same GUID, since tcli is still holding a reference to it.
Wait for tcli to be gone and then proceed with test
=> Fix wg adapter gone test

.unreleased/LLT-5119, nat-lab/tests/helpers.py, nat-lab/tests/mesh_api.py, nat-lab/tests/telio.py, nat-lab/tests/utils/connection/docker_connection.py
Tcpdumps are collected only on vpn server docker containers. We would like to also collect them on the containers that run libtelio/tcli.
Start tcpdump on docker containers where we have libtelio/tcli clients running.
=> Add pcap collection for docker based telio peer nodes

.unreleased/LLT-5139, crates/telio-nurse/src/heartbeat.rs, crates/telio-nurse/src/qos.rs, crates/telio-relay/src/derp/http.rs, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/endpoint_providers/local.rs, crates/telio-traversal/src/upgrade_sync.rs, crates/telio-utils/src/interval.rs, crates/telio-utils/src/lib.rs, crates/telio-utils/src/repeated_actions.rs, src/device/mod.rs
`RepeatedActions::add_action` used intervals with default missed tick behaviour. This caused many 'activations' after a long sleep, one for each missed tick. This is not desired - we want to ignore all the missed ticks.
`add_action` is modified to use a missed tick behaviour that will skip all the missed ticks. Additionally, to make it a little bit less likely that this kind of a mistake will be once again made all the places where the intervals are created had been converted to use our internal wrapper that returns `Interval` with already correct missed tick behaviour.
=> Change the interval missed tick behaviour to Delay in RepeatedActions::add_action

.unreleased/rename-ffi-deserialize-functions, src/doc/integrating_telio.md, src/ffi/mod.rs, src/libtelio.udl
`string_to_features` and `string_to_meshnet_config` could be named better
Rename to `deserialize_feature_config` and `deserialize_meshnet_config`
=> Rename string_to_* FFI functions

Cargo.lock, changelog.md, crates/telio-sockets/Cargo.toml, crates/telio-sockets/src/protector/apple.rs
When NWPathMonitor call a callback with a new path, not only store it for future use but also notify all NativeProtector instances that the new path had been identified. This will now trigger rebind of protected sockets, if the new interface has changed.
=> Rebind sockets when network path changes on Apple

.unreleased/LLT-5082, Cargo.lock, Cargo.toml, clis/tcli/src/cli.rs, crates/telio-dns/src/dns.rs, crates/telio-dns/src/nameserver.rs, crates/telio-dns/tests/integration_tests.rs, crates/telio-dns/tests/nameserver.rs, crates/telio-lana/src/event_log_file.rs, crates/telio-pq/src/proto.rs, crates/telio-proto/src/packet/relayed/natter.rs, crates/telio-relay/src/derp/mod.rs, crates/telio-traversal/src/endpoint_providers/mod.rs, src/lib.rs
We use boringtun v0.5.2 when v0.6.0 is available
Rebase Telio changes to boringtun on v0.6.0 version, use it in libtelio and add some fixes where necessary.
=> [LLT-5082] Use boringtun v0.6.0

.github/workflows/linters.yml, .unreleased/LLT-5089, Cargo.lock, crates/telio-crypto/Cargo.toml, crates/telio-pq/Cargo.toml
It’s possible that telio has unused features enabled, adding size to the final artifact.
Add a CI job to check for unused-features for every PR.
=> [LLT-5089] Add job to check for unused-features

.github/workflows/dod.yml
DoD must be un-checked and checked once again on every other push to PR.
Restart DoD job on every push.
=> Launch dod automatically after every push

README.md
1. Add to README.md check to verify if gcc (required for libtelio build) was installed. 
2. Add ca-certificates package (in order to connect to Derb server) installation for Docker container in README.md
1. During build of libetlio on linux VM there was following error:
` error: linking with: /home/{username}/libtelio/linkers/d-x86_64-linux-gnu-gcc failed: exit status: 127`
2. Peer in docker container was not able to connect to DERB:
`2024-05-17T08:55:07.250137Z  WARN telio_relay::derp: 284: (DerpRelay) Failed to connect: I/O Error: invalid peer certificate: UnknownIssuer`
1. For linux VM add check to verify if gcc (GNU Compiler Collection) is installed
2. Add `ca-certificates` to Dockerfile
=> Update README.md: Add gcc check and ca-certificates installation (in Dockerfile)

nat-lab/pyproject.toml, nat-lab/tests/conftest.py
When `pytest-timeout` cancels test due to timeout, we lose exception traceback, because `pytest-timeout` does `os._exit(1)`
Print asyncio running task stack before cancelling them
=> print pytest asyncio task stack

crates/telio-utils/src/repeated_actions.rs
Reverts NordSecurity/libtelio#566 As it broke some clippy checks
=> Fix clippy warning which got accidentally pushed to main

.unreleased/LLT-5208, Cargo.lock, Cargo.toml
The old version of boringtun ignores the preshared key changes
Update boringtun
=> Bump boringtun

.github/workflows/tests.yml, .unreleased/LLT-5075, crates/telio-wg/src/adapter/mod.rs
Cargo doc was not working previously on a macos host.
Don't use linux only code on macos. Also automated job is added to not break it in future by accident.
=> Fix cargo doc on mac and add a test for it

.unreleased/LLT-5247, clis/tcli/Cargo.toml
When building `tcli` package, cargo will build 2 executables - `tcli` and `tclid`. This has 2 downsides when building for nat-lab. First, it slows down the whole build process. Secnod, on a macOS host where building happens in a docker with a limited memory, concurrent linking processes consume whole memory and one of them is being killed by oom-killer.
Make the `tclid` binary optional. To build it the required command will be:
```
cargo build --package tcli --features tclid
```
=> Don't compile tclid by default when building tcli package

.unreleased/LLT-4641, crates/telio-nurse/src/heartbeat.rs, crates/telio-sockets/src/protector/apple.rs, crates/telio-sockets/src/protector/linux.rs, crates/telio-sockets/src/protector/mod.rs, crates/telio-sockets/src/protector/unsupported.rs, crates/telio-sockets/src/protector/windows.rs, crates/telio-sockets/src/socket_pool.rs, crates/telio-wg/src/wg.rs, src/device/mod.rs, src/ffi/mod.rs
Failed `SessionKeeper` startup is "fatal" - whole meshnet startup fails. Yet it only prevents the direct part of the meshnet from working.
When the SessionKeeper fails to start (for whatever reason), make it as if the config didn't have the 'direct' section and continue the startup. This will result in meshnet still working, but only in the relayed mode.
=> Make failed SessionKeeper startup non-fatal for the meshnet

.unreleased/LLT-5279, src/doc/integrating_telio.md, src/ffi/mod.rs, src/libtelio.udl
`go` bindings in `uniffi` generates `Destroy` methods, that has a name clash with `telio_destroy*` methods.
Rename `telio_destroy*` methods to `shutdown` to avoid clashes between `go` generated bindings.
=> LLT-5279 Rename destroy methods for them not to collide with go Destroy methods

android/templates/build.gradle
It's transient dependecy xstream, used in older
version had a known vulnerability.
Bump version to one used by android team
=> VCP-2244: Bump build-info-extractor-gradle to 5.1.14

android/templates/build.gradle
Reverts NordSecurity/libtelio#606
Breaks package-aar
=> Revert "VCP-2244: Bump build-info-extractor-gradle to 5.1.14"

nat-lab/tests/utils/command_grepper.py, nat-lab/tests/utils/network_switcher/network_switcher_windows.py, nat-lab/tests/utils/router/windows_router.py
Some commands in VM do not generate results instantly. This was observed primarily on Windows, when setting IP addresses on interface using `netsh` command.
After command execution, launch a "check-and-grep-like" commands for some predetermined amount of time, to search for a command execution result.
=> LLT-5246 Add netsh checks on config changes in win VM

.unreleased/LLT-5294, src/ffi/mod.rs, src/libtelio.udl
Apps teams want a function to get default config
Add the function
=> LLT-5294: Add FFI function to get default feature config

.unreleased/LLT-5278, crates/telio-model/src/features.rs, nat-lab/tests/telio_features.py, nat-lab/tests/test_telio_features.py, nat-lab/tests/test_vpn.py, src/device/mod.rs, src/device/wg_controller.rs, src/lib.rs, src/libtelio.udl
This PR creates a new feature for firewall. This answers the PR review comment https://github.com/NordSecurity/libtelio/pull/529/files#r1626552500
Above mentioned PR is already too large, so creating a separate PR to have `boringtun_reset_connection` as part of `FeatureFirewall` config.
=> Add firewall feature config

android/templates/build.gradle
It's transient dependecy xstream, used in older version had a known vulnerability.
Bump build-info-extractor-gradle version to 5.1.14
=> LLT-5286: Update build-info-extractor-gradle to 5.1.14

nat-lab/bin/update_wg_peer_key, nat-lab/tests/telio.py, nat-lab/tests/test_vpn.py, nat-lab/tests/uniffi/libtelio_proxy.py, nat-lab/tests/uniffi/libtelio_remote.py
Before rebase on Boringtun v0.6.0 calling `set_secret_key` while using Boringtun adapter caused panic. We need to make sure that setting private key will work in the future.
Add a test for `set_secret_key` Telio method
=> [LLT-4979] Add test for set_secret_key

nat-lab/tests/utils/vm/windows_vm_util.py
For some reason sometimes tests times out when copying files to windows VM. What is more, it seems like this happens for the whole test-suite instead of just a few tests. In order to figure out root cause easier -> add some additional logs during copying of files in testing VMs.
=> Add additional logs to testing framework when copying files into VMs

.unreleased/LLT-5196, nat-lab/bin/mac/list_interfaces_with_router_property.py, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/vm/mac_vm_util.py
No test was added to #548
Turns out that we already have very recently set all non management interfaces to be static and unknowingly removed the 'Router' property. To keep it that way, I've added a check to make sure that only the vagrant management interface can have the 'Router' property.
=> Verify that all non management interfaces in nat-lab have no 'Router' property

nat-lab/bin/kill_process_by_natlab_id, nat-lab/tests/mesh_api.py
Literal `{server_config['port']}` was being passed to some of the `nlx` configuration commands when starting up servers testing VPN servers. This PR fixes formatting of such commands.
=> Use format string when it is expected to do variable expansion

.unreleased/LLT-5292, nat-lab/tests/uniffi/libtelio_remote.py, src/lib.rs, src/libtelio.udl
All official apps use strings to represent keys internally. Using byte arrays for keys in the ffi layer meant that they had to do the conversion on their side before interacting with libtelio. By using string as the underlying type in UniFFI, the conversion happens transparently
Use string as the underlying type for keys in UniFFI
=> LLT-5292: Make string the underlying UniFFI type of keys

nat-lab/tests/telio.py, nat-lab/tests/uniffi/libtelio_remote.py
A recent set of commits again broke natlab. One commit was changing the underlying type for keys to strings, while another commit added more functions for dealing with keys. There was no code overlap so there were no conflicts, yet the change of underlying type for keys is made the added key handling break, causing type check errors and broke a test
Make the new key-handling code use strings directly instead of trying to convert to and from bytes
=> Fix wrong key type error

nat-lab/tests/uniffi/libtelio_remote.py
During nightly tests, we're sometimes getting the `FATAL: exception not rethrown` error, when executing `libtelio_remote.py` file.
Try to catch and print, what does this not-rethrown exception has in it.
=> Wrap libtelio_remote runtime into try-except block

wireguard-go-rust-wrapper/wireguard-go/go.mod, wireguard-go-rust-wrapper/wireguard-go/go.sum, wireguard-go-rust-wrapper/wireguard-go/interfacewatcher_windows.go
It is hard to understand why wireguard-go sometimes fails to start the adapter. For example in the job 13830453. NordSecurity/Wireguard-go fork has been updated to add more verbose logging. This PR updates libtelio reference.
=> [LLT-5312] Update wireguard-go reference in libtelio

crates/telio-crypto/src/encryption.rs, crates/telio-relay/src/derp/proto.rs, crates/telio-utils/src/lib.rs, crates/telio-utils/src/test.rs
We don't have any test for the XSalsa20Poly1305 usage in telio-relay, so if the underlying implementation will change, our unit tests won't fail
Create some test for the Salsa use in the telio-relay, similar to the one used for ChaCha in telio-crypto
=> LLT-5319: Create salsa test

nat-lab/tests/helpers.py
Conntrack limits may be enforced for tests which has failed, which, in-fact is likely to go out of limits. This PR attempts to enforce the conntrack limits only for succesfull tests.
=> Enforce conntrack limits only to succesfull tests

.unreleased/LLT-5077, crates/telio-model/src/config.rs, crates/telio-model/src/event.rs, crates/telio-model/src/mesh.rs, src/device/mod.rs, src/libtelio.udl
When multicast starts being used we want to give users the ability to granularly enable or disable multicast for different peers
Add flags to enable/disable sending and receiving multicast packets for a specific peer
=> LLT-5077: Add multicast flags to meshnet config

.unreleased/LLT-4641, crates/telio-traversal/src/session_keeper.rs
It's not 100% clear why surge ping fails to create a socket on windows for pinging.
Surge returns an `io::Result` so not much we can do about it but maybe this only happens for one kind of IP (4/6) and this change will show this.
=> Improve error handling for case when PingerClient creation fails

.unreleased/LLT-5359, crates/telio-dns/src/forward.rs, crates/telio-dns/src/nameserver.rs
Sometimes we are getting quite a few:
```
2024-06-16 09:45:49.249 INFO  VPN - "telio_dns::nameserver":160 [DNS] Lookup failed Error performing lookup: Unknown response code [DefaultDispatcher-worker-12]
```
errors, during DNS resolution. But we are not sure yet exactly the root cause for it. Thus this PR continues the Root cause hunt by adding more detailed DNS error  describtion when it occurs.
=> [LLT-5359] Log DNS request packet in case of DNS failure

Cargo.lock, crates/telio-starcast/Cargo.toml, crates/telio-starcast/src/lib.rs, crates/telio-starcast/src/nat.rs, crates/telio-starcast/src/transport.rs, crates/telio-starcast/src/utils.rs
This is the transport component for telio starcast. It has two reponsibilities: forward packet from starcast transport socket to virtual starcast peer, and forward packet from virtual starcast peer to one of more peers over the starcast transport socket. Local multicast packets go to all peers, mapped unicast packets (responses to multicast from other peer) go to a single peer. 
Note: There are currently two commits, one for implementation and one for testing. These will be squashed before merging, but might be easier to review separately
=> LLT-5125: Starcast transport component

.unreleased/LLT-5211, Cargo.lock, Cargo.toml, crates/telio-sockets/Cargo.toml, crates/telio-sockets/src/socket_params.rs, crates/telio-wg/Cargo.toml, crates/telio-wg/src/adapter/windows_native_wg.rs, crates/telio-wg/src/adapter/wireguard_go.rs, crates/telio-wg/src/windows/mod.rs, crates/telio-wg/src/windows/service.rs, nat-lab/tests/test_adapter.py
In Windows, we're sometimes seeing the errors: `Telio::start_named: Err(Adapter(WireguardGo(FailedToStart(-1))))` (the same with WireguardNT adapter). Primary suspect is the `*.dll` loader mechanism, which returns, but still haven't fully initialized the library (error happens only on first library load).
Add windows service checker for `Wintun` and `WireGuard` services.
=> LLT-5211 Wait for drivers loaded in Windows

Cargo.lock, crates/telio-starcast/Cargo.toml, crates/telio-starcast/src/lib.rs, crates/telio-starcast/src/starcast_peer.rs, src/device/mod.rs, src/device/wg_controller.rs
We need a virtual peer that would handle multicast according to the telio starcast spec 
Add multicast virtual peer for telio starcast implementation
Note that for now unit tests are missing and because this is just part of the whole solution, there wasn't any way to properly test the multicast peer. One solution would be to create two of these multicast peers and get them to communicate over the same socket.
Since this is just part of the whole multicast solution it is not properly integrated into libtelio which is causing unit test failures.
This branch also started off from the multicast PoC, so there is some leftover code present in the wg_controller and device/mod.rs files, because that's where the integration was happening which isn't clear yet.
=> Llt 5124 multicast as virtual peer

nat-lab/docker-compose.yml
The port mapping is necessary for natlab to be run with macos or windows as a host, but is not necessary on linux and sometimes breaks our CI pipeline due to the port being busy on the host.
Natlab already discovers the port mapping fully from the docker information so we  don't need to have the same port on both container and host. So a better option is to just bind a port in the container and let docker choose an available port on the host. We can also use non-ephemeral ports to make chance of collision in the container even less likely
=> LLT-5349: Make docker port mapping less flaky

ci/build_libtelio.py, ci/fetch_artifacts.py
`fetch_artifacts.py` script is broken and needs to be fixed to proceed with release. The error I was seing is:
```
Trying to download build artifacts ...
Error while downloading artifacts from "nightly" pipeline: 'ArtifactsDownloader' object has no attribute 'pipeline_id'
```
=> Fix fetch_artifacts.py script

crates/telio-wg/src/adapter/windows_native_wg.rs
When starting wg-nt adapter, there can still be failures, but we do not have any error description from OS (only bool on return).
Add `GetLastError` method to those calls, to retrieve the error code and message.
=> Additional error logging on wg nt failure

src/device.rs, src/ffi.rs
Change shutdown_art and consequently Telio.shutdown implementation to blocking. The old implementation was using shutdown_background method which just left worker threads running without joining them. That could result in a crash e.g. in a scenario when the telio user called shutdown and then unloaded libtelio library. The new implemntation uses Runtime's Drop implementation which is blocking and joins all threads.
There are still issues I see when it comes to Telio's shutdown API but I think it can be done in the future PR:
1. In the current state both `shutdown` and `shutdown_hard` close runtime but only `shutdown_hard's` documentation mentions it.
2. `shutdown` closes runtime and after that there is no possibility to call anything else on it (Previous name destroy was better I guess). …
=> Fix telio shutdown

.unreleased/LLT-5310, crates/telio-model/src/features.rs, crates/telio-nurse/src/aggregator.rs, crates/telio-nurse/src/config.rs, nat-lab/tests/telio_features.py, nat-lab/tests/test_telio_features.py, src/libtelio.udl
Analytics may be skewed by sessions being forcibly reported after 24h, which is the default time limit, and POs want to make the time limit configurable
Add `state_duration_cap` to nurse config and use it in nurse
=> LLT-5310: Make nurse state duration cap configurable

crates/telio-nurse/src/nurse.rs, nat-lab/tests/test_lana.py
Meshnet ID isn't properly fetched from Moose context and thus Telio changes it on rerun. There is a test which is supposed to test it but it doesn't work.
Fix the Meshnet ID fetching and the corresponding test.
=> [LLT-5180] Fix lana Meshnet ID fetching

nat-lab/tests/telio.py, nat-lab/tests/uniffi/libtelio_remote.py
Libtelio instance is not shutdown upon test cleanup. This PR updates the `libtelio_remote.py` shutdown method to include libtelio shutdown. 
Additionally it adds a little bit of logging upon test cleanup to show in more detail what is happening at that time.
=> [LLT-5394] Shutdown libtelio upon tests shutdown

.github/workflows/gitlab.yml, nat-lab/docker-compose.yml, nat-lab/tests/telio.py
Sometimes the tests crash with a segmentation fault, but we do not have core-dumps to analyze the root cause.
Enable, collect and attach core dumps to the CI runner artifacts.
=> [LLT-5393] Collect coredumps

.unreleased/LLT-5319, Cargo.lock, Cargo.toml, crates/telio-crypto/Cargo.toml, crates/telio-crypto/fuzz/fuzz_targets/decrypt_request_inner.rs, crates/telio-crypto/src/chachabox.rs, crates/telio-crypto/src/encryption.rs, crates/telio-crypto/src/lib.rs, crates/telio-firewall/src/firewall.rs, crates/telio-relay/src/derp.rs, crates/telio-relay/src/derp/proto.rs
There is a vulnerability in the `curve25519-dalek` crate in the currently used version - unfortunately we cannot update it simply, because it requires changing the version of the `crypto_box` crate, which changed the `ChaChaBox` implementation and thus it would make our client incompatible with the older versions.
This commit bumps the `crypto_box` and `curve25519-dalek` crates while replacing the `crypto_box::ChaChaBox` with our wrapper around `chacha20poly1305::XChaCha20Poly1305` crypto box.
=> Llt 5319 move to our chachabox wrapper

nat-lab/tests/telio.py, nat-lab/tests/uniffi/libtelio_remote.py
We occasionally have problems in CI that the socket we ask Pyro5 to bind is busy, causing the pipeline to fail even though nothing is wrong with the code. This problem has only happened with docker containers in CI so far, so it's only fixed for that scenario (not just for CI, but any system running linux as the host OS) but can be expanded to other platforms if needed
Pyro5 can automatically select an available port and we can find out about the port afterwards
=> LLT-5358: Let Pyro5 select port automatically

nat-lab/docker-compose.yml
CI started running into issues around the time the port mapping improvement was merged. It's unlikely that the port mapping change was the cause, but it's possible.
Revert port mapping improvement and see if it solves the issue
=> Revert port mapping improvement

.unreleased/LLT-4935, crates/telio-traversal/src/endpoint_providers.rs, crates/telio-traversal/src/endpoint_providers/stun.rs, crates/telio-traversal/src/endpoint_providers/upnp.rs, nat-lab/tests/test_lana.py, src/device/wg_controller.rs
We have an endpoint provider enabled by default, but still managing the `wg-stun` state, on every wg consolidation call, even though, it should be ~left untouched~ removed, when stun provider is paused.
Do not _touch_ the `wg-stun` peer, when not using the stun endpoint provider.
=> LLT-4935 Do not rotate wg-stun peer when ep paused

.unreleased/LLT-5222, crates/telio-model/src/features.rs, crates/telio-traversal/src/endpoint_providers/stun.rs, crates/telio-traversal/src/endpoint_providers/upnp.rs, crates/telio-wg/src/link_detection.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/telio_features.py, nat-lab/tests/test_downgrade.py, nat-lab/tests/test_telio_features.py, src/device/wg_controller.rs, src/libtelio.udl
The old downgrade logic was triggered if we did not receive anything for three direct keepalive period.
For battery improvement purpouses we want to increase these keepalive periods from 5 seconds to somewhere around 120 +- 5 seconds, therefore the old mechanism for downgrade won't work anymore.
The new solution uses the link detection's reports to trigger the downgrades. If the link_state of a peer changes to Down and the peer has a direct connection, we will trigger the downgrade.
=> Add downgrade logic using link detection

Cargo.lock, Cargo.toml
Need a new boringtun that logs details about ioctl failures
bumped to v1.2.2
did quick test, now if ioctl fails we will see something like:
```
ERROR boringtun::device::tun: 105: Failed to configure tunnel error=IOCtl(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }) op="TUNSETIFF" name="pna_beta" flags="1101"
```
=> Bump to boringtun with more logs

.unreleased/LLT-5351, Cargo.lock, Cargo.toml
During testing it was detected that libtelio 5.0.x versions had ~50 times slower network speed than 4.x.y versions. The main change was that Boringtun had been rebased on a newer upstream branch and there were issues introduced in both the upstream code and during the rebase itself which resulted in connected sockets not working properly which in turn made boringtun default to using the listening socket for all communication.
Fixed connected socket misconfigurations and a deadlock in the connected socket handler. These changes had been done on Nordsecurity/Boringtun repo and had already passed review. Besides that a unit test was added to prevent connected socket misconfigurations and an integration test is being added by another dev with LLT-253 to ensure that connected socket is working …
=> Fix Boringtun issues causing slower network speeds

Cargo.lock, crates/telio-dns/Cargo.toml, crates/telio-dns/src/forward.rs, crates/telio-dns/src/nameserver.rs, crates/telio-dns/src/resolver.rs, crates/telio-dns/src/zone.rs
The only hickory crate we need to use is hickory-server
Rearrange imports and remove the other crates from `Cargo.toml` files
=> [LLT-5421] Cleanup hickory uses

.unreleased/LLT-5324, Cargo.lock, Cargo.toml, crates/telio-wg/Cargo.toml, crates/telio-wg/src/adapter/boring.rs
Boringtun runs on eco cores on Apple, sacrificing a performance.
Put Boringtun thread on a single performance core on Apple.
=> LLT-5324 Bump boringtun to v1.2.4

.unreleased/LLT-5384, crates/telio-dns/src/nameserver.rs, crates/telio-dns/tests/nameserver.rs
telio-dns only actually supports UDP packets, and while we don't intend to support any other protocol, we want to handle them more gracefully. 
The logic for UDP packets remain unchanged, new logic is added for TCP packets so that telio-dns simply returns a TCP reset, and for other protocols we produce a silent error.
=> LLT-5384: Handle non-UDP packets in telio-dns

.unreleased/LLT-5430, Cargo.lock, Cargo.toml, src/doc/integrating_telio.md, src/ffi.rs, src/ffi/logging.rs, src/ffi/types.rs, src/lib.rs, tests/logger.rs
Until now some of information was lost then telio was used from ffi api, because non of the extra fields there send via telio log callback.
Switched to tracing subscriber based implementation, as it correctly implements span logic, and will allow us to add additional systems in the future using layer approach.
=> Add tracing extra fields to logging callback

.github/workflows/gitlab.yml, .gitlab-ci.yml
Different images had been used when running nat-lab on linux and macos host.
Now that the linux build is published in both amd64 and arm64 versions, same version can be used.
=> Update trigger to 1.2.8 which uses same build image version for linux builder on linux and macos host

nat-lab/tests/test_connection_tracker.py, nat-lab/tests/utils/connection_tracker.py
Conntrack lacked support for filtering IPv6 pings
Filtering of IPv6 pings is added.
=> Conntrack filtering will now also filter IPv6 pings

nat-lab/tests/test_connection_states.py, nat-lab/tests/test_derp_connect.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_downgrade.py, nat-lab/tests/test_events.py, nat-lab/tests/test_events_link_state.py, nat-lab/tests/test_fire_connecting_event.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_mesh_off.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_mesh_remove_node.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_pmtu.py, nat-lab/tests/test_pq.py, nat-lab/tests/test_proxy.py, nat-lab/tests/test_reconnections.py, nat-lab/tests/test_telio_version_compatibility.py, nat-lab/tests/test_upnp_connection.py, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/ping.py
There is a small race between ping utility receiving first response, and [.wait_for_next_ping](https://github.com/NordSecurity/libtelio/blob/v5.0.0-rc2/nat-lab/tests/utils/ping.py#L54) being called. 
So all Ping utility uses has this pattern, when using ping utility:
```python
async with Ping(<connection>, <ping_target_ip_address>).run() as ping:
await ping.wait_for_next_ping()
```
In this case, when [.run()](https://github.com/NordSecurity/libtelio/blob/v5.0.0-rc2/nat-lab/tests/utils/ping.py#L60) is called, `ping` process is started, and then after some time - [wait_for_next_ping()](https://github.com/NordSecurity/libtelio/blob/v5.0.0-rc2/nat-lab/tests/utils/ping.py#L55) is called, which may `.clear()` first ping response. 
In a test like …
=> [LLT-5453] Fix ping race which may cause two ping requests being sent-out

.github/workflows/gitlab.yml
Sometimes nightly pipelines statistics does not catch all the pipelines, that were ran during the night.
Move the nightly pipelines 1 hour back.
=> LLT-5448 Move nightly scheduled pipelines 1 hour back

nat-lab/tests/test_cleanup.py, nat-lab/tests/test_pinging.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/router/linux_router.py, nat-lab/tests/utils/vm/container_util.py, nat-lab/tests/utils/vm/windows_vm_util.py
Sometimes native interfaces survive until the next test and can impact them.
Before each test, remove all native wireguard interfaces.
=> Remove native interfaces at the beginning of each test

.github/workflows/linters.yml
Unused-features job is consistently failing due to too old rustc version. Update rustc version for this job.
=> Update rustc only for unused-features job

nat-lab/tests/test_pinging.py, nat-lab/tests/utils/connection_tracker.py
Seems like previous root cause for `test_session_keeper` failures was incorrect, and we still have flakyness in the test. Therefore this PR allows to collect more information from the tests, to aid root-cause search.
=> Log conntrack events in test logs

nat-lab/tests/test_pinging.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/vm/container_util.py
Conntrack may rebuild existing TCP connections, which would report out-of-limits in `test_session_keeper`. Instead of building to separate conntrackers (which in the middle would execute `conntrack -F` causing all kinds of issues), setup conntracking at the beginning of the test, and avoid creating connections with side effects (like cleaning up conntrack table) in the middle of test-run.
=> Run conntracker before starting up meshnet in test_session_keeper

.github/workflows/gitlab.yml, .gitlab-ci.yml, nat-lab/natlab.py
Something is killing iptables and we don't know what it is and why.
Add audit log collection. Once we configure our VM(s) with correct audit rules, we will see all kill syscalls and their issuers.
=> Audit kills during docker containers startup

.unreleased/LLT-5473, nat-lab/tests/conftest.py
Sometimes the pre-condition fails and we would like to collect logs to debug what went wrong.
Copy the derp relay logs from the container to the artifact logs folder
=> Collect derp logs after pytest session

.unreleased/LLT-5452, Cargo.lock, Cargo.toml, crates/telio-model/Cargo.toml, crates/telio-model/src/features.rs, crates/telio-nurse/src/config.rs, nat-lab/bin/mac/list_interfaces_with_router_property.py, nat-lab/tests/helpers.py, nat-lab/tests/telio.py, nat-lab/tests/telio_features.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_pinging.py, nat-lab/tests/test_telio_features.py, nat-lab/tests/test_telio_tasks.py, src/doc/integrating_telio.md, src/ffi.rs, src/libtelio.udl
We mandate that device fingerprint is set manually when activating nurse even though the fingerprint can be fetched from moose. If we remove fingerprint from the nurse feature config we can properly implement default for nurse and make it so that apps don't have to deal with the fingerprint
Just remove it and make nurse active by default. The only issue with that strategy is that we have some natlab tests that use the device fingerprint so we need to keep those working. The strategy implemented here is that if moose doesn't contain a device fingerprint, we try to read it from a file (that is created by the natlab test) and if that fails, we use `missing-device-fp` so that it's easy to see in analytics that something went wrong.
=> LLT-5452: Remove fingerprint from nurse and enable nurse by default

.unreleased/LLT-5450, Cargo.lock, Cargo.toml
There was a regression in speed going from v0.5.2 to v0.6.0 boringtun
Minimized boringtun thread contention, speed increased ~20% compared to v0.5.2
=> LLT-5450 Bump boringtun to v1.2.6

nat-lab/tests/utils/connection/ssh_connection.py
It seems that for some reason some log files from Windows machines contain bytes that are not valid utf-8 characters. Let's not crash in such case and additionally let's dump those bytes to be able to analyze what's happening
=> Natlab: Do not crash on utf-8 decoding

.unreleased/lock_android_cores, crates/telio-wg/src/adapter/boring.rs
In our analyzis a big set of supported devices have 4 "performance" cores Some have 4/4 (mid/low), others 1/3/4 (high/mid/low).
For now locking to 4 seems to give biggest speed improvements while using all cores, causes unreliable performance.
Lock boringtun to 4 threads on android
=> Lock boringtun to 4 threads on android

.unreleased/LLT-4928, Cargo.lock, Cargo.toml, clis/tcli/Cargo.toml, src/ffi/logging.rs
External IP addresses are visible in the logs
We replace the IP addresses in the logs with some hashes, so they are not visible anymore
=> [LLT-4928] Mask IPs with regex

nat-lab/tests/conftest.py, nat-lab/tests/telio.py, nat-lab/tests/utils/analytics/event_validator.py
- We do not get verbose information, when `lana` validators fail.
- `interderp` pre-conditions timeout is too short.
- Print failing event, when validating and save `*-events.db` files to `logs` dir after each test.
- Increase pre-conditions timeout to 30 secs.
=> nat-lab: save moose DB files 

nat-lab/bin/client, nat-lab/bin/cone-gw, nat-lab/bin/fullcone-gw, nat-lab/bin/internal-symmetric-gw, nat-lab/bin/nordlynx, nat-lab/bin/pmtu-probe, nat-lab/bin/symmetric-gw, nat-lab/bin/udp-block-gw, nat-lab/bin/upnp-gw, nat-lab/bin/vpn-server, nat-lab/docker-compose.yml, nat-lab/natlab.py
We have been observing `iptables` process being killed by kernel in the testing environment. Recently  we have added [kernel logs capturing](https://github.com/NordSecurity/libtelio/pull/725), and observed that we are hitting NULL pointer deref. With the following stack trace:
```
[Tue Aug  6 01:19:33 2024 <    0.000194>]  ? __die_body.cold+0x1a/0x1f
[Tue Aug  6 01:19:33 2024 <    0.000201>]  ? page_fault_oops+0xd2/0x2b0
[Tue Aug  6 01:19:33 2024 <    0.000197>]  ? exc_page_fault+0x70/0x170
[Tue Aug  6 01:19:33 2024 <    0.000200>]  ? asm_exc_page_fault+0x22/0x30
[Tue Aug  6 01:19:33 2024 <    0.000198>]  ? iptable_nat_table_init+0xe1/0x168 [iptable_nat]
[Tue Aug  6 01:19:33 2024 <    0.000202>]  xt_find_table_lock+0x127/0x1b0 [x_tables]
[Tue Aug  6 01:19:33 2024 <    0.000204>] …
```
=> Add workaround for kernel bug

.github/workflows/gitlab.yml, .gitlab-ci.yml, ci/build_libtelio.py, ci/fetch_artifacts.py
`./ci/fetch_artifacts.py` should only allow to download artifacts when SHA of the tagged build and download destination build matches.
In the meantime, some error-handling refactoring was done in order to have more consistent exception-based error handling instead of returning `bool`.
=> [LLT-5488] Allow only to download artifacts from main/nightly/staging builds when commit sha matches

README.md, clis/tcli/src/cli.rs
Setting `mesh set-ip` on macOS fails. 
The correct command on macOS is `ifconfig <NAME> inet <IP_ADDRESS>/10 <IP_ADDRESS>`. In addition for meshnet we also need to add the correct routes to the interface.
=> Fix tcli `mesh set-ip` for macOS

ci/fetch_artifacts.py
A case was missed where `self.target_os` may be `None` [here](https://github.com/NordSecurity/libtelio/blob/main-2408061718-43ef9e7/ci/fetch_artifacts.py#L158) was missed causing typing errors during runtime. This PR adds filter for target_arch to be not none when attempting to download binary artifacts.
In addition requirement was added that at least one pipeline must match the filters, such that we would raise an error if download was skipped due to non-matching pipelines.
Failed run can be observed in pipeline `2379654`
=> [LLT-5492] Fix typing errors when arch is not specified

.unreleased/LLT-5124, Cargo.lock, Cargo.toml, crates/telio-relay/src/derp.rs, crates/telio-traversal/Cargo.toml, crates/telio-traversal/src/endpoint_providers.rs, crates/telio-traversal/src/endpoint_providers/upnp.rs
Crate `rupnp` seems to be used only for an error which should be unused anyway
Remove it
=> [LLT-5421] Remove rupnp crate from Telio

.unreleased/LLT-5493, crates/telio-lana/Cargo.toml, crates/telio-lana/src/lib.rs, crates/telio-lana/src/moose_callbacks.rs
During startup libtelio would wait for the moose init callback to be called. This is not needed since after init is completed, events will be saved.
Don't wait for the init callback to be called during the startup.
=> Assume libmoose initialized after moose::init has successfully returned

nat-lab/tests/telio.py
Lana test insert fingerprints via sqlite3 cli. Previously creating telio instance was blocking until lana init callback was initialized. After #753 this is no longer the case.
Wait for the lana init callback success log directly in the test before trying to insert the fingerprint.
=> Wait for the moose init callback logs success message before inserting fingerprint in tests

crates/telio-lana/src/lib.rs
The test waited until the callback was called, not until the callback finished.
Wait for the results of calling the callback to happen. Additionally a bug in `test_init_lana_with_failing_moose_init` is fixed - init returning true but calling callback with success would be a bug in moose.
=> Fix a race in test_init_lana_with_failing_moose_init_cb

nat-lab/Pipfile, nat-lab/Pipfile.lock, nat-lab/bin/cleanup_natlab_processes, nat-lab/bin/kill_process_by_natlab_id, nat-lab/tests/conftest.py
When running tests, it is important to ensure that environment is in a state expected by tests. One thing is that no leftover processes must exist from previous tests. Luckily all processes started by nat-lab has `KILL_ID` set in environment variable, used exactly for this purpose - killing them, when they become unecessary.
This PR adds a small script (must be run with elevated privileges inside of testing environment due to fact, that processes being run inside of docker containers has root privileges). which kills nat-lab processes pre-test run.
=> [LLT-5474] Cleanup natlab processes in pretest setup hook

.unreleased/LLT-5494, nat-lab/tests/test_features_builder.py, src/ffi.rs, src/ffi/defaults_builder.rs, src/lib.rs, src/libtelio.udl
When a consumer of this library wants to construct feature config, until now he was
forced to use JSON, or provide all default features himself.
This either easily leads to miss-configuration due to typos, or making
code not forward compatible.
A new ffi added, FeaturesDefaultsBuilder, that allows to construct individual features, with libtelio prefered defaults.
=> LLT-4494: Add tool to build defaults for individual features

.unreleased/LLT-5309, Cargo.lock, crates/telio-model/src/constants.rs, crates/telio-nurse/src/qos.rs, crates/telio-starcast/src/starcast_peer.rs, crates/telio-starcast/src/transport.rs, crates/telio-utils/Cargo.toml, crates/telio-utils/src/const_ipnet.rs, crates/telio-utils/src/lib.rs, nat-lab/bin/multicast.py, nat-lab/tests/test_multicast_connection.py, nat-lab/tests/utils/multicast.py, nat-lab/tests/utils/vm/windows_vm_util.py, src/device.rs, src/device/wg_controller.rs
All the separate parts of starcast (see RFC LLT-0060) are ready to be integrated into Telio.
This PR integrates all the separate starcast parts (virtual peer, transport and nat) into libtelio.
You can see the doc rs in code of every separate component to understand how they're supposed to be integrated into telio. 
The Nat-Lab test for multicast is being implemented with a separate PR, so this one is untested yet.
=> Llt 5309 integrate multicast components

.github/workflows/gitlab.yml, .gitlab-ci.yml, .unreleased/LLT-5072, Cargo.toml, ci/build_libtelio.py, ci/insert_libtelio_version.py
- With the merge of https://github.com/NordSecurity/rust_build_utils/pull/23 binary stripping will be moved to `rust-build-utils` scripts.
- Windows and macOS debug symbols were not being released.
This PR removes binary stripping from `build_libtelio.py` and adds post-build stages to copy the debug-symbols to the distributable directory `/dist`.
=> LLT-5072: Move linux binaries strip to rust_build_utils

nat-lab/bin/client
In Non-Initial network namespaces conntrack is deactivated until some reference is created. We have been using:
```
iptables -A INPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
```
to add a reference, but this rule is a bit too intrusive and may cause spurious packets being accepted inside testing containers. Therefore I am proposing to change it to:
```
iptables -A INPUT -m conntrack --ctstate ESTABLISHED -j LOG --log-level debug
```
in this PR.
=> Update conntrack trigger rule to be actually noop

nat-lab/tests/test_telio_version_compatibility.py
During removal of tcli from natlab it was noticed that version_compatability_test was not working. I've attempted to rewrite it that time, but failed. Decided to come for it later.
Fix test that was not working
=> fix version compatability test

Cargo.lock, Cargo.toml, crates/telio-batcher/Cargo.toml, crates/telio-batcher/src/batcher.rs, crates/telio-batcher/src/lib.rs, crates/telio-model/src/features.rs, crates/telio-traversal/Cargo.toml, crates/telio-traversal/src/session_keeper.rs, nat-lab/tests/conftest.py, nat-lab/tests/telio_features.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_features_builder.py, src/device.rs, src/device/wg_controller.rs, src/ffi/defaults_builder.rs, src/lib.rs, src/libtelio.udl
According to empirical testing and some research it appears that sending more data at once is beneficial to battery instead of sending sporadically.
- SessionKeeper is modified to hold both `RepeatedActions` and `Batcher` instances and uses each one depending on the passed enum parameter. This is done for safety so the chances of problems introduced.
Having no batcher option should not ever trigger it.
=> LLT-5339: Session Keeper ping packet batching

README.md, build.rs
Fix typos where `BYPASS_LLT_SCAN` should be `BYPASS_LLT_SECRETS`.
=> docs: Correct BYPASS_LLT_SCAN to BYPASS_LLT_SECRETS

nat-lab/tests/conftest.py
When running tests locally 1 by 1, not always there will be test name, that would include `["windows', "mac"]` strings in it. If tests name doesn't contain those string, binaries won't be copied to VMs. Doesn't apply to CI, since it is running all tests, which certainly includes those strings.
Add separate binary copying according to `CUSTOM_ENV_GITLAB_CI` variable, indicating if it is run in CI or not.
=> copy all binaries when running locally during collection

.unreleased/LLT-5507, crates/telio-model/src/features.rs, nat-lab/tests/telio_features.py, src/device.rs, src/device/wg_controller.rs, src/ffi/defaults_builder.rs, src/ffi/logging.rs, src/libtelio.udl
IPs should always be hidden in production, but hiding them makes it hard to investigate bugs found in the nat-lab tests. This is why a flag to control IP hiding has been added. While it defaults to hiding the IPs, for the nat-lab tests (and only for that case) it defaults to show IPs by changing pytests default value.
Additionally, as a side effect, the log censoring functionality no longer makes copies of log message strings when they haven't been modified.
=> Make it possible to control using the `hide_ips` if the IP addresses are hidden

nat-lab/tests/telio.py, nat-lab/tests/telio_test.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_telio_version_compatibility.py, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/iperf3.py, nat-lab/tests/utils/output_notifier.py, nat-lab/tests/utils/process/process.py
To be able to pass output notifier as process callback, we have to wrap it in `on_stdout` function to work, which makes no sense, when we should be able to pass `output_notifier.handle_output` as callback.
Make output notifier handle output function possible as callback of process in natlab
=> Make output notifier possible as stdout/stderr callback in natlab

nat-lab/run_local.py
Debugging rare failing natlab test doesn't show up the problem if test is run only once
Add parameter to run test multiple times.
=> Add count pytest parameter in natlab

crates/telio-model/src/config.rs, crates/telio-model/src/mesh.rs, src/device.rs, src/libtelio.udl
Sanitize nicknames making them hidden from the logs, just like hostnames, the difference is that nicknames are wrapped in an Option<>, telling if is whether or not set.
=> Sanitize nicknames from logs

nat-lab/tests/telio.py, nat-lab/tests/test_adapter.py, nat-lab/tests/test_connection_states.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_dns_through_exit.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_off.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_proxy.py, nat-lab/tests/test_upnp_connection.py
Introduce checking for errors in our logs. It is possible that some tests like e.g. test_adapter_gone_event will emit error logs and this is expected. For that reason self._allowed_errors was introduced in telio.py. But most happy path tests should not emit them. Tests that should be checked and cleaned up are marked with LLT-5532 tag and the jira task is created for it.
=> Nat-lab: Check logs for errors

nat-lab/tests/test_connection_states.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_lana.py
=> Nat-lab: Allow more error logs

.github/workflows/gitlab.yml, .gitlab-ci.yml
This bump increases number of shards for nat-lab job from 6 to 9
=> Bump libtelio-build version

nat-lab/natlab.py, nat-lab/tests/conftest.py
Some places where we save logs aren't respecting the `NATLAB_SAVE_LOGS` environment variable
Make those places respect the env var
=> Make more logs respect NATLAB_SAVE_LOGS env var

nat-lab/tests/utils/network_switcher/network_switcher_docker.py, nat-lab/tests/utils/network_switcher/network_switcher_mac.py, nat-lab/tests/utils/network_switcher/network_switcher_windows.py
On natlab machines, switching to primary/secondary network has different implementations wether we're working with the Windows/Mac VM or the docker containers.
This is implicit knowledge, however the developer might not be aware of these differences and it can be a bug source in the future.
Add function documentation to state what each network switch does.
=> natlab: Add comments differenciating primary routes switch

nat-lab/tests/conftest.py
Sometimes if you just want to run a quick natlab test or two, adding in the derp checks adds unnecessary time
Add an environment variable that lets you skip the setup checks, with the default being to run them
=> Add env var to skip natlab setup checks

nat-lab/tests/telio.py
Currently we are checking for errors in our logs. And if some are found we are failing the tests, though some errors in logs are expected and not an issue.
Temporarily disable failing the pipeline on errors in logs until we have the capacity to investigate which ones are acceptable.
=> Warn on unnexpected errors in logs

.unreleased/LLT-5519, crates/telio-traversal/src/connectivity_check.rs, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/endpoint_providers/stun.rs, crates/telio-traversal/src/endpoint_providers/upnp.rs, crates/telio-wg/src/uapi.rs, crates/telio-wg/src/wg.rs, src/device.rs, src/device/wg_controller.rs
Until now it was possible that wg event comming into device.rs and
tick happening in device.rs, could lead to invalid race condition.
If in that situation, select pick's consilidation step, while
old endpoint exists in cross ping check, and peer just downgraded
to relay do to roaming, wg_controller would again put that
peer to an invalid direct connection.
Eposed Instant information, next to compared endpoints to ensure correct causality order
=> [LLT-5519] Fix roaming vs cross_ping_check racing

.unreleased/LLT-5498, crates/telio-model/src/mesh.rs, crates/telio-nurse/src/data.rs, crates/telio-nurse/src/heartbeat.rs, crates/telio-nurse/src/nurse.rs, crates/telio-nurse/src/qos.rs, crates/telio-traversal/src/endpoint_providers/stun.rs, crates/telio-traversal/src/endpoint_providers/upnp.rs, crates/telio-utils/src/dual_target.rs, crates/telio-utils/src/ip_stack.rs, crates/telio-utils/src/lib.rs, crates/telio-utils/src/pinger.rs, crates/telio-wg/src/link_detection.rs, crates/telio-wg/src/link_detection/enhanced_detection.rs, crates/telio-wg/src/wg.rs, nat-lab/bin/cone-gw, nat-lab/bin/fullcone-gw, nat-lab/bin/internal-symmetric-gw, nat-lab/bin/symmetric-gw, nat-lab/bin/udp-block-gw, nat-lab/bin/upnp-gw, nat-lab/tests/helpers.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_pinging.py, nat-lab/tests/utils/analytics/event_validator.py, src/device.rs
Libtelio modules, which uses `pinger`, did not checked the IP stack, which is currently used on adapter (`IPv4`, `IPv6`, or dual `IPv4v6`) and so `pinger` can actually open the `IPv4` socket, even if the current stack is `IPv6`, but the source address would be set (by OS) to out-of-tunnel address.
Check, what stack is used, before performing ping requests in-tunnel.
=> LLT-5498 Add ip stack check for modules with Pinger

.gitignore, nat-lab/tests/interderp_cli.py, nat-lab/tests/mesh_api.py, nat-lab/tests/telio.py, nat-lab/tests/utils/testing.py
Our nat-lab test log files are getting so long it sometimes manages to reach filename limit’s in Windows.
And it’s extremely hard to focus in on all of data produced for a singular tests. 
Instead of storing all logging artifacts in one directory, with long names. Create a sub directories
for each test, that stores log for all logs/pcaps etc created for this test.
=> LLT-5531: Directory per test for logs

nat-lab/tests/helpers.py, nat-lab/tests/test_events.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_pinging.py, nat-lab/tests/test_telio_version_compatibility.py, nat-lab/tests/utils/connection_tracker.py
Nat-lab tests with ConnectionTracker `get_out_of_limits()` sometimes fail, even though in the logs the connections are present.
- Add lock to ensure thread safe operation.
- Add mechanism to ensure we synchronized to a known event.
- Add more logs.
=> Conntracker sync

.github/workflows/gitlab.yml, .gitlab-ci.yml
Seems like we are hitting github pull limits
Mitigate by using build with lower sharding
=> Bump build version to one with lower shards

.github/workflows/linters.yml
```
error: failed to compile `cargo-unused-features: v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-install3SVrCi`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
rustc 1.78.0 is not supported by the following package:
cargo-util@0.2.14 requires rustc 1.79
Try re-running `cargo install` with `--locked`
```
=> Fix unused-features linter

nat-lab/Pipfile, nat-lab/Pipfile.lock, nat-lab/tests/telio.py, nat-lab/tests/test_batching.py, nat-lab/tests/utils/batching.py
Batching tests, as per design session, should be star-like with multiple different nodes and idling. Then we should observe batching over the course of the time and see that it's working.
Setup preferred meshnet topology, launch tcpdump on nodes of interest, then aggregate packet captures by using filters into histograms and display them.
Existing configuration in this PR is pretty minimal, just few directly connected nodes. Windows, MacOS, VPN, Proxied peers will be added next.
As a result currently we can see some histograms but we still need to:
- add proper configuration
- add various filters to observation while we don't have fully implemented the batching
=> Llt 5483 big batching test

.unreleased/LLT-5183, Cargo.lock, Cargo.toml, crates/telio-network-monitors/Cargo.toml, crates/telio-network-monitors/src/apple.rs, crates/telio-network-monitors/src/lib.rs, crates/telio-network-monitors/src/linux.rs, crates/telio-network-monitors/src/local_interfaces.rs, crates/telio-network-monitors/src/monitor.rs, crates/telio-network-monitors/src/windows.rs, crates/telio-sockets/Cargo.toml, crates/telio-sockets/src/protector/apple.rs, crates/telio-traversal/Cargo.toml, crates/telio-traversal/src/endpoint_providers/local.rs, nat-lab/tests/telio.py, nat-lab/tests/test_network_monitor.py, nat-lab/tests/utils/router/linux_router.py, nat-lab/tests/utils/router/mac_router.py, nat-lab/tests/utils/router/router.py, nat-lab/tests/utils/router/windows_router.py, src/device.rs
https://github.com/NordSecurity/libtelio/pull/529 introduces filtering in firewall on incoming packets on local IP. Calling if-addr on every packet is an expensive process.
Cache local IPs, and update it on notification from the OS.
P..S.
This PR is currently divided into 5 commits. I have tried to separate them as logically as possible. There might be some overlap. Each commit can be looked at separately, but some things (very minor things) might have changed in future commits.
1 - Separates out fetching local interfaces into its own module
2 - Creates a network monitor module and adds network monitoring for Apple. Apple has a callback for network and link changes. As far as I could see, there is no need to deregister or cleanup.
3 - Creates a network monitor for linux and windows. Uses …
=> LLT 5183 list local if ip

nat-lab/tests/telio.py, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/multicast.py, nat-lab/tests/utils/python.py
On the vagrant macOS box we have a manual installing of python. When running python commands in nat-lab, `connection.create_process()` doesn’t see the new python installation path, since `/etc/profile` is not sourced. And tries to run the default system python, which fails with:
```
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'
```
Simplify the way python scripts are executed on macOS, by providing a helper function that gives the full path to the python installation.
=> LLT-5540: macOS python path

.unreleased/LLT-5402, crates/telio-batcher/src/batcher.rs, crates/telio-traversal/src/session_keeper.rs, crates/telio-utils/src/dual_target.rs, crates/telio-utils/src/repeated_actions.rs, src/device.rs, src/device/wg_controller.rs
Disable Wireguard keepalives for stun, vpn and proxied peers and use the session keeper intead because we want them to be batched for battery lifetime improvements.
=> Use batcher for stun, vpn and proxied peers keepalives

nat-lab/tests/test_connection_tracker.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/connection_tracker.py
There are tests (like `test_mesh_firewall.py`) where we are manually starting `conntrack` in order to observe TCP state changes. Occasionally they fail because they might be missing the new connetion events, and `conntrack` does not report on subsequent states in that case. We need to make sure that `conntrack` is ready to process events before proceeding with the test.
- Added mechanism to the existing `ConnectionTracker` class to track TCP states alongside connection limits, in order to utilize it's synchronization mechanism.
- Updated tests to use `ConnectionTracker` instead of manually starting `conntrack` process.
=> LLT-5586: Conntracker TCP states

Cargo.lock, crates/telio-traversal/Cargo.toml, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/endpoint_state.rs, crates/telio-traversal/src/lib.rs
[SM crate ](https://crates.io/crates/sm) is deprecated and thus no longer maintaned. We've been using it to define a endpoint state machine for cross ping check component of telio-traversal:
```
sm! {
EndpointState {
InitialStates { Disconnected }
SendCallMeMaybeRequest {
Disconnected => EndpointGathering
}
ReceiveCallMeMaybeResponse {
EndpointGathering => Ping
}
Publish {
Ping => Published
}
Timeout {
EndpointGathering => Disconnected
Ping => Disconnected
}
EndpointGone {
Published => Disconnected
}
}
}
```
Because of this dependency we've been required to keep old versions of `quote`, `proc-macro2` and `syn` crates.
This PR replaces the FSM defined using the SM crate and removes that crate from libtelio workspace.
=> [LLT-4929] traversal: Remove SM crate from cross ping check

crates/telio-wg/src/uapi.rs
Uapi parsing code is triggering checkmarks analysis, privating misbehaving functions (there is no need for pub), and removing
not used allows.
=> Cleanup uapi parsing functions

nat-lab/tests/config.py, nat-lab/tests/helpers.py, nat-lab/tests/mesh_api.py, nat-lab/tests/telio.py, nat-lab/tests/test_batching.py, nat-lab/tests/test_derp_connect.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_events.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_api.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_mesh_off.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_mesh_remove_node.py, nat-lab/tests/test_reconnections.py, nat-lab/tests/test_telio_version_compatibility.py, nat-lab/tests/uniffi/libtelio_proxy.py, nat-lab/tests/uniffi/libtelio_remote.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/network_switcher/network_switcher_mac.py
This is the second PR to start using types generated from UniFFI instead of defining new ones, where possible, in natlab. This PR deals with the meshnet config.
Some notes:
- The `(get|set)_meshmap` functions have been renamed to `(get|set)_meshnet_config`
- Strong types instead of dicts means that we can do things like `derp.ipv4` instead of `derp["ipv4"]`
=> LLT-5534: Use generated meshnet config in natlab

nat-lab/tests/utils/connection_tracker.py
Sometimes sync events get counted towards ICMP events and some tests fail.
Don't count any ICMP events from 127.0.0.2
=> Conntracker skip all events from sync_connection

nat-lab/tests/helpers.py, nat-lab/tests/telio.py, nat-lab/tests/telio_test.py, nat-lab/tests/test_adapter.py, nat-lab/tests/test_batching.py, nat-lab/tests/test_derp_connect.py, nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_downgrade.py, nat-lab/tests/test_events.py, nat-lab/tests/test_events_link_state.py, nat-lab/tests/test_fire_connecting_event.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_off.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_node_state_flickering.py, nat-lab/tests/test_pinging.py, nat-lab/tests/test_proxy.py, nat-lab/tests/test_reconnections.py, nat-lab/tests/test_telio_version_compatibility.py, nat-lab/tests/test_upnp_connection.py, nat-lab/tests/uniffi/libtelio_proxy.py, nat-lab/tests/uniffi/libtelio_remote.py, nat-lab/tests/utils/bindings.py
This is PR 3/4 to replace bespoke types in natlab with those in the generated python bindings. This PR deals with using strongly typed events, which brings with it the need to start using some related types from the bindings, making the PR a bit on the bigger side. Most of the changes should be conceptually quite simple with mostly changes like `State.Connected` -> `NodeState.CONNECTED`
=> LLT-5535: Use generated events in natlab

nat-lab/tests/test_teliod.py
Teliod test is flaky
Removes sleeps and timeouts, ensures that the socket is created before running the next Teliod instance, uses waiting killall instead of kill.
=> [LLT-5635] Fix Teliod test

.unreleased/LLT-5653, Cargo.lock, Cargo.toml, nat-lab/tests/test_vpn.py
The feature panics on MacOS.
It is caused by the fact that borintun writes more bytes to the tunnel than the packet size and we implement `io::Write::write()` for the tunnel sink. Down the road, we use its `io::Write::write_all()` implementation which panics if the returned number of bytes is larger than the buffer size.
Override the default implementation of the `io::Write::write_all()` to mitigate the panic.
=> Fix reset connections firewall feature panic on MacOS

nat-lab/tests/test_vpn.py
The old AdapterType was removed in favor of the generated TelioAdapterType, but between the last commit on that migration PR being pushed and the pipeline being green so it could be merged, another PR added a new test relying on the old AdapterType. because of that, the PRs were incompatible but had no code conflicts, and got the repo into a bad state
=> Fix bad adapter type in natlab

crates/telio-traversal/src/connectivity_check/cross_ping_check.rs
It is not guaranteed that `wg_controller` will use every published endpoint, which means, that existing [exponential backoff reset](https://github.com/NordSecurity/libtelio/blob/main/crates/telio-traversal/src/connectivity_check/cross_ping_check.rs#L758) may not occur. But in any case, if endpoint has passed the validation - we may reset exponential backoff already, as we know, that required information has flown succesfully between two meshnet nodes.
=> Reset exponential backoff on succesfull endpoint verification

nat-lab/tests/telio.py, nat-lab/tests/test_vpn.py, nat-lab/tests/uniffi/libtelio_proxy.py
Some libtelio code is synchronous blocking, which might block main thread.
Wrap all libtelio_proxy functions with asyncio.to_thread so those calls wouldn’t block async threads.
=> Move sync blocking code to thread

.unreleased/LLT-4963, crates/telio-model/src/features.rs
I runned some tests with optimization enabled/disabled to measure the relay to direct recovery time.
The scenario used for tests:
- Node A and B are directly connected
- Cut the connection and expect downgrade to relay
- Undo the cut and wait for path upgrade to direct
Times measured between relay event to the direct event showed that the recover process is faster with the optimization enabled.
For STUN is with 3-4 seconds faster.
For UPNP is with 10 seconds faster.
Nevertheless this is a battery lifetime improvement feature and we want to push apps to use it leaving them the option to disable it if needed.
=> Make STUN and UPnP providers optimization enabled by default

.unreleased/LLT-5660, clis/tcli/src/cli.rs, crates/telio-pq/src/conn.rs, crates/telio-pq/src/lib.rs, crates/telio-pq/src/proto.rs
On UDP packet drop PQ methods can hang on `recv()` call
Introduce a timeout for UDP socket `recv()` calls and handle the error
=> Fix possible PQ methods hang condition

.github/workflows/gitlab.yml, .gitlab-ci.yml, Cargo.toml, ci/build_libtelio.py, nat-lab/run_local.py, nat-lab/tests/config.py, nat-lab/tests/conftest.py, nat-lab/tests/test_teliod.py, nat-lab/tests/utils/vm/mac_vm_util.py, nat-lab/tests/utils/vm/windows_vm_util.py
By default release builds are used on build scripts, and release build profile is configured to use compiler size optimization flags which slows down compilation, taking around double the time than without optimizations. Also, `tcli` is no longer required to run nat-lab, therefore it shouldn't be built by default when running build scripts.
This commit adapts build scripts to make use of debug binaries and stop building tcli implicitly. 
Tcli is now built when `--tcli` flag is passed and debug builds are now fully supported for natlab and other build scripts functionalities.
Benchmarking results for release vs. optimized dev profile:
Linux:      **6m46s -> 1m50s**
Win:        **8m24s -> 1m40s**
macOS:  **9m33s -> 43s**
Android: **2m47s -> 1m05s**
=> natlab: Add support for faster debug builds

nat-lab/tests/conftest.py, nat-lab/tests/interderp_cli.py
When interderpcli failed to execute there is only INTERNALERROR exception of the process printed out to the execution trace which not helps to identify the actual root cause.
In case of exception raised during execution of interderpcli process save_logs method can be called to save interderpcli.log content.
=> [LLT-5674] Collect interderpcli logs in case of process failure

nat-lab/bin/dns-server
Request to subdomain `www.google.com` are being made but the dns is lacking an entry for it.
Add new entry for `www.google.com`.
=> Add missing subdomain www.google.com in nat-lab's dns

nat-lab/tests/helpers.py, nat-lab/tests/mesh_api.py
it feels like sometimes mesh_api gives wrong or empty values, therefore further actions in test fails
for debugging purposes print out api/node in natlab when setup is done
=> LLT-5677: print api nodes on setup

nat-lab/bin/core-api.py, nat-lab/tests/test_core_api.py
This is a minimal hosted version of API in nat-lab. 
It implements all /machine API methods.
Some of the data is mocked and the actual configuration of the peers is not implemented.
This will be taken care of with further PRs as redesigning the current mesh_api implementation is required. 
=> [LLT-5563] Minimal hosted version of API in nat-lab

crates/telio-starcast/src/transport.rs
`telio-starcast` unit tests may fail non-deterministically due to Err("WouldBlock") return value from `.try_recv()`
Convert `try_recv()` to `recv().await` and wrap in a Timeout future
=> LLT-5664: Wrap flaky starcast test in timeout future

.unreleased/LLT-5681, build.rs
Android binaries do not pass `checksec` stack canary scan.
Add the required compilation flag.
=> [LLT-5681] Enable stack canary

clis/interderpcli/src/main.rs
Timeouts in interderpcli are suspected to be to short which is causing nat-lab failures.
Increase timeouts in interderpcli from 3s to 10s
=> Increase timeout in interderpcli to 10s

.unreleased/LLT-5675, Cargo.lock, crates/telio-wg/Cargo.toml, crates/telio-wg/src/wg.rs, nat-lab/tests/test_events_link_state.py
At some point the logic in is_link_up has been changed and it no longer used the WG_KEEPALIVE and RTT.
=> Fix link detection fluctuations

.unreleased/LLT-5663, crates/telio-wg/src/wg.rs, nat-lab/tests/test_events_link_state.py
Use real rx/tx stats that are updated in uapi
CONNECTED/CONNECTING status is based on `time_since_last_rx` value which is cached per peer and normally updated each second based on `self.stats` which contains timestamp of last received data and last sent data. But the `self.stats` is only updated later in the same iteration. Meaning, that `self.time_since_last_rx` will not get updated till the next iteration. Causing TTC for wg peers to increase with extra second.
Update `self.stats` at the start of iteration.
=> LLT-5663: Fix TTC for wg peers

nat-lab/tests/conftest.py, nat-lab/tests/interderp_cli.py, nat-lab/tests/mesh_api.py, nat-lab/tests/telio.py
interderp check fails and we don't know really know why
- print interderp logs
- catch tcpdump dumps for derp servers
=> add tcpdump for interderp check

crates/telio-wg/src/link_detection.rs, crates/telio-wg/src/link_detection/enhanced_detection.rs, crates/telio-wg/src/wg.rs
Link detection had very little logs and now seems to fail on one of the cases. Having more logs is crucial in observing what is happening.
=> Add more debug logs to link detection

nat-lab/tests/utils/ping.py
Then test times out due to global timeout, and ping is the failure reason, it's may be unclear what was not reached
Attempt to add this information as task name.
=> Add ping argument information

Cargo.lock, crates/telio-dns/Cargo.toml
test_dns* test sometimes fail with a nslookup timeout. It looks as if the dns forwarder sometimes taking a lot of time to resolve the queries.
This adds more (temporary) logs to the underlying dns library
=> Temporary logs in the dns library to track down nat-lab failure

.github/workflows/gitlab.yml, .gitlab-ci.yml
Upgrade libtelio-build reference to allow manually triggering job to upload xcframeworks.
=> Update libtelio-build reference

nat-lab/tests/conftest.py
When running natlab precondition checks, we are not retrying if we get process error.
Retry precondition check when we get process error.
=> add process exec error handling in natlab precondtions

.github/workflows/gitlab.yml, .gitlab-ci.yml, nat-lab/tests/config.py
Old VM dependencies, missing windump for windows VM
Updated VM dependencies, added windump
=> Update libtelio build ref to v2.4.10

.github/workflows/gitlab.yml, .github/workflows/linters.yml, .gitlab-ci.yml, nat-lab/tests/config.py
Reverts NordSecurity/libtelio#878
Windows VM sometimes hang during `vagrant up` -> therefore the revert, since the issue is resolved
=> Revert "Update libtelio build ref to v2.4.10"

.unreleased/LLT-5593, Cargo.lock, Cargo.toml, crates/telio-model/src/features.rs, crates/telio-utils/Cargo.toml, crates/telio-utils/src/lib.rs, crates/telio-utils/src/log_censor.rs, nat-lab/tests/utils/bindings.py, src/device.rs, src/device/wg_controller.rs, src/ffi/defaults_builder.rs, src/ffi/logging.rs, src/libtelio.udl
DNS forwarding can lead to logging of the domain names used by the user.
Since domain names are logged as part of structures not owned by libtelio, instead of using `Hidden` the same approach as IP hiding is used - `LogCensor`.
=> Llt 5593 sanitize dns names

crates/telio-utils/src/tokio.rs, src/ffi/logging.rs, tests/logger.rs
We suspect that tokio threads are blocked by some blocking operations.
Print a log when some thread goes from unparked to parked after more than 1s - telio has no place where it expects to be doing work for that long without a break. To make it simpler to match with what was happening thread ID will also be printed in the logs.
=> Detect long blocking tasks

.github/workflows/build.yml, .github/workflows/linters.yml
macOS clippy workflow is [occasionally failing](https://github.com/NordSecurity/libtelio/actions/runs/11365707093/job/31614492082?pr=868) with `(signal: 6, SIGABRT: process abort signal)`.
MacOS-12 runners are [deprecated by GitHub](https://github.com/actions/runner-images/issues/10721) and will be removed.
`actions-rs` Rust GitHub actions are [unmaintained and archived](https://github.com/actions-rs).
Update the macOS workflow runners to `macos-13` for `x86_64` targets and `macos-14` for `aarch64`.
Remove `actions-rs` dependency for macOS clippy workflow, as the GitHub Runners already come with all the Rust [tools preinstalled](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#rust-tools).
=> Update macOS clippy runner and remove actions-rs

.github/workflows/linters.yml, crates/telio-nurse/src/nurse.rs
In natlab tests, calls to `lana!(flush_changes)` took more than 1s. Since it's non-async, it blocks the thread on which current async task is running.
To fix this, it's wrapped in `spawn_blocking` which moves it to a separate thread where tokio is expecting blocking to occur.
Also fixed the CI job for unused-features by locking in the dependency versions.
=> Move moose flush to spawn blocking

.unreleased/LLT-5554, Cargo.lock, clis/teliod/Cargo.toml, clis/teliod/README.md, clis/teliod/example_teliod_config.json, clis/teliod/src/comms.rs, clis/teliod/src/config.rs, clis/teliod/src/main.rs, clis/teliod/src/nc.rs, nat-lab/data/teliod/config.json
Teliod needs to be notified about meshnet changes which means it has to have a connection to Notification Center.
Implement Notification Center connection using rumqttc. After #853 is merged, the placeholder callback(s) will be replaced by triggering of meshmap update.
Integration tests will be done once core api support is added to nat-lab.
=> LLT-5554: Add MQTT notification center support to `teliod`

.unreleased/LLT-5710, crates/telio-dns/src/dns.rs, nat-lab/tests/telio.py, nat-lab/tests/test_pq.py, src/device/wg_controller.rs
Magic DNS breaks when a PQ connection is established
Magic DNS relies on the stable public key of the WG interface. When connecting to the PQ server the keys change and are rotated every few minutes. The fix is to notify the DNS about this change.
=> Fix magic DNS not working under PQ VPN

.unreleased/LLT-5108, crates/telio-starcast/src/nat.rs, crates/telio-starcast/src/transport.rs, nat-lab/tests/mesh_api.py, nat-lab/tests/test_mesh_api.py, nat-lab/tests/test_multicast_connection.py, src/device.rs
`allow_multicast` and `peer_allow_multicast` flags are present in mesh config, but not implemented in starcast yet.
Add code that removes peers from multicast peer list if we have `allow_multicast` set to false for them and prevent starcast from sending multicast packets to peers who have `peer_allow_multicast` set to false, but still receive multicast packets from those peers.
=> Add allow_multicast flags from mesh config to starcast integration

.github/workflows/gitlab.yml
So it turns out, that current implementation of label based variant for controlling whether workflows are being run or not for 3rd-party contributors is not good enough. Abusing it still requires maintainer action, but really non-obvious one. For this reason, a reusable workflow has been implemented, which will be pinned in github settings to be the only one allowed to run on the private runner. The workflow is already implemented and merged, hence this PR, which migrates from github actions (which you cannot pin) to workflow (which you can pin).
=> Retarget libtelio from trigger gitlab action to reusable workflow

nat-lab/Dockerfile, nat-lab/data/custom_debs/README
Ability to override nordderper(will be used to trigger natlab with custom nordderper via Nordderper repo).
This is a generic solution though but the primary target is to trigger the natlab from derper project with custom derper.
=> Ability to override nordderper

.unreleased/async-logs, src/device.rs, src/ffi/logging.rs, tests/logger.rs
To avoid blocking callers, when logging is slow, the call to the logging callback is moved to the separate therad. Now, logging anything only causes non blocking try_send that will fail if there is no more space in the queue of not yet processed log messages.
To have some visibility into how this system performs, count of dropped logs is printed along side one of the periodic logs of libtelio.
=> Call logging callback on a separate thread

src/device/wg_controller.rs
Some of the tests in wg_controrller started to fail on main. After local reproduction, it turns out that `EndpointProvider::name()` was called on a mock instance without any expectation set for that function.
The snippet that requires `expect_name` is this: https://github.com/NordSecurity/libtelio/blob/main/src/device/wg_controller.rs#L198-L206
Add `expect_name` call.
=> Fix broken (unexpected 'name()' call) wg_controller tests

nat-lab/tests/telio.py, nat-lab/tests/uniffi/libtelio_proxy.py, nat-lab/tests/uniffi/libtelio_remote.py
`libtelio_remote.py` when consuming logs via callback would open and close log file on every single log line, which is really innefficient. This PR reuses the same open file handle for the duration of `libtelio_remote.py` process itself.
=> [LLT-5725] avoid opening and closing log file on every log line

nat-lab/bin/dns-server, nat-lab/bin/dns-server.sh, nat-lab/docker-compose.yml, nat-lab/tests/conftest.py
Logs from dns server (and tcpdump pcaps) are not collected from dns servers, but are needed for nat-lab investigation.
Dns logs are now timestamped and are collected once per the run_local.py run. The pcaps are collected per test.
=> Llt 5617 collect dns server logs

.github/workflows/gitlab.yml, .gitlab-ci.yml
This error was found in one of the CI, possibly preventing libtelio from working correctly on windows
```
794 Oct 26 02:09  Error       Server                 3221227977 The server could not bind to the transport \Device
\NetBT_Tcpip_{0E186230-9C20-2C05-1B58-9DF3FA403D1A
} because another computer on the network has the 
same name.  The server could not start.           
```
Adding custom hostname to prevent collision
=> bump libtelio build to v2.4.12

crates/telio-nurse/src/nurse.rs, nat-lab/tests/telio.py, nat-lab/tests/test_lana.py, src/device.rs
`test_lana_same_meshnet_id_is_reported_after_a_restart` fails with a different meshnet id after the restart:
```
[2024-10-25 19:30:02] FAILED tests/test_lana.py::test_lana_same_meshnet_id_is_reported_after_a_restart[IPv4-IPv4v6] - AssertionError: assert '628c9cbb-8627-40ad-9b6c-518596d836a9' == 'd3dc4ef2-125d-43a6-b9d7-786f2879269b'
[2024-10-25 19:30:02]   
[2024-10-25 19:30:02]   - d3dc4ef2-125d-43a6-b9d7-786f2879269b
[2024-10-25 19:30:02]   + 628c9cbb-8627-40ad-9b6c-518596d836a9
```
1. Additional logs are added to track values of the meshnet id at startup.
2. Additional logs are added to track device fingerprint at startup (it is modified by test in `maybe_write_device_fingerprint_to_moose_db`
3. Both logs and event database are saved after the client is shutdown but before it is …
=> Better tracking of meshnet ID in nat-lab

nat-lab/tests/test_lana.py
Sometimes the 10s interval causes the pings to be sent at exactly the time when the upgrade is happening and this causes some ping packets to be lost. This in turns causes tests to fail, since we expect no packet loss in the validators.
=> Set rtt_interval to 3 minutes (previously it was 10s)

Cargo.lock, crates/telio-wg/Cargo.toml
NOTE: This is a temporary version, when https://github.com/NordSecurity/wireguard-nt-rust-wrapper/pull/5 will be merged it will be updated
Current version of our wireguard-nt-rust-wrapper uses `log` crate which is incompatible with our `tracing` log. This can be fixed using adapter on the Telio side (as we did in ..), but changing logging crate to `tracing` here seems to be simpler and nicer. Another problem is lack of the last OS error in some of the errors returned.
Move wireguard-nt-rust-wrapper to a new version, which uses `tracing` log, and returns errors with last OS error included
=> [LLT-5479] Use new win native wg adapter

.unreleased/LLT-5574, src/ffi.rs
The rustls-platform-verifer init procedure crashes on the Android app
It turns out that JVM passes one more argument to this function thus the signature is incorrect
=> [LLT-5574] Fix rustls-platform-verifer init procedure for Android

nat-lab/run_local.py
Running natlab locally with run_local.py and building libtelio from it, requires atleast 16GBs of RAM. Which would fail if it was run from within `default` natlab VM, which has only 4GBs of RAM.
Adding a warning, so people won't get confused why this is happening.
=> Add warning to run_local.py script

crates/telio-lana/src/lib.rs, crates/telio-nurse/src/nurse.rs
Sometimes test verifying that restarting libtelio results in the same meshnet ID fails. Those logs hopefully will help in tracking down the reason for those failures.
=> Add logs to make it clear when libtelio is fetching lana entries in uninitialized state

.unreleased/LLT-5553, Cargo.lock, clis/teliod/Cargo.toml, clis/teliod/README.md, clis/teliod/example_teliod_config.json, clis/teliod/src/comms.rs, clis/teliod/src/config.rs, clis/teliod/src/core_api.rs, clis/teliod/src/main.rs, clis/teliod/src/nc.rs, nat-lab/data/teliod/config.json, nat-lab/tests/test_teliod.py
To run a meshnet App for OpenWRT a thin cli layer on top of telio library is to be designed. This wrapper would call the Core API which is normally done by the Apps
Add support to call Core API to register and update device, get meshmap.
=> Core API suport for teliod

crates/telio-wg/src/wg.rs, src/device.rs
Analysis of `test_event_link_state_peer_goes_offline` failure suggests that event generation happened in rust code but was not visible on the python side.
To make sure that nothing is blocking events processing, new separate thread is started only for that purpose. To 
to make sure that the event was indeed generated, new debug log is added.
=> Spawn event callback calling task loop on a separate thread

nat-lab/tests/utils/command_grepper.py, nat-lab/tests/utils/network_switcher/network_switcher_windows.py
During tests, sometimes `netsh show addresses` hangs and `CommandGrepper` is either stuck or silencing errors.
Add more logs to `CommandGrepper` and increase timeout value.
=> Add more logs to command grepper

nat-lab/tests/utils/connection/connection.py, nat-lab/tests/utils/connection/docker_connection.py, nat-lab/tests/utils/connection/ssh_connection.py, nat-lab/tests/utils/ping.py, nat-lab/tests/utils/process/docker_process.py
It's not always easy to map from the ping packet in the pcap to the test log.
Tag each ping packet sent from tests with a random bytes to make it easy to map back from pcap to test log. In case of the docker connections, `KILL_ID` is used as the random string.
=> Tag each ping in nat lab with random payload

nat-lab/tests/telio.py, nat-lab/tests/test_direct_connection.py
Direct connection test fails, as some nodes can report direct events, before we fully downgrade to relayed connections
Because python futures are eagerly executed, we should not collect
events for two different steps at the same time.
Moved relay and direct event gathering after a change in network
configurations, and only after each step is confirmed
=> Fix direct connection wait

nat-lab/tests/test_wg_adapter.py
When we kill the python process and immediately after exit the scope, it's possible that the cleanup of objects created in the scope races with the 'death' of the libtelio_remote.py. If the remote dies fast enough it can generate connection refused error on our side.
=> Handle ConnectionRefusedError gracefully

crates/telio-dns/src/forward.rs, src/device/wg_controller.rs
Session keeper is constantly spamming logs when VPN is connected. Lower the verbosity to Debug, which is normally not enabled in prod.
=> Lower session keeper and DNS logging verbocity

.unreleased/LLT-5770, Cargo.lock, Cargo.toml
rustls crashes when the default crypto provider is not defined
Use one of the rustls crate features (`ring`) to define the default crypto provider.
According to https://docs.rs/rustls/latest/rustls/index.html#crate-features defining `ring` feature and NOT defining `custom-provider` is enough to implicitly use the ring provider without the need to install it manually.
=> Fix rustls crash on TLS connection

.github/workflows/gitlab.yml, .gitlab-ci.yml, ci/build_libtelio.py, nat-lab/run_local.py
The set of packages that are built at the same time is split into two groups. One containing only `teliod` and the other containing the rest. This way the peak memory usage drops from ~12 gigs down to less than 8 (this might increase the compilation duration, or not - your mileage may vary).
To enable this new behaviour set the environment variable `NATLAB_REDUCE_PARALLEL_LINKERS=1`.
=> Reduce the number of parallel linkers started by build_libtelio.py

nat-lab/vm_nat.sh
This should make it clean what the actual state of routing is.
=> Print routing information when enabling/disabling vm nat

crates/telio-traversal/src/endpoint_providers/upnp.rs, nat-lab/bin/kill_process_by_natlab_id, nat-lab/tests/mesh_api.py, nat-lab/tests/test_upnp_connection.py, nat-lab/tests/utils/router/linux_router.py
Sometimes upnp module managed to run periodic code that recreates mappings in between the `upnpd` restart and `upnpc` call that verifies no mappings are present.
All calls to `kill` or `killall` now wait for the process to terminate. After that change there is no need to for the above assertion - we know that we have restarted the `upnpd`.
=> LLT-5618 wait for kills

.github/workflows/gitlab.yml, .gitlab-ci.yml, nat-lab/natlab.py, nat-lab/tests/conftest.py
- no macos logs
- poor macos vm provision
- bump libtelio-build version with new macos vm provision
- move dmesg host logs collection to before and after pytest
- add macos system and dmesg logs
=> bump libtelio build version and save macos system logs

clis/teliod/.gitignore, clis/teliod/README.md, clis/teliod/src/command_listener.rs, clis/teliod/src/daemon.rs, clis/teliod/src/main.rs, crates/telio-model/src/mesh.rs, nat-lab/tests/test_teliod.py
`teliod` is envisioned as rather headless daemon, which is expected to operate in places where there are no direct human interaction. But in some cases one may need to retrieve current state of meshnet, online/offline status of nodes etc.
This PR adds a channel for returning results as `CommandResponse` back from `telio_task` that processes`TelioTaskCmd`s, and a `CommandListener` that handles commands from the client and passes it back the `CommandResponse` result.
Additionally this PR:
- Refactor `daemon_event_loop()` to exit sooner in case `telio_task()` fails with an error.
- Move error type definitions to `error.rs`
- Move daemon specific code to `daemon.rs`
=> [LLT-5565] teliod status reporting

.unreleased/LLT-5785, crates/telio-traversal/src/batcher.rs
Batcher had no checks against interval and threshold. This allows for API misuse, for example setting too much of a threshold(so the action would be always batched) or too short interval(so it would always fire).
This PR adds some checks and unit tests, also refactored existing tests to reduce boilerplate.
It can be proved that half the interval threshold is enough and this PR adds a check that it should not be higher than that. Description in the code.
=> LLT-5785-batcher-argument-constraints

.github/workflows/gitlab.yml, .gitlab-ci.yml, nat-lab/tests/test_cleanup.py
Bump libtelio build to v2.6.2
test_cleanup.py was changed, due to removal of additional controller from windows VM, which was accidenatlly introduced by disabling `qemu-guest-agent` in previous version (causing libvirt to automatically add one more controller for host and guest communication).
So initally it was 5 devices, with v2.6.1 another device appeared, increasing number to 6, but with v2.6.2 it is again removed, returning back to 5 devices.
=> Bump libtelio build to v2.6.2

.github/workflows/linters.yml
Autoflake lists each file having no problems
which makes it difficult to see what actually failed.
Add quiet flag to only output what is wrong
=> Supress autoflake output

.github/workflows/gitlab.yml, .gitlab-ci.yml, ci/build_libtelio.py, ci/moose_utils.py
To fully integrate `moose` to `qnap` (and other embedded platforms), we have to integrate moose-worker, as well have a static build of `libsqlite3`.
Moose integration was postponed, so building qnap without `--moose` option.
=> Disable moose option for qnap build

Cargo.lock
[RUSTSEC-2024-0399](https://rustsec.org/advisories/RUSTSEC-2024-0399.html)
Update rustls to 0.23.18
=> Update rustls to 0.23.18 which fixes RUSTSEC-2024-0399

build.rs
Instead of using artifact file from installation script check if git-secrets tool is installed, that llt-secrets are added as a provider and that the hooks in the repo are enabled.
=> Change process of detecting llt-secrets hook

nat-lab/tests/conftest.py, nat-lab/tests/test_lana.py, nat-lab/tests/utils/analytics/event_loader.py, nat-lab/tests/utils/connection/connection.py, nat-lab/tests/utils/connection/docker_connection.py, nat-lab/tests/utils/connection/ssh_connection.py, nat-lab/tests/utils/process/docker_process.py, nat-lab/tests/utils/process/process.py, nat-lab/tests/utils/process/ssh_process.py, nat-lab/tests/utils/vm/mac_vm_util.py, nat-lab/tests/utils/vm/windows_vm_util.py
It's not always clear if/when/why a process crashed on mac vm in nat-lab.
Collect diagnostic reports from mac vm which contain crashes.
=> Collect DiagnosticReports from Mac VM after all test are completed

crates/telio-model/src/features.rs, crates/telio-traversal/src/batcher.rs, crates/telio-traversal/src/session_keeper.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_batching.py, nat-lab/tests/test_direct_connection.py, src/device.rs, src/device/wg_controller.rs, src/libtelio.udl
Introduce network activity based trigger to batcher.
Make DynamicWg have `subscribe_to_network_activity` that returns a tokio watch receiver channel to observe the traffic changes. Traffic changes are global WireGuard traffic changes towards and from any peer.
Since the goal is to steer the alignment of batched actions(network activities) between the peers, it's not necessary to be selective per-peer and a global approach should work.
---
No new feature flag introduced, it is enabled alongside batcher. So far no practical results can be observed in natlab cases I tried as it's overshadowed by other things doing network activity, so this is an improvement based on assumptions and RFC at this point.
=> Network activity triggered batcher

.github/workflows/gitlab.yml, .gitlab-ci.yml
Mac vm fails to start due to fail of creating network interfaces
in v2.6.6 libtelio build issue was potentially fixed by changing network interface models from `e1000` to `vmxnet3`
=> bump libtelio build to v2.6.6

nat-lab/tests/helpers.py, nat-lab/tests/mesh_api.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_events.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_network_switch.py, nat-lab/tests/test_pmtu.py, nat-lab/tests/test_pq.py, nat-lab/tests/test_vpn.py
VPN containres are being overprepared for every container/every node on every test. This is excessive, 
This PR introduces an indicator whether VPN containers are needed in `setup_environment()` and skips VPN container preparation when not needed. What is more, it only prepares containers in setup_environment once instead of doing it for every node separately.
=> Prepare VPN containers only whenever needed

nat-lab/tests/conftest.py, nat-lab/tests/utils/vm/mac_vm_util.py, nat-lab/tests/utils/vm/windows_vm_util.py
re-enabling vm nat on every test spams too much logs
enable vm nat once per pytest session
=> Enable VM nat once during pytest session

nat-lab/tests/uniffi/libtelio_proxy.py
During shutdown via RPC, ConnectionRefusedError may happen naturally. Do not panic in case of this error.
=> [LLT-5824] When shutting down natlab's telio-proxy, allow ConnectionRefusedError

crates/telio-traversal/src/session_keeper.rs, src/device/wg_controller.rs
Overwrite SessionKeeper entry on Proxy->Direct upgrade
There is a bug when batching is enabled and peer is upgraded
from Proxying to Direct. The issue exists because
entry to SessionKeeper is added initially, however
once the upgrade happens, it is not updated.
Given the scenario where one of the peer is offline and then comes
online after a delay it results in SessionKeeper not emitting ping
when upgrading from relayed to direct connection.
The ping, however, must be done in order to provide a NAT(wg) mapping
and both peers must do that to establish a mapping.
Additionally this breaks alignment of keepalives between
both peers since the upgrade process is highly synchronized, thus
if both libtelio SessionKeeper instances emit at the same time,
they are aligned and work well for battery. …
=> Overwrite SessionKeeper entry on Proxy->Direct upgrade

crates/telio-traversal/src/endpoint_providers/upnp.rs, nat-lab/data/upnpd/upnpd.conf, nat-lab/docker-compose.yml, nat-lab/tests/test_upnp_connection.py, src/device.rs
UPNP lease is not renewed when battery optimizations are turned on and UPNP endpoint provider is paused.
Ignore battery optimizations when it't time (at least 75% of the whole lease duration) to renew the lease.
=> LLL-5772 handle upnp lease expiry when battery optimizations are on

.unreleased/LLT-5801, Cargo.lock, crates/telio-sockets/Cargo.toml, crates/telio-sockets/src/protector/apple.rs, src/device.rs
With PR 601 a regression was introduced, where interfaces being listed for binding selection would not depend not on OS preference order provided by `nw_path_monitor()`, but basically on `getifaddrs()` function. And getifaddrs generally does not guarantee any preference ordering.
This PR rolls back telio-sockets apple protector to the old state. 
libtelio v4.3.5 is a "known good" protector state, this PR reverts back to it. You may verify it by running `git diff v4.3.5 crates/telio-sockets/src/protector/apple.rs`. Note that, in comparison to v4.3.5, due to name clash of `PATH_CHANGE_BROADCAST` in previous variant of apple socket protector and current version of `telio-network-monitor` -> it has been renamed to `PROTECTOR_PATH_CHANGE_BROADCAST`. and empty `set_fwmark()` method added. What …
=> [LLT-5801] Fix incorrect os preference order for network interfaces on apple

crates/telio-starcast/src/nat.rs
Nat-lab test fail then testing multicast, with
UnexpectedTransportProtocol error
Adding additional logging to investigate this issue.
=> Add aditional logging for unexpected packets

nat-lab/tests/helpers.py, nat-lab/tests/test_connection_states.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_dns_through_exit.py, nat-lab/tests/test_events.py, nat-lab/tests/test_fire_connecting_event.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_mesh_plus_vpn.py, nat-lab/tests/test_mesh_remove_node.py, nat-lab/tests/test_node_state_flickering.py, nat-lab/tests/test_pinging.py, nat-lab/tests/test_pmtu.py, nat-lab/tests/test_pq.py, nat-lab/tests/test_reconnections.py, nat-lab/tests/test_telio_version_compatibility.py, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/connection_tracker.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/dns.py
`test_dns_duplicate_requests_on_multiple_forward_servers` is sometimes failing. Seems like the test was written long time ago, when conntracker was not yet widly used. As starting various captures and then verifying results is generally race-condition-prone practice, the first agreed upon step is to convert the test to use conntracker, which already have sync points helping to reduce likelyhood of any race conditions. 
What is more, the assertion is rather strange, the DNS should not issue the same query to multiple servers, but assertion verifies whether one, the other or both servers are being used, which is strictly asserting, that on succesfull DNS query any DNS servers have been reached, which is not really useful assertion. This PR strictens the assertion a little bit, to make sure …
=> [LLT-5771] update telio dns test to rely on conntrack instead of tcpdump

crates/telio-traversal/src/endpoint_providers/upnp.rs
As can be seen here:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=051502d4fa626f2a1615bfd06d589ec9
using duration max with instants can lead to overflows. Instead lets use a duration that is long enough that in practice is 'indistinguishable' from infinity.
=> Fix 'overflow when adding duration to instant' error in upnp

ci/build_libtelio.py
On https://github.com/NordSecurity/libtelio/pull/981 `unset_cargo_dependencies()` function was mistakenly removed.
Readd it back so that when building without `--moose` flag, moose dependencies get removed.
=> fix: Readd unset moose dependencies

crates/telio-traversal/src/session_keeper.rs, src/device/wg_controller.rs
Reverts NordSecurity/libtelio#992
The fix was incomplete: it rather rewrote entries in SessionKeeper no matter what when iterating through `update_keys` so it fixed the alignment issue when upgrading from Proxying to Direct, however now will excessively overwrite those. Need a better solution
=> Revert "Overwrite SessionKeeper entry on Proxy->Direct upgrade"

Cargo.lock, Cargo.toml, crates/telio-utils/Cargo.toml, crates/telio-utils/src/backtrace.rs, crates/telio-utils/src/lib.rs, src/ffi.rs
Only the inner most backtrace frame is printed when we handle panic
Print whole backtrace (on debug level) when panic happens. Also re-enable integer overflow checks in debug builds.
=> Print backtrace on panic

.gitignore, qnap/package_routines, qnap/shared/NordSecMeshnet.sh, qnap/shared/teliod.cfg, qnap/shared/teliod.cgi
This PR introduces a cgi script that the QNAP web UI can execute in order to manage the `teliod` daemon process.
Note: Configuration update and authentication features are going to be tackled in a future PR.
=> [LLT-5811] qnap: Add cgi script handling REST API

crates/telio-network-monitors/src/linux.rs
It was failing with:
range end index 4294836240 out of range for slice of length 1444
It seems we don't need dummy struct to wait for this socket to be ready. It's enough to try to read any bytes from it. In such situation it seems that recv returns each time network interface appears (or disappear).
=> Fix crash in neli (netlink library)

clis/teliod/src/daemon.rs
`teliod` does not specify direct connections.
Adds a helper function that creates default Features and enables direct connections.
=> [LLT-5834] Add direct connections to teliod features

Cargo.lock, crates/telio-dns/Cargo.toml, deny.toml
This will fix CI lint failures that complain about vulnerability in pre 1.0 idna versions.
=> Update trust-dns to 3.0.1 (which includes update of idna to 1.0.0)

.github/workflows/linters.yml, .gitignore, Justfile
There are many shorter and longer commands that we (sometimes) want to also run locally. Most of them are long enough that I don't remember them and have to pull them out of shell history or even worse from CI config.
Use [just](https://just.systems/) to automate this. `Just` is a recent rewrite/replacement for make. You can run it like that:
```
$ just # will run the default 'test' / 'cargo test...' command
$ just clippy # will run the clippy target
$ just d # will run the 'deny' target' (cargo deny check) using the 'd' alias
```
Second commits replaces our CI jobs which started those various commands directly, with `just` invocations so that we can easily keep them in sync with what we run locally.
=> Automate day to day rust development tasks with Just(file)

nat-lab/bin/core-api.py, nat-lab/bin/mqtt-listener.py, nat-lab/data/core_api/rumqttd.toml, nat-lab/docker-compose.yml, nat-lab/tests/helpers.py, nat-lab/tests/test_core_api.py, nat-lab/tests/test_notification_center.py
In the ESP32 mesh network (meshnet) integration tests within the nat-lab environment, the v1/notifications/token endpoint must be supported by the nat-lab CoreApi to provide essential connection details for the MQTT message broker. This endpoint requires Basic authentication for access control, while all other CoreApi endpoints use Bearer token authentication.
1) Implement `v1/notifications/token` Endpoint: Add the `v1/notifications/token` endpoint to provide connection details for the MQTT broker, based on the specifications outlined in the `v1/notifications/token` documentation.
2) Enable Basic Authentication for `v1/notifications/token`: Add Basic authentication support for the `v1/notifications/token` endpoint. Additionally, create and add test user accounts to validate …
=> [LLT-5604] Notifications token support in CoreApi

.github/workflows/linters.yml, Justfile
This makes it possible to for example, run black with `$ just black`.
=> Use justfile to run black and pylint linters

nat-lab/tests/test_notification_center.py
`test_nc_registered` failed over the weekend with the pytest `Timeout` exception.
Add additional logging for MQTT listener process inside the test to be able to understand the root cause of the failure.
=> Add additional logging for MQTT listener

crates/telio-firewall/src/firewall.rs, crates/telio-model/src/features.rs, nat-lab/tests/test_dns_through_exit.py, nat-lab/tests/test_events.py, nat-lab/tests/test_features_builder.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_mesh_exit_through_peer.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/bindings.py, src/ffi/defaults_builder.rs, src/libtelio.udl
Merging https://github.com/NordSecurity/libtelio/pull/529 created a problem in builds because of backward compatibility in ffi signature `enable_reset_boringtun_conns` which was changed to `enable_firewall`.
This PR fixes reverts and fixes the issue.
=> Revert to old signature in firewall

nat-lab/tests/telio.py, nat-lab/tests/test_batching.py, nat-lab/tests/test_derp_connect.py, src/device.rs, src/device/wg_controller.rs
Batching relies on Sessionkeeper(is baked into it) which is not present when direct feature is disabled or if SessionKeeper::start fails.
This breaks cases where batching is enabled but direct feature is not for VPN reestablishment for example(added testcases fail on `main`). This is a limitation of the decision to keep SessionKeeper instead of introducing a separate entity for batching.
The fix is to override the batching feature when either SessionKeeper or Direct are None which is done here.
However I did an extra step and moved SessionKeeper outside the Direct entities as I think it doesn't belong there anymore due to being repurposed for more stuff(vpn, proxy, stun keepalives when batching, derp keepalives in progress). This moving out provided very minimal changes, though the diff …
=> Detach batcher and direct feature

nat-lab/tests/utils/connection_tracker.py
FiveTuple from connection tracker, when printed would produce the following output:
```
In nlx_1 there has been 3 connections to <class 'utils.connection_tracker.FiveTuple'> which is more then max limit of 2
```
Obviously `<class 'utils.connection_Tracker.FiveTuple>` is not desirable, hence this PR adds `def __str__` implementation to the class.
This is the result:
=> Fix FiveTuple printing

.github/workflows/gitlab.yml, .gitlab-ci.yml
This adds the changes to the macos provisioning so that it doesn't download software updates.
=> Update trigger reference to v2.7.2

nat-lab/Pipfile, nat-lab/Pipfile.lock, nat-lab/tests/test_events.py, nat-lab/tests/utils/bindings.py
node diff wasnt clear
make node diff more clear by introducing deepdiff
Mini test to show differences in output:
```python
def test_diff():
alpha = telio_node(
identifier="alpha-id",
public_key="alpha-pub",
state=NodeState.CONNECTED,
ip_addresses=["1.1.1.1"],
allowed_ips=["1.1.1.1/32"],
nickname="alpha",
hostname="alpha.nord",
allow_incoming_connections=True,
allow_peer_send_files=True,
path=PathType.DIRECT,
)
beta = telio_node(
identifier="alpha-id",
public_key="alpha-pub",
state=NodeState.CONNECTED,
ip_addresses=["1.1.1.1"],
allowed_ips=["1.1.1.1/32"],
nickname="alpha",
hostname="alpha.nord",
allow_incoming_connections=True,
allow_peer_send_files=True,
path=PathType.DIRECT,
)
assert node_diff(alpha, beta) is None
beta.identifier = "beta-id"
assert node_diff(alpha, beta) is None
``` …
=> Make node diff more readable

nat-lab/tests/conftest.py
There is no point in running tests when networking is broken
Check that VMs can reach each other, and also at least one selected docker host.
=> Check that the VMs can ping each other

build.rs, crates/telio-lana/build.rs
For lana, this script is self contained so it should explicitly depend only on itself. For toplevel, we don't need to check changes in crates and src if the bypass is in place.
After this change, subsequent invocations of `run_local.py` or `build.sh`, will not rebuild/relink anything if there are no changes.
=> Make sure that build scripts use rerun-if-changed in a correct way

.github/workflows/gitlab.yml, .gitlab-ci.yml
qnap build job didn't have architecture in the name which cause the release pipeline to file when trying to download prebuilt qnap artifacts.
add a matrix build with one architecture for qnap
=> Update triggered-ref to v2.7.3 which adds ARCH to qnap build job name

.unreleased/LLT-5639, crates/telio-model/src/features.rs, crates/telio-relay/src/derp.rs, crates/telio-relay/src/derp/http.rs, nat-lab/tests/test_derp_connect.py, src/libtelio.udl
This PR adds DERP userspace keepalive to libtelio. (Unbatched for now)
=> Add DERP userspace keepalives

crates/telio-model/src/features.rs, crates/telio-relay/src/derp.rs, src/libtelio.udl
`pool_keepalive` was made a required field. This is causing failures in unaligned clients (the fact that it has a default serde value in the json doesn't help).
Make the field optional in the udl.
=> Make pollKeepalive optional

clis/teliod/example_teliod_config.json, clis/teliod/src/config.rs, clis/teliod/src/core_api.rs, clis/teliod/src/daemon.rs, clis/teliod/src/nc.rs, nat-lab/data/teliod/config.json
Currently `app_user_id` used for notification center is part of the user provided config for teliod. It shouldn’t be user configurable, we can reuse the the meshnet `hardware_id` for it instead which should be generated when the device is registered.
Remove `app_user_uid` from the user config.
Use a randomly generated UUID instead of the public key for `hw_identifier`.
Use the `hw_identifier` as `app_user_uid` in notification center.
=> LLT-5866: Remove app_user_uid from the config.

Cargo.lock
Updating crates.io index
Updating git repository `https://github.com/NordSecurity/trust-dns.git`
Updating git repository `https://github.com/NordSecurity/neptun.git`
Updating git repository `https://github.com/NordSecurity/wireguard-nt-rust-wrapper`
Updating git repository `https://github.com/NordSecurity/rust-dispatch.git`
Updating git repository `https://github.com/NordSecurity/system-configuration-rs.git`
Updating git repository `https://github.com/NordSecurity/nat-detect.git`
Updating git repository `https://github.com/NordSecurity/rust-igd.git`
Updating git repository `https://github.com/NordSecurity/uniffi-rs.git`
Updating addr2line v0.24.1 -> v0.24.2
Updating anstyle v1.0.8 -> v1.0.10
Updating anyhow v1.0.89 -> v1.0.95
Updating async-io v2.3.4 -> v2.4.0
Updating async-trait v0.1.83 …
=> Update dependencies on 7.01.25

Cargo.lock
Darwin runners fail after the update of this crate which is a transient dependency, this is a manual patch that will not need any action further(cargo update will just update it again).
There's outstanding PR which claims to fix the issue: https://github.com/rustpq/pqcrypto/pull/72
The error in question from compilation:
```
cargo:warning=<instantiation>:79:5: error: instruction requires: sha3
```
=> Manually revert back pqcrypto-internals to 0.2.5

.github/workflows/linters.yml, .gitignore, Justfile, nat-lab/bin/cleanup_natlab_processes, nat-lab/bin/derp-server, nat-lab/bin/dns-server.sh, nat-lab/docker-compose.yml, nat-lab/tests/config.py, nat-lab/tests/conftest.py, nat-lab/tests/helpers.py, nat-lab/tests/mesh_api.py, nat-lab/tests/telio.py, nat-lab/tests/utils/connection/connection.py, nat-lab/tests/utils/connection/docker_connection.py, nat-lab/tests/utils/connection/ssh_connection.py, nat-lab/tests/utils/connection_util.py, nat-lab/tests/utils/process/docker_process.py, nat-lab/tests/utils/process/process.py, nat-lab/tests/utils/process/ssh_process.py, nat-lab/tests/utils/tcpdump.py, nat-lab/tests/utils/vm/mac_vm_util.py, nat-lab/tests/utils/vm/windows_vm_util.py
- add multi-OS tcpdump wrapper
- add `DO_NOT_KILL` prefix to process kill_id, so it won't be killed during cleanup before each test
- make dns-server pcaps session wide
- unify `GITLAB_CI` usage between code, previously was `GITLAB_CI` and `CUSTOM_ENV_GITLAB_CI`
- add Connection name to Process, so errors would be more clear
=> add tcpdump wrapper

.unreleased/LLT-5884, Cargo.lock, crates/telio-pq/Cargo.toml, crates/telio-pq/src/entity.rs, nat-lab/tests/test_pq.py, src/device.rs, src/device/wg_controller.rs
If a client is connected to PQ VPN and then doesn't do a new handshake within wireguard's 180s reject connection timeout (can happen for example during nonet), the client would not be able to establish a new handshake since it's supplying a preshared key even though the server doesn't expect one, leading to a broken VPN connection
If postquantum is active and time since last handshake exceeds wireguards reject threshold (in `uapi::Peer::time_since_last_handshake` this is represented as `None`), restart postquantum
=> LLT-5884: PQ VPN breaks after some time of nonet

Justfile, nat-lab/tests/test_batching.py, nat-lab/tests/utils/tcpdump.py
windump might be causing issues for windows vms and make tests fail
temporary disable windump
=> Temporary disable tcpdump for windows

Cargo.lock, Cargo.toml, crates/telio-wg/src/adapter/neptun.rs, nat-lab/tests/telio.py, nat-lab/tests/test_start_with_tun.py, nat-lab/tests/uniffi/libtelio_proxy.py, nat-lab/tests/uniffi/libtelio_remote.py, nat-lab/tests/utils/router/linux_router.py, nat-lab/tests/utils/router/mac_router.py, nat-lab/tests/utils/router/router.py, nat-lab/tests/utils/router/windows_router.py
`start_with_tun` ffi function wasn't being tested and thus contained bugs on platforms which weren't using that function in production.  
Added a nat-lab test for `start_with_tun` function and fixed multiple bugs found on the way.
=> Add nat-lab test for starting telio with an existing tunnel

.github/workflows/build.yml, .github/workflows/linters.yml, .github/workflows/scorecard.yml, .github/workflows/tests.yml
download-artifact and upload-artifact actions v3.x.x were depecrated.
Bump versions both actions versions to v4.x.x.
see: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Bump depecrated actions version

.github/workflows/build.yml
With https://github.com/NordSecurity/libtelio/pull/1065, artifacts with duplicated names are no longer uploaded for each PR.
Distinguish artifact names from each job.
=> ci: Avoid artifacts conflicting names

.unreleased/LLT-5886_protected_pinger, Cargo.lock, Cargo.toml, crates/telio-nurse/Cargo.toml, crates/telio-nurse/src/nurse.rs, crates/telio-nurse/src/qos.rs, crates/telio-pinger/Cargo.toml, crates/telio-pinger/src/lib.rs, crates/telio-sockets/Cargo.toml, crates/telio-sockets/src/protector.rs, crates/telio-sockets/src/socket_pool.rs, crates/telio-utils/Cargo.toml, crates/telio-utils/src/lib.rs, crates/telio-wg/Cargo.toml, crates/telio-wg/src/link_detection.rs, crates/telio-wg/src/link_detection/enhanced_detection.rs, crates/telio-wg/src/wg.rs, src/device.rs
Due to the nature of Apple's NetworkExtension control protocol, packets originating from the NetworkExtension process are routed outside of the tunnel. 
Because of this on macOS AppStore and iOS platforms, raw ICMP packets from QoS RTT and Link detection components destined for the tunnel interface, leave the main interface instead.
Use the `SocketPool` component in order to bind the ping raw socket to the tunnel interface. The Pinger component had to moved into it's own crate in order to avoid circular dependencies between Utils and Sockets.
LinkDetection component was also updated to use the new Pinger.
=> LLT-5886: Protected RTT QoS pings

nat-lab/tests/conftest.py
During the last nat-lab run, the `setup_check_connectivity` failed while attempting to establish connectivity between the MAC VM and the Windows VM.  However, the exception message was empty, making it difficult to identify the root cause of the failure.
Add more verbose exception messages.
=> Improve exception message in setup_check_connectivity

nat-lab/tests/test_events.py, src/device.rs
Sleeps in testcases cause flakyness. This PR removes one instance of it.
Eliminate sleep from `test_event_content_meshnet` testcase. Also add additional log line just before calling event callback from libtelio since telio and natlab logs show 4sec difference in the logs:
**Telio**:
```
2025-01-19 18:19:48.950786 TelioLogLevel.DEBUG 2025-01-19T18:19:48.9503876Z ThreadId(3) "telio::device":2403 Event is being published to libtelio integrators Node { public_key: "wuNG...vG8=", state: Connected, ...
```
**NatLab**:
```
[alpha]: event [2025-01-19 18:19:52.958807]: Event.NODE(body=TelioNode(public_key=wuNGlTQiOB26qsAhM5Fw/vP3afIP55bBRA1YETjZvG8=, state=NodeState.CONNECTED,
```
=> LLT-5950: test event content meshnet sleep to event

nat-lab/tests/test_wg_adapter.py
Pyro5 wraps ConnectionRefusedError into Pyro5.errors.CommunicationError. The reason why the test is flaky is that sometimes ProcessExecError is raised instaed of Pyro exception. That depends on the order of events in the async event loop.
=> Fix test_wg_adapter_cleanup

.github/workflows/gitlab.yml, .gitlab-ci.yml, nat-lab/tests/test_cleanup.py
We recently changed the network model for the windows VMs for natlab, which makes a test fail because the adapter is different
Update the test
=> LLT-5939: Fix test after windows VM provisioning fix

.github/workflows/gitlab.yml, .gitlab-ci.yml
Windows provision script fails in natlab tests.
Remove running provision script in natlab, and let precondition checks handle that. Libtelio-build has already been updated for that.
=> bump libtelio-build to without windows provision script

.unreleased/LLT-5892, Cargo.lock, crates/telio-model/src/features.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_events_link_state.py, src/device.rs, src/ffi/defaults_builder.rs, src/libtelio.udl
Current WireGuard polling mechanism is inefficient and thus slowing down connection times for VPN.
Connection times can be sped up by speeding up polling period after an update had been made to WireGuard.
Implements RFC LLT-0083.
=> Add faster WG polling after update

Cargo.lock, crates/telio-dns/Cargo.toml
dns tests fail in nat-lab. Root cause isn't known yet and it is a bit difficult to pinpoint the problem.
Sprinkle logs in trust-dns and hopefully that would help narrow the problem.
This would be a temp bump to get to the root cause of dns test failing
=> bump trust-dns version

nat-lab/tests/utils/command_grepper.py, nat-lab/tests/utils/router/windows_router.py
Windows tests fail sometimes by not reporting any
IP which is set without errors. Experimentation
revealed that the device might not have been
in a `Connected` state, so we enforce that.
=> Wait for interface to report Connected state

nat-lab/tests/test_dns.py
Dns tests sometimes fail. It might be possible that the issue is not on our end, but on neptun's end.
To test out that theory, adding linux native adaptor in the dns tests as well. When the tests fail again, and if they fail only on neptun that confirms the theory. Otherwise back to the drawing board.
=> Add linux native adapter in dns tests

nat-lab/tests/uniffi/libtelio_proxy.py
We observe that sometimes Pyro delays events reported but still reports them and we suspect something around communication between natlab and the node itself
which is done with Pyro.
This commit adds more information to aid debugging
=> More Pyro logs around event logging

crates/telio-pq/src/entity.rs, nat-lab/tests/test_pq.py
There was a potential race condition in our PQ restart logic that could cause restart to be called erroneously before the initial handshake was performed. The decision on whether to restart PQ was done based on the time since last handshake, as reported by the wireguard interface. The problem was that wireguard will uses None to represent both the case where no handshake has been performed and the case where a connection has been rejected after 180 seconds, so our PQ restart logic would incorrectly trigger if there was a wg consolidation happening between PQ peer being added and a handshake happening
Now there's an additional timestamp in the PQ entity to help guide if PQ should be restarted
=> LLT-5935: Only restart PQ if there was actually a previous handshake

nat-lab/tests/test_dns.py, nat-lab/tests/utils/dns.py
1. Print nslookup output in nat-lab
2. Increase timeout of nslookups that fail so we can see if at some point
they get unstuck but fail the test manually if the lookup took more then
the second so we can still see those failures in the nightly runs.
=> nat-lab investigation

ci/build_libtelio.py
Qnap's QDK builds packages depending on the project directory structure, given that `x86_64` folder was always present, it conflicted with other builds.
Create arch directory during build.
=> LLT-5985: qnap: Fix missing aarch64 teliod binary

nat-lab/tests/test_events.py
Timeouts can be undeterministic, especially when we use VMs, since they are not as lightweight and might cause delays.
In test_event_content_meshnet case we observed constantly that Windows peer fails to receive the event in a timely manner. It is delayed by several seconds sometimes.
Why is that it's not entirely clear, and packet capture is not present on Windows at this point. Maybe it's due to same interface being used for libtelio and natlab and TCP retransmissions are to blame for retries that might cause delays.
As an easy solution, the timeout is being removed to see if it helps.
=> Remove timeout when waiting for disconnected event

crates/telio-pq/src/entity.rs, nat-lab/tests/test_pq.py, src/device/wg_controller.rs
NepTUN is behaving differently from the other wireguard implementations in that NepTUN will report time since last handshake as `None` after 180 seconds (wireguard `REJECT-AFTER-TIME` value) whereas the other implementations keep reporting an actual time. The fix we added before assumes that the time since last handshake is `None` after 180s and therefore doesn't work with other adapter types 
1. Parameterize the regression test so we know it works with all adapter types
2. We added a timestamp since last handshake to the PQ entity, let's base the restart decision purely on that timestamp instead
=> LLT-5989: Fix PQ restart for other adapter types

Cargo.lock, Cargo.toml, clis/derpcli/src/conf.rs, clis/derpcli/src/main.rs, clis/interderpcli/Cargo.toml, clis/tcli/Cargo.toml, clis/tcli/src/bin/tclid/coms.rs, clis/tcli/src/bin/tclid/daemon.rs, clis/teliod/Cargo.toml, clis/teliod/src/nc.rs, crates/telio-crypto/Cargo.toml, crates/telio-crypto/src/lib.rs, crates/telio-firewall/src/firewall.rs, crates/telio-lana/Cargo.toml, crates/telio-network-monitors/Cargo.toml, crates/telio-network-monitors/src/local_interfaces.rs, crates/telio-network-monitors/src/monitor.rs, crates/telio-nurse/Cargo.toml, crates/telio-nurse/src/heartbeat.rs, crates/telio-pq/Cargo.toml, crates/telio-pq/src/proto.rs, crates/telio-relay/Cargo.toml, crates/telio-relay/src/derp.rs, crates/telio-relay/src/derp/http.rs, crates/telio-sockets/Cargo.toml, crates/telio-traversal/src/endpoint_providers/local.rs, crates/telio-utils/src/lru_cache.rs, crates/telio-wg/src/windows/service.rs, src/ffi.rs, src/lib.rs
=> Update libtelio dependencies

.github/workflows/changelog.yml, .github/workflows/ci.yml, .github/workflows/dod.yml
While implementing the merge queue I've discovered that our CI has a bug. This is caused by jobs marked as skipped. When we have a workflow that is triggerd on both push and pull_reqeust events and then the trigger job that is responsible for cancelling duplicated CI runs on our internal pull requests, GH is treating cancelled job as successful in its 'requred checks' logic which protects branches from merging PRs with failing CI. So in the situation where we push a change that fails the skipped jobs are reported first and the actual runs are reported few minutes later when they actually finish. This creates the window during which the checks are considered successful.
There is also a second bug. check-all-green job was not marked to run 'always' This is a problem because in case any of …
=> Do not run our CI on push to branch

crates/telio-pq/src/entity.rs, nat-lab/tests/test_pq.py
PQ needs to be restarted if more than 180s pass since last handshake, but for this purpose a successful rekey is also considered a handshake, which was not taking into consideration, which meant that 180s after a connection was established, PQ would erroneously be restarted
Reset PQ handshake timestamp on successful rekey
=> LLT-5996: Reset PQ handshake ts on successful rekey

nat-lab/tests/test_lana.py
Revert back moose db timeout in natlab to 60s
Additionally, measure how long does it take to fetch moose db
=> Revert back moose db timeout in natlab to 60s

nat-lab/tests/telio.py
`wait_for_log` has an option to be case insensitive (which is the default) in which case it will convert your search string to lowercase, but it always converts the log to lower case. So if you were to pass `case_insensitive=False` and a search string that's not just lowercase letters, you would never get a hit. The reason we haven't seen it happen so far is that no callsite is passing `case_insensitive=False`
Convert log to lowercase only if  `case_insensitive` is `True`
=> Fix wait_for_log case sensitivity

.github/workflows/tests.yml, Cargo.lock, crates/telio-utils/Cargo.toml, crates/telio-utils/src/lib.rs, crates/telio-utils/src/utils.rs, src/ffi/logging.rs, tests/logger.rs
Add granular timestamps to logs
There is a suspicion that our logs can lock from time to time.
Currently the timestamp in our logs comes from the very end of log
processing right before sending it to the writer thread which executes
application callback. To check if we do not have any locking inside
logging machinery on call site let's add two timestamps to our logs. One
directly from the call site and second in formatter. Third is already
there and comes from writter as explained above.
This is a temporary commit meant to be reverted once we have results.
=> logging timestamps

crates/telio-test/src/lib.rs
Bumped from 100ms to 500ms. This fixes flakyness in `wait_with_session_start_until_stun_server_wg_peer_is_available` on macos.
=> Allow for more time in await_timout for tests

nat-lab/tests/test_direct_connection.py, nat-lab/tests/test_dns.py, nat-lab/tests/test_lana.py, nat-lab/tests/test_network_monitor.py, nat-lab/tests/test_pinging.py, nat-lab/tests/test_pq.py, nat-lab/tests/test_telio_tasks.py, nat-lab/tests/uniffi/libtelio_remote.py
We have a suspicion that writing to logs is blocking a thread that causes DNS queries to sometimes be delayed. 
Temporarily disable logs completely to see if the errors go away.
Note: This will be reverted in 2-3 days, but until then we're not going to be able to debug other test issues
=> Temporarily disable logs to see if dns tests stop failing

Cargo.lock, Cargo.toml, clis/tcli/src/bin/tcli.rs
The default level when RUST_LOG is empty or not present, is DEBUG.
=> Add support for RUST_LOG for tcli

.github/workflows/linters.yml
`unused-features` job was disabled unintentionally on https://github.com/NordSecurity/libtelio/pull/1014.
Reenable it.
=> ci: Reenable unused-features linter job

Cargo.lock, Cargo.toml, clis/derpcli/Cargo.toml, clis/derpcli/src/conf.rs, clis/interderpcli/Cargo.toml, clis/tcli/src/cli.rs, clis/teliod/Cargo.toml, crates/telio-model/Cargo.toml, crates/telio-network-monitors/Cargo.toml, crates/telio-relay/Cargo.toml, crates/telio-traversal/Cargo.toml, crates/telio-wg/Cargo.toml
Cargo dependencies are out of date
Updated the dependencies and refactored some of the code that had braking changes.
- Migrated `clap` from version 3.x to 4.x.
- Bumped minor versions, that didn't have braking changes.
=> Bump cargo dependency versions

.unreleased/LLT-5683, nat-lab/tests/telio.py, nat-lab/tests/test_events_link_state.py
Previously the link state testcase scenarios were structured like setup, do some interaction between peers, sleep for a while and check the reported link states. This approach did not consider the timings of the events.
Proposed solution consists in checking the state constantly during the scenario, not only at the end of it.
=> LLT-5683: Increase constrains in link state testcases

.github/workflows/gitlab.yml, .gitlab-ci.yml
Vagrantfile in libtelio-build has provisioning script with audit logs disabled. They are found to be
the root cause of most IO on `default` VM. Not a
guarantee this will fix anything though.
=> Point to libtelio-build with audit logs disabled

Justfile
Latest rustup release (1.28.0) broke / changed behaviour regarding implicit installing of toolchains specified in the toolchain file.
See for details: https://github.com/rust-lang/rustup/issues/4211#issuecomment-2695620307
=> Install also toolchain from toolchain-file when running unused lint

.github/workflows/dod.yml
Ubuntu 20.04 is being deprecated by github.
https://github.com/actions/runner-images/issues/11101
Update the workflow Ubuntu version.
=> Bump check-dod Ubuntu version

nat-lab/tests/utils/multicast.py
Test `test_multicast_disallowed` is occasionally failing.
Reduce multicast client timeout so that it always fails before the server.
=> Reduce MulticastClient timeout

.github/workflows/gitlab.yml, .gitlab-ci.yml
Bump libtelio-build reference to v2.9.0.
Enables downloading artifacts from main for GitHub scheduled pipelines (nightlies) instead of building it for each pipeline. 
=> Bump libtelio-build reference to v2.9.0

nat-lab/tests/conftest.py, nat-lab/tests/test_multicast_connection.py, nat-lab/tests/utils/connection_util.py
Ephemeral ports setup takes about 5 seconds, it is being done on every test for every node and that's not required.
Do the ephemeral ports setup only when a new connection is created instead.
=> natlab: Setup ephemeral ports only when needed

ci/insert_libtelio_version.py
Currently libtelio is the only LLT library we use which is provided with code signing. This is causing a problem following adoption of Framework wrapped-dylibs, because the code signing is setting an identity on the dylib binary which is being preserved throughout the later build pipeline which conflicts with the Framework identity
Remove code signing in libtelio
=> Remove Apple code signing

Cargo.lock, crates/telio-nurse/src/qos.rs, crates/telio-pinger/Cargo.toml, crates/telio-pinger/src/lib.rs, crates/telio-traversal/Cargo.toml, crates/telio-traversal/src/session_keeper.rs, crates/telio-wg/src/link_detection/enhanced_detection.rs
There is some logic duplicated between SessionKeeper and `Pinger` component used by QoS and LinkDetection
- SessionKeeper is refactored to use the same `Pinger` component.
- A new method `send_ping` is added to issue a "fire and forget" ping as used by SessionKeeper. LinkDetection is also migrated to issue a "fire and forget" ping as it doesn't require to wait for a reply.
- `perform` renamed to `perform_rtt` to make it more explicit.
- `module_name` field added to aid in debugging the module that sent the pings. In debug builds this is also added as ICMP data to be more easily traceable in packet captures.
=> LLT-5886: Protected pinger refactoring

clis/teliod/README.md, clis/teliod/example_teliod_config.json, clis/teliod/src/cgi/api.rs, clis/teliod/src/config.rs, clis/teliod/src/daemon.rs, clis/teliod/src/logging.rs, clis/teliod/src/main.rs, nat-lab/data/teliod/config.json
Logs generated by teliod can, over time, fill up the filesystem.
Keep the logs from last `log_file_count` (default 7) days.
=> Add daily log rotation for the teliod

.unreleased/LLT-6041-pq-restart-instant, crates/telio-pq/src/entity.rs
Instant does not give any guarantees when it comes to whether it counts time that elapsed during the system sleep. Because we need to measure real passage of time in PQ restart logic let's use SystemTime instead.
=> Use SystemTime instead of Instant in PQ restart

.unreleased/LLT-5972_configure_windows_adapter_according_to_needs, crates/telio-dns/src/dns.rs, crates/telio-dns/src/nameserver.rs, crates/telio-dns/tests/nameserver.rs, crates/telio-proxy/src/proxy.rs, crates/telio-starcast/src/starcast_peer.rs, crates/telio-wg/src/adapter/windows_native_wg.rs, nat-lab/tests/test_adapter.py, nat-lab/tests/utils/command_grepper.py, nat-lab/tests/utils/router/windows_router.py, src/device.rs, src/device/wg_controller.rs
It may be beneficial to show the adapter as "disconnected" or "down" in case it is idling in libtelio. This is especially useful if one keeps it preconfigured for potential use in the future, as adapter configuration can sometimes take seconds. For this reason this PR adds a logic which makes sure that adapter is down if there are no peers requested for WG and brings it up when peers are added. 
There is RFC LLT-0089 for more details.
Now in order to finalize the PR there had to be a few changes to other places.
Previously we have been configuring windows adapter IP address with standard `netsh` command and later waiting until the IP address is actually set, Unfortunately due to a fact that this operation now is operating on "disconnected" adapter before any feature is turned on - the …
=> [LLT-5972] Control Up/Down state of WG-NT adapter according to presence of peers.

crates/telio-wg/src/adapter/windows_native_wg.rs, crates/telio-wg/src/windows/tunnel/interfacewatcher.rs, nat-lab/tests/test_events_link_state.py, nat-lab/tests/utils/connection/docker_connection.py, nat-lab/tests/utils/connection/ssh_connection.py
Async contexts must define `__aexit__` method, but it matters what we return out of it. According to [PEP 492](https://peps.python.org/pep-0492/#new-syntax) the `__atexit__` usage is equivalent to this
```python
mgr = (EXPR)
aexit = type(mgr).__aexit__
aenter = type(mgr).__aenter__
VAR = await aenter(mgr)
try:
BLOCK
except:
if not await aexit(mgr, *sys.exc_info()):
raise
else:
await aexit(mgr, None, None, None)
```
In case of exception -> we need to return something that would evaluate to `False`, or otherwise we will loose exceptions. Omiting `return` statement altogether - is equivalent to `return None` which evaluates to `False`.
This PR fixes `__aexit__` implementation according to that.
=> Fix nat-lab test exception handling

.unreleased/LLT-6086, crates/telio-model/src/features.rs, crates/telio-wg/src/adapter.rs, crates/telio-wg/src/adapter/linux_native_wg.rs, crates/telio-wg/src/adapter/windows_native_wg.rs, crates/telio-wg/src/wg.rs, crates/telio-wg/src/windows/tunnel/interfacewatcher.rs, nat-lab/tests/test_adapter.py, nat-lab/tests/test_events_link_state.py, nat-lab/tests/utils/bindings.py, src/device.rs, src/ffi/defaults_builder.rs, src/libtelio.udl
Windows adapter control based on RFC LLT-0089 was missing feature flag. This PR adds it.
=> Add new feature flag for dynamic WireGuard-NT adapter control

Cargo.lock, Cargo.toml
Forward-port a fix for v5.1 and v5.2 so it can be included in v5.3 release candidates. The only change in NepTUN between v1.0.4 and v1.0.5 is changing the log level for DuplicateCounter errors
=> LLT-6071: Change DuplicateCounter log level to debug

crates/telio-network-monitors/src/monitor.rs
Network monitor keeps reporting errors that the broadcast channel lagged and thus events are being missed.
Since the channel's capacity was only 2, increased it to 10.
=> Increase network monitor broadcast channel capacity

nat-lab/pyproject.toml, nat-lab/tests/conftest.py, nat-lab/tests/telio.py, nat-lab/tests/utils/logger.py
1. Ctime is missing from the pytest report logs.
2. Expected CancelledError exceptions are being unnecessarily logged.
3. A few log messages were unintentionally removed.
1. Add Ctime to every log handler.
2. Remove logging of client request loop exception.
3. Add missing log messages.
=> Fix natlab logger issues

nat-lab/tests/test_dns.py
Linux native tests were added when investigating dns test failures, to check whether issue is in neptun. The issue wasn't in neptun.
Remove extra linux native tests
=> Remove redundant dns tests

clis/teliod/src/cgi/mod.rs
Web UI is being served to unauthenticated users. This gives unauthorized access to nord access token and meshnet information.
Authenticate the user before handling any request.
=> qnap: Do authentication before handling any request

Cargo.lock
=> Fix RUSTSEC-2025-0024 by updating crossbeam-channel to 0.5.15

.unreleased/is_link_up_is_always_false_before_first_received_packet, crates/telio-utils/src/bytes_and_timestamps.rs
In the last week's change to link state detection there was a bug for the case before receiving first ever packet. In that case, we should always report that the link is down.
=> Link can't be up before the first received packet

.unreleased/NMACOS-8047, crates/telio-sockets/src/protector/apple.rs
When [includeAllNetworks](https://developer.apple.com/documentation/networkextension/nevpnprotocol/includeallnetworks) parameter is set, and the user changes the network interface (e.g. connects/disconnects Ethernet cable to a mac) we end up in a no-net situation. When `includeAllNetworks` flag is set we cannot call the `bind` method too soon, as the system will block the traffic
The solution to this problem is to call `bind` method as soon as the new network interface is fully reconfigured. This brings the challenge of knowing when this has happened. I tried to find some indication in `nw_path_monitor` or in the DynamicStore, unfortunately, I didn't find a single indicator that would say it is 100% safe to rebind the sockets.
I settled on a solution to observe 2 keys in the DynamicStore: …
=> Improve socket rebinding on Apple platforms

.unreleased/LLT-5790, Cargo.lock, crates/telio-wg/Cargo.toml
wg-nt spams logs a lot.
Highest log level in wg-nt is info, so change it to debug on interception to avoid spamming on prod builds.
=> LLT-5790 Bump wg-nt-rust-wrapper

crates/telio-traversal/src/endpoint_providers/stun.rs
Apps requested to reduce the log level for STUN session start errors
This commit changes their log level to `warn`
=> [LLT-5846] Reduce STUN session start fail to warn

.unreleased/LLT-6095, Cargo.lock, Cargo.toml, crates/telio-model/src/features.rs, crates/telio-wg/src/adapter.rs, crates/telio-wg/src/adapter/neptun.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_events_link_state.py, nat-lab/tests/test_neptun.py, nat-lab/tests/utils/bindings.py, src/device.rs, src/ffi/defaults_builder.rs, src/libtelio.udl
Tests done by Android team showed that modifying SO_SND and SO_RECV gives a big boost in speed, hence a need to be able to modify buffer sizes.
Add socket buffer size as a feature to be configurable by upstream Apps.
Tests regarding socket buffer sizes have been added in NepTUN. Corresponding NepTUN merged PR
https://github.com/NordSecurity/NepTUN/pull/29. for reference.
=> Add feature to modify SO buffer size in neptun

nat-lab/tests/test_derp_connect.py
When we restart derp server, race condition appears. Server can be started faster than we actually connect to any other server, therefore, connecting to same derp server again.
Shutdown derp server, connect to other derp server and then bring back previous derp server
=> Fix derp restart test race condition

clis/teliod/README.md, clis/teliod/example_teliod_config.json, clis/teliod/src/cgi/api.rs, clis/teliod/src/config.rs, clis/teliod/src/daemon.rs, crates/telio-wg/src/adapter.rs, nat-lab/data/teliod/config.json, qnap/shared/teliod.cfg
During PoC is was reviled that NepTun did not work with OpenWRT. It was required to use native implementation, but the adapter type is hard coded in `teliod`.
Add `adapter_type` field to the config, and pass it on when creating the device.
=> LLT-6137: teliod configurable adapter type

.unreleased/misc_natlab_improvements, crates/telio-wg/src/link_detection.rs, nat-lab/tests/conftest.py, nat-lab/tests/helpers.py, nat-lab/tests/telio.py, nat-lab/tests/test_events_link_state.py, nat-lab/tests/utils/command_grepper.py, nat-lab/tests/utils/connection/ssh_connection.py, nat-lab/tests/utils/connection_tracker.py, nat-lab/tests/utils/network_switcher/network_switcher_windows.py, nat-lab/tests/utils/process/docker_process.py, nat-lab/tests/utils/process/ssh_process.py, nat-lab/tests/utils/router/linux_router.py, nat-lab/tests/utils/router/mac_router.py, nat-lab/tests/utils/router/router.py, nat-lab/tests/utils/router/windows_router.py, nat-lab/tests/utils/vm/mac_vm_util.py
Fixes:
- Libvirt VMs routing was being configured only when binaries were pushed, this PR configures it as default for every new ssh connection.
- Exceptions on docker/ssh processes were not being raised against the context manager of the cleanup stage, making  pytest hang for the whole test timeout duration. This PR fixes it by running the processes inside a try/except/finally block.
- If telio fails to launch won't set the client proxy port, creating an infinite loop waiting for the port. This PR fixes it by additionally checking if the telio process is running.
- Other logging and duplicated code minor fixes.
Features:
- This PR adds link state check as part of the setup_mesh_nodes() helper function.
- Add enable/disable interface methods to router classes.
=> natlab: Misc improvements

.github/workflows/gitlab.yml, .gitlab-ci.yml, nat-lab/docker-compose.yml, nat-lab/natlab.py
This PR bumps the libtelio build tag that embbeds a docker version update to v28.x that has a stricter nat policy for the bridge network drivers ([changes](https://github.com/moby/moby/pull/48724)). By default it drops all the packets going to unpublished ports, disabling for instance  libvirt <-> docker communication.
To accept traffic from the libvirt VMs, 'nat-unprotected' mode is set to the network drivers of their gateways to the "nat-lab internet": `cone-gw-03` and `cone-gw-04` ([see](https://github.com/NordSecurity/libtelio/blob/main/nat-lab/vm_nat.sh#L30)).
See: [Docker v28 release notes ](https://docs.docker.com/engine/release-notes/28/#networking-4)
=> ci: Bump libtelio build tag

nat-lab/tests/utils/connection/connection.py
When running nat-lab, sometimes wireguard got assigned a random port from the ephemeral port range that clashed with the port hardcoded for the starcast (13569). This is because we are overriding ephemeral port range in tests to avoid clashes between tests run on the same machine.
Increase minimal ephemeral port range start so that it's greater than the starcast port.
=> Increase the start of ephemeral port range in nat-lab

.github/workflows/nagger.yml, .unreleased/LLT-6057, Cargo.lock, Justfile, clis/teliod/src/nc.rs, crates/telio-model/src/config.rs, crates/telio-nurse/src/aggregator.rs, crates/telio-nurse/src/heartbeat.rs, crates/telio-nurse/src/qos.rs, crates/telio-pq/src/conn.rs, crates/telio-relay/src/derp/http.rs, crates/telio-traversal/src/connectivity_check.rs, crates/telio-traversal/src/connectivity_check/cross_ping_check.rs, crates/telio-traversal/src/endpoint_providers/upnp.rs, crates/telio-traversal/src/upgrade_sync.rs, crates/telio-utils/Cargo.toml, crates/telio-utils/src/bytes_and_timestamps.rs, crates/telio-utils/src/instant.rs, crates/telio-utils/src/interval.rs, crates/telio-utils/src/lib.rs, crates/telio-utils/src/lru_cache.rs, crates/telio-utils/src/repeated_actions.rs, crates/telio-utils/src/tokio.rs, crates/telio-wg/src/link_detection.rs, crates/telio-wg/src/uapi.rs, crates/telio-wg/src/wg.rs, crates/telio-wg/src/windows/service.rs, src/device.rs, src/device/wg_controller.rs, src/ffi/logging.rs
Both `std::time::Instant` and `tokio::time::Instant` do not track the time spent by the operating system in suspend mode. This can lead to telio not reacting in time to various events or timeouts.
Add a custom suspend-aware replacement `Instant` implementation. The key points:
- most of the work is done by already existing create `boot_time` which is used in release builds
- in debug builds, this new `Instant` is using `tokio::time::Instant` which means that time suspending used in rust tests is still working and can be used
- `boot_time` crate doesn't compile for Linux 32bit systems, which is why for now we use our own fork with a fix for those platform
- this PR only tackles time measurement, notifications via `tokio::time::Interval` are left unchanged - this might be fixed in a future …
=> Implement suspend-aware replacement for `tokio::time::Instant`

.github/workflows/gh-pages.yml
gh-pages job is still using rust v1.79 and we have packages which require higher versions. Version is adjusted here to match one defined in `build-docs-on-mac` job.
=> Update rust toolchain for gh-pages job

ci/fetch_artifacts.py
`unzip=False` was removed from `_get_artifacts ` hence `self._get_artifacts(job, unzip=True)` usage causing an error.
=> Fix _get_artifacts usage

.github/workflows/linters.yml, Justfile
Clippy for teliod started failing after some toolchain changes
Changed the `just clippy` recipe to run for custom packages with an optional argument `just clippy teliod`
=> ci: fix clippy for teliod

crates/telio-firewall/Cargo.toml, crates/telio-firewall/benches/firewall_bench.rs, crates/telio-firewall/src/firewall.rs, crates/telio-model/src/features.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_features_builder.py, nat-lab/tests/test_vpn.py, src/device.rs, src/libtelio.udl
Add firewall blacklist for outgoing packets that can be configured via feature config
=> LLT-6113 Drop blacklisted packets in firewall

clis/teliod/src/cgi/api.rs, clis/teliod/src/cgi/app.rs, clis/teliod/src/cgi/web.rs
Upon receiving POST request, after toggling
the daemon, now the result of it is transferred
back to the page so the user would get the feedback.
It's not very granular at the moment but at least it is
explicit about telling that something has failed instead
of just staying silent(refreshes the page but meshnet doesn't
turn on).
Below is the screenshot when incorrect token was entered and
meshnet was toggled:
=> Introduce failure feedback in QNAP UI

clis/teliod/src/cgi/app.rs, clis/teliod/src/cgi/mod.rs, clis/teliod/src/cgi/qnap.rs, clis/teliod/src/cgi/web.rs, clis/teliod/src/command_listener.rs, clis/teliod/src/config.rs, clis/teliod/src/core_api.rs, clis/teliod/src/daemon.rs, clis/teliod/src/main.rs, clis/teliod/src/nc.rs
Wrap token into Hidden<String>
In teliod the auth token should never appear in a
plaintext form exept for debug builds for security
reasons so it wouldn't be emitted by accident or logged.
Each place storing a token as String is replaced with
Hidden<String> which prints itself as `****` unless it's in
debug mode.
Signed-off-by: Lukas Pukenis <lukas.pukenis@nordsec.com>
=> Wrap token into Hidden<String>

.unreleased/LLT-6195-optional-thread-id-in-logs, crates/telio-model/src/features.rs, nat-lab/tests/utils/bindings.py, src/device.rs, src/device/wg_controller.rs, src/ffi.rs, src/ffi/defaults_builder.rs, src/ffi/logging.rs, src/libtelio.udl, tests/logger.rs
Additionaly, dropped `"` characters surrounding module path.
=> By default hide thread IDs in logs

Cargo.lock, Cargo.toml, crates/telio-wg/Cargo.toml, crates/telio-wg/src/adapter/windows_native_wg.rs
wireguard-nt sometimes fails to start for unknown reason
add some logs to list out registry where network driver lays
=> add more debug logs for wireguard nt

.unreleased/LLT-6122-reject-blacklisted-packets-in-firewall, Cargo.lock, Cargo.toml, crates/telio-dns/src/nameserver.rs, crates/telio-dns/tests/nameserver.rs, crates/telio-firewall/benches/firewall_bench.rs, crates/telio-firewall/src/firewall.rs, crates/telio-pq/src/proto.rs, crates/telio-starcast/src/starcast_peer.rs, crates/telio-wg/src/adapter.rs, crates/telio-wg/src/adapter/neptun.rs, crates/telio-wg/src/lib.rs, crates/telio-wg/src/wg.rs, nat-lab/tests/test_vpn.py, src/device.rs
Instead of dropping blacklisted packets in telio-firewall reject UDP
packets with ICMP destination unreachable and UDP packets with TCP_RST.
=> LLT-6122 Reject blacklisted packets in firewall

.github/workflows/linters.yml, .github/workflows/tests.yml, Justfile, clis/teliod/src/cgi/api.rs, clis/teliod/src/cgi/qnap.rs
Some parts of teliod are under feature flags like `cgi` and `qnap`, and CI is not linting everything
Add linting and tests to CI for `teliod` `cgi`
=> Clippy and Tests for teliod cgi

Cargo.lock, clis/teliod/Cargo.toml, clis/teliod/README.md, clis/teliod/example_teliod_config.json, clis/teliod/src/cgi/api.rs, clis/teliod/src/command_listener.rs, clis/teliod/src/comms.rs, clis/teliod/src/config.rs, clis/teliod/src/core_api.rs, clis/teliod/src/daemon.rs, clis/teliod/src/main.rs, nat-lab/data/teliod/config.json, nat-lab/tests/test_teliod.py, qnap/shared/NordSecurityMeshnet.sh
According to the [daemon](https://linux.die.net/man/1/daemonize) convention, a daemon should detach itself from the terminal, disassociate from its process group and run in the background.
Use `daemonize` crate to detach the daemon process, set umask, change process group, and redirect stdout and stderr to a file.
The daemon process needs to be forked before starting the `tokio` runtime, otherwise it panics.
`teliod daemon` command was replaced with `teliod start` to make it more semantically correct.
`--no-detach` flag was added to run teliod attached to the terminal as a regular process.
Added a `--stdout-path` parameter to specify where to redirect stdout and stderr.
Added a `--working-directory` parameter to specify which working directory the daemon should use.
The unix socket mode …
=> LLT-6123: Teliod daemonize

qnap/shared/NordSecurityMeshnet.sh
Config file after installing NordSecurityMeshnet
gets owned by `root` user with 0777 permissions and
`teliod` is later executed with `admin` user.
Changing the permissions is needed as 0777 is too lax,
but 0600 doesn't work since a different user accesses it.
As a resut 0660 is chosen
=> Change teliod config file permissions to 0660 on qnap

Justfile
When developing on macOS, CGI server can only be run through a VM, but it only accepts connections from localhost. 
CGI Server accepts connections from any address.
=> Just web httpd accept any address

.github/workflows/diagram.yml
Restrict GITHUB_TOKEN permissions for diagram workflow
=> Restrict token permissions for diagram to read-only

Cargo.lock, clis/teliod/API.md, clis/teliod/Cargo.toml, clis/teliod/src/cgi/api.rs, clis/teliod/src/cgi/constants.rs, clis/teliod/src/cgi/web.rs, clis/teliod/src/config.rs, qnap/shared/NordSecurityMeshnet.sh, qnap/shared/teliod.cfg
`teliod` now daemonizes itself, so we don't have to send the process to the background manually.
Update CGI and QNAP scripts launching `teliod` to make use of it daemonizing itself.
`get_teliod_logs` endpoint was rename to `get_logs` and now it returns combined logs from all the sources.
`MESHNET_LOG` and `get_meshnet_logs` were removed as they were not used anywhere.
STDOUT and STDERR before daemonizing is redirected to `TELIOD_INIT_LOG` (`/var/log/teliod_init.log`).
STDOUT and STDERR after daemonizing is redirected to `TELIOD_STDOUT_LOG` (`/var/log/teliod_stdout.log`).
`libtelio` and `teliod` tracing logs are directed to `TELIOD_LIB_LOG` (`/var/log/teliod_lib.log`) and are rotated daily. 
Therefore `get_logs()` was updated to handle the `teliod_lib.log.YYYY_MM_DD` files, and …
=> LLT-6123: Teliod daemonize CGI

clis/teliod/src/command_listener.rs, clis/teliod/src/daemon.rs
Client commands like `get-status` and `is-alive` get constantly polled by the CGI, resulting in repeated log entries, potentially filling up space.
Reduce the log level from `info` to `debug`
=> Reduce log level of teliod client commands

clis/teliod/src/cgi/web.rs, qnap/qpkg.cfg
NordSecurityMeshnet is opened in another browser tab instead of the built-in QNAP desktop environment.
QNAP has ability to open applications in an iframe which can be easily done by tweaking the configuration parameter.
It eventually lands in /etc/config/qpkg.conf
with `Desktop = 1` written to it.
=> In QNAP open Meshnet in the same Window

clis/teliod/src/cgi/constants.rs, clis/teliod/src/cgi/web.rs, qnap/shared/NordSecurityMeshnet.sh
Meshnet is being started at the start of QNAP regardless if user has started it previously or not. This means that if user enters a valid token, starts meshnet and then stops it and machine restart happens - meshnet will automatically turn on even though it should stay off.
In CGI handler we save user's intent by creating a file and then check for it in
NordSecurityMeshnet.sh when starting.
=> Persist teliod daemon state using a marker file

Cargo.lock, clis/teliod/Cargo.toml, clis/teliod/src/config.rs, clis/teliod/src/main.rs
When a relative path is given as `log_file_path`, the validation tries to convert it to an absolute path.
Since most likely the file does not yet exist, `canonicalize()` will fail with error `Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })`
Properly convert the path to absolute, by splitting file name and directory parts, and canonicalize only the parent directory.
Add more descriptive error message.
=> Fix teliod log path validation

crates/telio-sockets/src/protector/apple.rs
Backport of https://github.com/NordSecurity/libtelio/pull/1275 to release v5.3
=> NMACOS-8047 - Backport v5.3

.unreleased/LLT-6394, crates/telio-model/src/config.rs, src/ffi.rs
Deserializing configs return very opaque errors upon failure, which makes it hard for apps to find the cause. 
When the deserialization fails, emit debug log
=> LLT-6394: Emit debug log when meshnet or feature config can't be deserialized

crates/telio-firewall/src/conntrack.rs, crates/telio-firewall/src/firewall.rs, crates/telio-firewall/src/lib.rs
Conntracker can be reused in chain-based firewall and thus should be extracted from firewall code.
Moved conntracker code to a separate module.
=> [LLT-6204] Extract conntracker to a separate mod

crates/telio-wg/src/windows/tunnel/mtumonitor.rs
Previous code as a bare subtraction 'mtu - 80' which can overflow
Instead, let's do a saturating subtraction
=> Prevent overflow in mtumonitor

clis/tcli/src/cli.rs, clis/teliod/src/daemon.rs, crates/telio-dns/src/bind_tun.rs, crates/telio-dns/src/dns.rs, crates/telio-wg/src/adapter.rs, crates/telio-wg/src/adapter/linux_native_wg.rs, crates/telio-wg/src/adapter/neptun.rs, crates/telio-wg/src/adapter/windows_native_wg.rs, crates/telio-wg/src/wg.rs, src/device.rs, src/device/wg_controller.rs, src/doc/introduction.md, src/ffi.rs
Before (#1273) a bug was introduced which caused nat-lab test start_with_tun to sometimes fail. This was later reverted (in #1287). The source of the problem was that the `OwnedFd` which was part of the `Config` was dropped after the underlying descriptor was passed to NepTUN - which meant the descriptor was closed.
Instead of passing config by reference, and dropping it (and contained `tun`) afterwards, this PR changes the `start` (and `set_tun`) so that it consumes the `OwnedFd` using `IntoRawFd` and pass it to NepTUN for management.
=> Replace raw fd with ownedfd for tunnel descriptor

.unreleased/LLT-6394, crates/telio-model/src/config.rs, src/ffi.rs
This is a backport of https://github.com/NordSecurity/libtelio/pull/1309
=> Backport: emit debug log when meshnet or feature config can't be deserialized

nat-lab/tests/test_connection_tracker.py, nat-lab/tests/test_mesh_firewall.py, nat-lab/tests/test_vpn.py, nat-lab/tests/utils/connection_tracker.py
This PR implements action points from today's nat-lab meeting:
- prefix all conntacker logs with some unique id
- rename wait() funciton in conntracker, so it wouldn't be mixed up with asyncio.Event().wait() -> [code](https://github.com/NordSecurity/libtelio/blob/9095db6e8c657f4f267451da994e96141c451f8f/nat-lab/tests/utils/connection_tracker.py#L370)
- print what can be recover [here](https://github.com/NordSecurity/libtelio/blob/9095db6e8c657f4f267451da994e96141c451f8f/nat-lab/tests/utils/connection_tracker.py#L381)
=> Improve debuggability of connection tracking

crates/telio-firewall/src/conntrack.rs, crates/telio-firewall/src/firewall.rs
Previously there was very little actually testing of the conntracker state outside of the sanity checks in benchmarks - which turns out cough an issue: https://github.com/NordSecurity/libtelio/actions/runs/15852903485/job/44690771436?pr=1324#step:3:499
Also, there was no tests for the handling of vpn peer in the rust tests and also no test to check how the firewall behaves with different values for the `record_whitelisted` property.
The state is checked using get_state in various tests that can impact it for both possible values of `record_whitelisted`. Also, a test for vpn peer handling has been added.
=> Add tests for firewall that excercise previously untested configuration or state

.gitignore, clis/tcli/src/cli.rs, clis/teliod/README.md, clis/teliod/src/cgi/api.rs, clis/teliod/src/comms.rs, clis/teliod/src/config.rs, clis/teliod/src/configure_interface.rs, clis/teliod/src/core_api.rs, clis/teliod/src/daemon.rs, clis/teliod/src/nc.rs, crates/telio-model/src/config.rs, crates/telio-sockets/src/protector/linux.rs, crates/telio-utils/src/lib.rs, nat-lab/bin/core-api.py, nat-lab/data/teliod/config_with_vpn.json, nat-lab/tests/config.py, nat-lab/tests/mesh_api.py, nat-lab/tests/test_core_api.py, nat-lab/tests/test_teliod.py
`teliod` now needs to be able to connect to VPN and this is a first version.
The config is updated to allow passing the ip and public key of a server to connect to. Future updates would likely include more user-friendly options, but for this PR, this is how you connect to VPN.
Routing information is updated but only for the existing configuration options (`ip` and `ifconfig`). Basic routing is set up, along with disabling IPv6.
=> LLT-6139: Implement VPN functionality for teliod

nat-lab/tests/conftest.py
We've seen some failures in natlab where binaries could not be copied to some VMs because the connection failed. 
We already have precondition checks for connectivity between VMs and those have retries already set up. By moving the copying of binaries to after those connectivity checks have been done, we reduce the risk of the failed connection happening during the copying of binaries
=> Move copying of binaries to after connectivity checks

clis/teliod/README.md, clis/teliod/src/configure_interface.rs
For the OpenWRT there is a native command [UCI](https://openwrt.org/docs/techref/uci) (Unified Configuration Interface), which should be used to configure networks.
Add `InterfaceConfigurationProvider` implementation for `UCI`
Rename `adapter_name` to `interface_name` for consistency.
=> LLT-6138: Add UCI support to teliod

crates/telio-utils/Cargo.toml, crates/telio-utils/src/log_censor.rs
We have a couple of feature config options that are only there for us to use during development, like hide_user_info and hide_thread_id. These feature config options that are not active in production builds can give a bad impression to our users if they are spotted in the logs.
Hide those options from the logs
=> LLT-6386: Censor feature config options from logs

.github/workflows/gitlab.yml, .github/workflows/gitlab_schedule.yml
Sometimes `authorize-and-resolve-workflow-ref` workflow jobs [failing](https://github.com/NordSecurity/libtelio/actions/runs/16310405037/job/46064879188#step:3:68) with error:
`HTTPError: 403 Client Error: rate limit exceeded for url: ...`
Due to that some of the nightlies pipelines are not getting triggered.
Make authenticated requests in get-workflow-action which increases the rate limit. 
Corresponding MR in trigger-gitlab-pipeline will be merged after the testing on nightlies for one week.
=> Bump trigger gitlab pipeline version

clis/teliod/src/configure_interface.rs, clis/teliod/src/daemon.rs
OpenWRT platforms are using UCI commands to configure routes and firewall zones.
Add UCI implementation for setting up VPN functionality. Disabling IPv6 and preserving LAN access between devices.
=> LLT-6138: Add VPN support to UCI

README.md
As a first time user while following README.md I was looking for a directory `tcli-test` in which I was supposed to create `docker` subfolder inside, but the `tcli-test` directory also has to be created.
Make the README.md super clear about making both directories.
=> Add mkdir and cd to readme

nat-lab/pyproject.toml, nat-lab/tests/teliod.py, nat-lab/tests/test_teliod.py, nat-lab/tests/utils/router/linux_router.py, nat-lab/uv.lock
Teliod natlab tests contains significant boilerplate and duplicated logic for starting, stopping, and interacting with the teliod daemon.
This PR refactors the teliod test suite by introducing a dedicated abstraction (Teliod, Config, and supporting classes) which encapsulates all process management, configuration, daemon lifecycle, log handling, and socket logic.
It centralizes teliod test logic, reducing boilerplate, improving maintainability and preparing the suite for easier future extension.
=> [LLT-6404] natlab: Abstract teliod to its own module

nat-lab/tests/test_vpn.py, nat-lab/tests/utils/connection_tracker.py
test_firewall_blacklist_tcp nat-lab test fails because TcpState CLOSE comes immediately after TIME_WAIT and we just check for last 3 events upto TIME_WAIT
Add optional to check whether events above the last event match the event sequences.
=> allow trailing close in conntracker

crates/telio-wg/src/windows/tunnel/interfacewatcher.rs
Just-in-case add a nullcheck for raw pointer provided via interface_change_callback.
=> Add null check for raw pointer provided via interface_change_callback

ci/moose_utils.py
In the past build scripts were manipulating manifest files when adding or removing the moose analytics libtelio feature.
Since https://github.com/NordSecurity/libtelio/pull/1165 `moose` cargo feature is required to always exist, therefore the scripts should not touch it anymore and actually keep it regardless of whether libmoose is included or not in the libtelio build.
This PR removes that feature from the scripts.
=> build: Stop removing moose cargo feature from lana manifest

nat-lab/bin/core-api.py
Currently in register machine api (in nat-lab core-api) the `HTTPStatus.OK` is returned instead of `HTTPStatus.CREATED`
1. Return `HTTPStatus.CREATED` for `POST /v1/meshnet/machines` in nat-lab core-api
=> Return http status CREATED in nat-lab register machine api

nat-lab/docker-compose.yml, nat-lab/openwrt.Dockerfile
To be able to make https requests to nat-lab's core api the self-signed certificate should be available in OpenWrt GW container
1. Add core-api's `test.pem` certificate to OpenWrt container
Later on the daemon can be started with config which points to certificate location (tested and it works):
```
{
"log_level": "trace",
....
"http_certificate_file_path": "/etc/ssl/certs/test.pem",
....
}
```
=> [LLT-6509] Add self-signed certificate to OpenWrt container

Cargo.lock
=> Fix RUSTSEC-2025-0047 by bumping slab to 0.4.9 -> 0.4.11

crates/telio-proto/protos/ens.proto, crates/telio-proto/src/ens.rs
Small changes have been made to the proto definition. Instead of using one common `Empty` type, distinct types are used to make it easy in the future to change them.
=> Align our proto definition with latest one from RFC

nat-lab/tests/test_mesh_firewall.py
`test_mesh_firewall_tcp_stuck_in_last_ack_state_conn_kill_from_client_side` failed in a recent nightly because we were expecting conntracker events LAST_ACK, TIME_WAIT but we got TIME_WAIT, CLOSE. We know from before that occasionally, probably due to multithreading in NepTUN, the final close event might arrive early which is fine and we should allow that to happen in our tests
Allow trailing `CLOSE` in `test_mesh_firewall_tcp_stuck_in_last_ack_state_conn_kill_from_client_side`
=> Allow trailing conntracker close event in another test

Cargo.lock
`cargo deny` is failing because of a potential vulnerability in an older version of `tracing-subscriber`
Bump cargo lock to the latest versions
=> Bump cargo lock

clis/teliod/README.md, clis/teliod/example_teliod_config.json, clis/teliod/src/cgi/api.rs, clis/teliod/src/config.rs, clis/teliod/src/core_api.rs, clis/teliod/src/daemon.rs, clis/teliod/src/main.rs, nat-lab/data/teliod/config_with_vpn_country_de.json, nat-lab/data/teliod/config_with_vpn_country_pl.json, nat-lab/data/teliod/config_with_vpn_iproute_setup.json, nat-lab/data/teliod/config_with_vpn_manual_setup.json, nat-lab/tests/teliod.py, nat-lab/tests/test_core_api.py, nat-lab/tests/test_teliod.py
Initial VPN supuport in Teliod is currently designed to use a direct endpoint (ip, port, public_key) provided from the config file. This approach is not user-friendly, as end users are unlikely to know valid IPs and public keys of NordVPN servers.
To improve usability, the goal is to allow users to specify a country code (e.g., "US" or "AR") in the VPN config. Teliod will then fetch a suitable VPN server automatically using the NordVPN Core API.
`config::VpnConfig` was converted into an enum with `Server` and `Country` variants.
This enables us to maintain the previous functionality.
Config changes from:
```json
"vpn": {
"server_endpoint": "10.0.100.1:1023",
"server_pubkey": "public-key-placeholder"
}
```
to
```json
"vpn": {
"server": {
"address": "10.0.100.1",
"public_key": …
```
=> LLT-6211: Connect to VPN by country

.gitlab/merge_request_templates/Default.md, .markdownlint-cli2.yaml, PULL_REQUEST_TEMPLATE.md, nat-lab/network.md
Some files should not be included in markdown formatting/linting.
- `network.md` is autogenerated and just contains a mermaid graph
- Two different pull request templates look better in the pull request view the way they were before
Exclude those files and restore them to how they were before adding the formatter/linter
=> Exclude more files from markdown formatting

nat-lab/tests/test_mesh_firewall.py
In some tests we are asserting that conntracker has the last few events in the regular TCP lifecycle, minus `CLOSE`. In most cases this works really well, but sometimes we get a `CLOSE` event too early, which is fine, as long as it's only ever `CLOSE` and it arrives at the end and in the right order. In this case, the test should not fail
Allow trailing close in the test in question
=> Allow trailing close in mesh firewall test

build.rs
Some platforms, like maybe kepler, need the .so libs it links to have it's `SONAME` section set. We were previously doing that for android builds but not linux builds
Set the soname for linux too
=> LLT-6012: Add soname to libtelio.so on linux

nat-lab/bin/openwrt/50-set-ips.sh, nat-lab/bin/openwrt/container_net_setup.sh, nat-lab/bin/openwrt/entrypoint.sh, nat-lab/bin/openwrt/run-vm.sh, nat-lab/docker-compose.yml, nat-lab/openwrt.Dockerfile
- Set up bridging networking in container to access qemu VM outside of the container
- Add necessary VM ip and routing set-up
**Problem:**
With VM’s default -nic user mode, the VM cannot be reached directly from LAN.
It cannot forward traffic between networks so it's not possible to properly test routing or VPN passthrough.
**Solution:**
Use TAP devices and Linux bridges to connect the QEMU VM to the host’s networks:
Bridge connects the TAP device to the host network, allowing the VM to appear as if it’s physically connected to that network.
With at least two interfaces (eth0 on LAN, eth1 on WAN), the QEMU VM can forward packets between networks and act as a router/gateway.
=> Add networking to OpenWrt qemu VM

nat-lab/tests/test_teliod.py
With vagrantless natlab it seems like there's sometimes a small delay between teliod being started and logs being available. It happens in every nightly but only a couple of the pipelines there, so not super common
Loop the log check until the expected logs are there, to account for any delays
=> Loop log check in teliod test

nat-lab/tests/telio.py, nat-lab/tests/test_lana.py, nat-lab/tests/utils/moose.py
We caught an error, where `sqlite3` binary and `libmoose` accessed db file and caught a deadlock.
Offloading some of `busy_timeout` to python-side retries.
=> Fix sqlite timeout by splitting it

nat-lab/tests/utils/tcpdump.py
Intermittent races can cause tcpdump to fail to start in NAT lab.
Attempt to start the capture up to three times, logging a warning on each failure and rethrowing on the final attempt.
=> Retry tcpdump startup and scope pcap cleanup

.env, clis/nordvpnlite/openwrt/feed/net/nordvpnlite/files/config.json
Some leftovers of old name were present in OpenWRT config file(interface name, log file).
Simply rename and also bump .env to latest libtelio-build reference.
=> Rename OpenWRT config leftover to nordvpnlite
