.github/workflows/gitlab.yml
README.md

Add README badges

---

changelog.md
crates/telio-task/src/task.rs
crates/telio-traversal/src/connectivity_check/cross_ping_check.rs
crates/telio-traversal/src/endpoint_providers/stun.rs
crates/telio-traversal/src/endpoint_providers/upnp/mod.rs
src/device/mod.rs

Some spammy log messages are of too high log-level. Review and update those.

[LLT-4002] review log levels of spammy messages

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/fuzzing.yml
.github/workflows/gitlab.yml
.github/workflows/linters.yml
.github/workflows/main.yml
.github/workflows/scorecard.yml
.github/workflows/tests.yml
CODEOWNERS
README.md

LLT 3986, 3987, 3988 Improvements after security review

---

clis/tcli/src/cli.rs
crates/telio-model/src/config.rs

1. Add an option to the tcli to set an ip for the adapter
2. Add an option to the tcli to display mesh config

TCLI improvements

---

changelog.md
crates/telio-dns/src/nameserver.rs
crates/telio-dns/src/zone.rs
crates/telio-dns/tests/integration_tests.rs
crates/telio-dns/tests/nameserver.rs
src/device/mod.rs

[LLT-4008] Add support for AAAA records in telio-dns

---

crates/telio-dns/src/nameserver.rs
crates/telio-dns/src/zone.rs
crates/telio-dns/tests/integration_tests.rs
crates/telio-dns/tests/nameserver.rs
nat-lab/tests/test_dns.py
src/device/mod.rs

Added an integration test for AAAA records and made some improvements suggested by Tomasz

[LLT-4026] Integration test for AAAA records

---

CODEOWNERS

add myself to nat-lab codeowners

update codeowners for natlab

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Update gitlab pipeline version

Update gitlab pipeline version

---

changelog.md
crates/telio-model/src/api_config.rs
src/device/mod.rs
src/ffi/types.rs

Validate that the public key associated with a requested meshnet config matches the private key of the device the config will be applied to

LLT-4023: Validate meshnet config public key

---

nat-lab/tests/test_direct_connection.py
nat-lab/tests/test_upnp_connection.py
nat-lab/tests/utils/connection_util.py

Re-enable/cleanup direct connection tests on natlab.

LLT-3737: Add more upnp integrational test

---

.github/workflows/gitlab.yml
.gitignore
.gitlab-ci.yml
nat-lab/pyproject.toml
nat-lab/pytest.ini
nat-lab/requirements.txt

No problem being solved with this, just adding dep

Add pytest-html support to nat-lab

---

nat-lab/tests/test_direct_connection.py
nat-lab/tests/test_network_switch.py

Natlab Police: Xfail failed nigthly tests

---

nat-lab/tests/telio.py
nat-lab/tests/test_direct_connection.py
nat-lab/tests/test_events.py
nat-lab/tests/test_mesh_plus_vpn.py
nat-lab/tests/test_network_switch.py
nat-lab/tests/test_reconnections.py
nat-lab/tests/test_upnp_connection.py
nat-lab/tests/test_vpn.py

During nightly runs it was found a few flaky tests.
For the ones that the flakyness cause was simple enough, a fix is also provided in this PR.

Natlab police: address nightly flakyness

---

changelog.md
nat-lab/tests/test_lana_validator.py

We have validators for lana which test events, but there is no test which checks the validator itself.
Add test for lana validator

Llt 3775 lana validator tests

---

nat-lab/conftest.py
nat-lab/pyproject.toml
nat-lab/tests/mesh_api.py
nat-lab/tests/test_connection_states.py
nat-lab/tests/test_derp_client_message_forward.py
nat-lab/tests/test_derp_connect.py
nat-lab/tests/test_direct_connection.py
nat-lab/tests/test_direct_feature.py
nat-lab/tests/test_dns.py
nat-lab/tests/test_dns_through_exit.py
nat-lab/tests/test_events.py
nat-lab/tests/test_fire_connecting_event.py
nat-lab/tests/test_lana.py
nat-lab/tests/test_mesh_exit_through_peer.py
nat-lab/tests/test_mesh_firewall.py
nat-lab/tests/test_mesh_plus_vpn.py
nat-lab/tests/test_mesh_remove_node.py
nat-lab/tests/test_network_switch.py
nat-lab/tests/test_node_state_flickering.py
nat-lab/tests/test_pinger.py
nat-lab/tests/test_reconnections.py
nat-lab/tests/test_tcli.py
nat-lab/tests/test_telio_tasks.py
nat-lab/tests/test_upnp_connection.py
nat-lab/tests/test_verify_pk_on_packets.py
nat-lab/tests/utils/router/linux_router.py
nat-lab/tests/utils/router/mac_router.py
nat-lab/tests/utils/router/windows_router.py

Remove nordderper restart

---

.github/workflows/gitlab.yml
.gitlab-ci.yml
nat-lab/data/nordderper/config1.yml
nat-lab/data/nordderper/config2.yml
nat-lab/data/nordderper/config3.yml

Updates nordderper configs, so they are compliant with the new version of nordderper.
New nordderper version requires updated config files.
Update config files.

Update nordderper configs

---

.github/workflows/gitlab.yml

Version 2.0.0 supports pipeline cancellation

Update trigger-gitlab-pipeline to version v2.0.0

---

.gitignore
nat-lab/Dockerfile
nat-lab/tests/telio.py
nat-lab/tests/telio_test.py
nat-lab/tests/test_reconnections.py
nat-lab/tests/test_telio_version_compatibility.py

Add a test for telio compatibility with it older version. 
This required changing the natlab docker image.

Add telio version compatability test

---

nat-lab/tests/test_lana.py

`test_lana_with_second_node_joining_later_meshnet_id_can_change` was missing the logic of [`resolve_current_meshnet_id`](https://github.com/NordSecurity/libtelio/blob/f0d1dba72c9118529c8840b77fcbea4d3dc3dcde/crates/telio-nurse/src/heartbeat.rs#L181): when different meshnet IDs are used by the same number of nodes, it lexicographically compares the PK (in binary: base64->base2) of those nodes and chooses the smallest.
Update test assert logic.

natlab: Compare fp based on pk

---

Cargo.lock
changelog.md
crates/telio-model/Cargo.toml
crates/telio-model/src/api_config.rs
crates/telio-proto/Cargo.toml
crates/telio-proto/protos/pinger.proto
crates/telio-proto/src/packet/relayed/pinger.rs
crates/telio-traversal/src/connectivity_check/cross_ping_check.rs
crates/telio-traversal/src/endpoint_providers/local.rs
crates/telio-traversal/src/endpoint_providers/stun.rs
crates/telio-traversal/src/endpoint_providers/upnp/mod.rs
crates/telio-traversal/src/ping_pong_handler.rs
nat-lab/bin/configure_route.sh
nat-lab/bin/internal-symmetric-gw
nat-lab/docker-compose.yml
nat-lab/tests/test_direct_connection.py
nat-lab/tests/utils/connection_util.py
src/device/wg_controller.rs

Improves the way in which we use peer-reflexive endpoints, also adds tests for their usage.

LLT-3316: Improve handling peer reflexive endpoints

---

CODEOWNERS

remove gytsto from natlab owners

---

crates/telio-traversal/src/endpoint_providers/stun.rs
src/device/wg_controller.rs

WG STUN to the first server was failing because it was connecting before the server was added as a WG peer.
Sending STUN requests when STUN server is already added to wireguard peers

Fix wg-stun behavior

---

nat-lab/tests/test_direct_feature.py
src/device/mod.rs

LLT-3752: Enable upnp direct feature by default

---

.github/workflows/gitlab.yml

After disabling test-apple CI job a new tag was released.
Update libtelio-build tag.

Bump libtelio-build tag

---

nat-lab/tests/test_mesh_remove_node.py
nat-lab/tests/test_network_switch.py

Unmarked flaky test
Mark them with xfail mark

Natlab police: mark new flaky tests

---

nat-lab/tests/test_connection_states.py
nat-lab/tests/test_mesh_exit_through_peer.py

More Windows tests failed
Mark them as flaky

Natlab police: mark new flaky Windows tests

---

nat-lab/tests/utils/stun.py

There are two problems with our current STUN module:
- it is inconsistent - while on Windows and Mac we use stunman which is RFC5389 compliant, on Linux we use default Ubuntu package which is RFC3489 compliant, which is obsolete and
- our nordderper implementation requires RFC5389 compliance from the connecting STUN clients.
Instead of the default STUN Ubuntu client we can use `turnutils_stunclient` which is RFC5389 and also add a possibility of choosing STUN port, so we can use it to test nordderper.

Make stun module rfc5389 compliant

---

nat-lab/tests/utils/connection_util.py
nat-lab/tests/utils/vm/windows_vm_util.py

There's something fishy going on with Windows VM as it's randomly failing tests with no obvious reason.
Add logs so we can debug.

[LLT-4357] natlab: Add debug logs to windowsVM

---

nat-lab/tests/test_network_switch.py

Test is failing in at least once per day
Mark it with xfail

Mark test_vpn_network_switch as flaky for WindowsNativeWg

---

Cargo.lock
Cargo.toml
crates/telio-dns/Cargo.toml
crates/telio-dns/src/dns.rs
crates/telio-dns/tests/integration_tests.rs
crates/telio-dns/tests/nameserver.rs
crates/telio-proxy/Cargo.toml
crates/telio-wg/src/adapter/boring.rs
crates/telio-wg/src/adapter/linux_native_wg.rs

This only to run CI test on changes.
There are still issues with the new botringtun and dns

Update boringtun to v0.5.2

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

New version of libtelio-bulid is available. 
Use it :smiley:

Bump telio-bulid to v0.3.2

---

nat-lab/tests/test_direct_connection.py

Mark natlab test as flaky

---

nat-lab/tests/test_lana.py

Mark test as flaky

---

nat-lab/tests/test_events.py

Mark test_event_content_vpn_connection as flaky on win

---

.github/workflows/ci.yml
.github/workflows/gitlab.yml
.gitlab-ci.yml

`coverage` and `nagger` scheduled workflows also added to the list of checked jobs.

Use v0.4.3 version of the scheduled gitlab pipeline

---

Cargo.lock
changelog.md
crates/telio-relay/Cargo.toml
crates/telio-relay/src/derp/http.rs
crates/telio-traversal/src/endpoint_providers/stun.rs

This was already tested manually with `tcl`i as described in the ticket. Additionally `STUN` module already includes appropriate tests so only `DERP` test is added.

Change DERP protocol identifier and STUN software.

---

nat-lab/run_local.py

It's possible to run nat-lab in an incompatible environment.
Check if the version of outer environment matches the one which is expected (`triggered-ref` in github workflows).

Add check to verify if the setup for nat-lab is correct

---

Makefile

Fix the makefile so that it works on macos
`sed` on mac requires passing the extension for backups when `-i` is used. Additionally the version check is fixed since it wasn't ready for the `x.y.z` format of versions (it only expected `x.y`).

Fix the makefile so that it works on macos

---

nat-lab/guidelines.md

Add guidelines/tips on how to write natlab tests so they would be less flaky or in general more stable.

LLT-4052: add natlab guidelines

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Use triggered ref 0.4.4 which introduces nat-lab sharding.

Update triggered ref to v0.4.4 (sharding)

---

crates/telio-utils/src/lru_cache.rs

Updated proptest detects this, since 'len' and 'is_empty' no longer implicitly clear expired entries.
```
minimal failing input: init = (
0,
0,
), ops = [
Insert(
E,
),
Sleep(
2,
),
GetUsingEntry(
E,
),
]
```
Originally found here: https://github.com/NordSecurity/libtelio/pull/214/files#diff-fae6e5df3dd3f66c7dd878a77a90ef925d96693b70fb4d03a466e9444d5f1f89R174

LRU cache should if occupied entry didn't expire before returning it

---

clis/tcli/src/cli.rs

`tcli dev con` was not intuitive for a foreigner
Added information to tcli's `dev con` to aid for future users

Add comments to "dev con" command

---

nat-lab/tests/test_dns.py

There was a test case missing for nicknames feature to ensure that a peer nickname change is done with success.
Add that test case.

natlab: Add change peer nickname test

---

Cargo.lock
Cargo.toml
changelog.md

Update version to v4.2.1

---

nat-lab/tests/test_dns_through_exit.py
nat-lab/tests/test_mesh_plus_vpn.py

Tests are flaky
Add the flaky mark to those tests

natlab police: Add flaky mark to tests

---

Cargo.lock
Cargo.toml
changelog.md
crates/telio-nurse/Cargo.toml
crates/telio-nurse/src/qos.rs
crates/telio-nurse/src/rtt/ping.rs
crates/telio-sockets/Cargo.toml
crates/telio-sockets/src/protector/apple.rs
crates/telio-traversal/Cargo.toml
crates/telio-traversal/src/session_keeper.rs
crates/telio-utils/src/dual_target.rs
crates/telio-wg/src/wg.rs
nat-lab/tests/test_events.py
src/device/mod.rs
src/device/wg_controller.rs

There was some problems with how `surge_ping` was used in analytics and session_keeper in dual-stack configuration.

LLT-4597 LLT-4594 Bug fixes from IPv6 smoke test

---

Cargo.lock
changelog.md

Update zerocopy
**Note to reviewers:**
In order to avoid conflict on changelog.md file I have branched this PR off of the changes, which already includes rustix update, as I am planning to merge rustix first and then this. So keep in mind, that this PR will have changelog for rustix too, but after merging there changelog values will be as expected :).

Update zerocopy v0.7.25 -> v0.7.31

---

crates/telio-model/src/event.rs
crates/telio-model/src/mesh.rs
nat-lab/tests/test_events.py
src/device/mod.rs

Node event did not have nickname of that node
add the node field and fill it

added nicknames to node events

---

Cargo.lock
Cargo.toml

Update cargo version in preparation for v4.2.2 RC

Release v4.2.2

---

Cargo.lock
Cargo.toml
changelog.md
nat-lab/tests/test_events_link_state.py

Bump boringtun version to v1.1.10

---

nat-lab/tests/conftest.py

The introduction of helper functions in natlab tests has hidden parameters ids making debugging less transparent.  
Add identification function to relevant tests so that devs can identify the parameters for each test.
Test previously described as:
`test_upnp_without_support[beta_setup_params0-alpha_setup_params4]`
with this PR becomes:
`test_upnp_without_support[DOCKER_CONE_CLIENT_2-AdapterType.BoringTun-['upnp']-MAC_VM-AdapterType.BoringTun-['upnp']]`

natlab: Add test parameters identification

---

changelog.md

Forgot to update changelog in #297 😅 
Add changelog entry

Update changelog to reflect LLT-4661 was merged in

---

nat-lab/tests/test_network_switch.py
nat-lab/tests/utils/connection_util.py
nat-lab/tests/utils/network_switcher/network_switcher.py
nat-lab/tests/utils/network_switcher/network_switcher_docker.py
nat-lab/tests/utils/network_switcher/network_switcher_mac.py
nat-lab/tests/utils/network_switcher/network_switcher_windows.py

Reverts NordSecurity/libtelio#314

Revert "Resolve LLT-4812: Reenable windows management interface on natlab."

---

nat-lab/tests/test_network_switch.py
nat-lab/tests/utils/connection_util.py
nat-lab/tests/utils/network_switcher/network_switcher.py
nat-lab/tests/utils/network_switcher/network_switcher_docker.py
nat-lab/tests/utils/network_switcher/network_switcher_mac.py
nat-lab/tests/utils/network_switcher/network_switcher_windows.py

Reverts NordSecurity/libtelio#321

Revert "Resolve LLT-4812: Reenable windows management interface on natlab.""

---

.github/workflows/gitlab.yml
nat-lab/Pipfile
nat-lab/Pipfile.lock

Install pytest-repeat for natlab-tests-retry job

---

.github/workflows/nagger.yml
Cargo.lock
Cargo.toml
nat-lab/tests/utils/process/docker_process.py
nat-lab/tests/utils/process/ssh_process.py

Natlab fixes

---

nat-lab/tests/utils/process/docker_process.py
nat-lab/tests/utils/process/ssh_process.py

Nat lab could leave hanging process
Close it

[LLT-4920] backport natlab fix

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Lack of vagrant logs
Add debug vagrant logs

Update libtelio-build ref

---

changelog.md
crates/telio-dns/src/dns.rs
crates/telio-dns/src/nameserver.rs
crates/telio-dns/src/zone.rs
crates/telio-dns/tests/integration_tests.rs
crates/telio-dns/tests/nameserver.rs
crates/telio-model/src/api_config.rs
nat-lab/tests/telio_features.py
nat-lab/tests/test_dns.py
nat-lab/tests/test_telio_features.py
nat-lab/tests/test_telio_tasks.py
rustfmt.toml
src/device/mod.rs
src/device/wg_controller.rs

TTL value is to big in telio-dns
Backport Juozapas Solution.

[LLT-4908] backport configurable ttl value

---

changelog.md
crates/telio-model/src/validation.rs
nat-lab/tests/mesh_api.py
nat-lab/tests/test_dns.py
nat-lab/tests/test_events.py
nat-lab/tests/test_mesh_api.py
src/device/mod.rs

Backport of https://github.com/NordSecurity/libtelio/pull/359

[LLT-4916] Backport any case nick

---

Cargo.lock
changelog.md
crates/telio-proxy/Cargo.toml
crates/telio-proxy/src/proxy.rs

Add error handling in proxy egress. Log change of state and error only once.

Handle egress errors

---

changelog.md

This was missed in the main PR
Add it now

Update changelog with updated missed tick behavior

---

.github/workflows/tests.yml
ci/replace_string.py
ci/test_replace_string.py

We need to update libtelio version in our builds w/o rebuilding them for future promotions of builds.
Add script that allows to replace certain string in provided file.

add string replacement in file script

---

changelog.md
crates/telio-firewall/src/firewall.rs
crates/telio-nurse/src/qos.rs
crates/telio-nurse/src/rtt/ping.rs
crates/telio-wg/src/wg.rs

[LLT-4913] Backport fix nurse error spam

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

There was no easy/automated way to build android app.
v0.4.18 includes an option to trigger jobs that result in a working apk for android.

Trigger androind pipeline

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

This fixes github notification and pipeline status which should fix the timelines script.

Update trigger to 0.4.19

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

bump libtelio-build version

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Dump Vagrantbox to the latest version

Point to newer Vagrantbox(with nordlynx)

---

.cargo/config_apple_tvos
.github/workflows/build.yml
.github/workflows/gitlab.yml
.gitlab-ci.yml
Cargo.lock
Cargo.toml
changelog.md
ci/build_libtelio.py
ci/moose_utils.py
clis/interderpcli/Cargo.toml
crates/telio-firewall/Cargo.toml
wireguard-go-rust-wrapper/build.rs
wireguard-go-rust-wrapper/wireguard-go/build.ps1
wireguard-go-rust-wrapper/workaround_msvc_static_go_runtime_init.c

Backporting windows arm64 build from `main`.

Backport Windows ARM64 build to v4.3.x

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

v1.0.0 contained non existing sha in libtelio submodule. It caused pipelines to fail
Problem fixed in v1.0.1. Update tag here

Fix gitlab pipelines

---

Cargo.lock
clis/tcli/src/derp.rs
crates/telio-model/src/config.rs
crates/telio-nurse/src/aggregator.rs
crates/telio-relay/Cargo.toml
crates/telio-relay/src/derp/http.rs
crates/telio-relay/src/derp/mod.rs
crates/telio-relay/src/derp/proto.rs
src/device/mod.rs

We need to report data about Derp connectivity changes
This commit adds aggregator pointer to the Derp module and uses it to report Derp connectivity events

[LLT-4859] Report DERP changes to aggregator

---

Cargo.lock
Cargo.toml
changelog.md
release.py

Release v4.3.1

---

Cargo.lock
Cargo.toml

Release v4.3.2

---

Cargo.lock
Cargo.toml

Release v4.2.7

---

wireguard-go-rust-wrapper/wireguard-go/platform_specific_windows.go

Llt 4644 backport wintun creation fix

---

Cargo.lock
Cargo.toml
changelog.md

Release v4.2.8

---

nat-lab/tests/test_lana.py
nat-lab/tests/utils/analytics/event_validator.py

Lana tests in `nat-lab` had disabled nat-traversal info validator.
Enabled nat-traversal info validator and clear a bunch of TODOs. 
Changed nat traversal info validator. Now it standard `StringValidator` with added entries count validation. The reason for this, is that we currently do not have node numbering validator (the same as in connectivity matrix) so we cannot check if, which node is actually included in the nat traversal info entry.

Enable nat traversal info validator

---

.github/workflows/scorecard.yml

Update scorecard to the latest version

---

changelog.md

As the main, v4.2 and v4.3 branches have diverged, the changelog.md entries between them had become desynchronized and a lot of entries that had already been released ended up in the unreleased section of the main branch.
This branch introduces a manual clean up and synchronization of these entries.

Changelog clean up

---

.github/workflows/gitlab.yml
.gitlab-ci.yml
.unreleased/update-libtelio-build-ref

Update libtelio build ref

---

Cargo.lock
Cargo.toml

Release v4.2.9

---

Cargo.lock
changelog.md
crates/telio-sockets/Cargo.toml
crates/telio-sockets/src/protector/apple.rs
src/device/mod.rs

Merge of fixes from the 4.2 branch #531 and #524.

Fixes for apple interface selection and socket rebinding

---

.unreleased/LLT-5148
.unreleased/LLT-5188
Cargo.lock
crates/telio-sockets/Cargo.toml
crates/telio-sockets/src/protector/apple.rs
src/device/mod.rs

Merge of fixes from the 4.2 branch #531 and #524.

Fixes for apple interface selection and socket rebinding main

---

.github/workflows/linters.yml

Backport of https://github.com/NordSecurity/libtelio/pull/554

Lock udeps job toolchain

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

bump libtelio build version

---

Cargo.lock
Cargo.toml
changelog.md

Release v4.3.3

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio_build tag to handle libsqlite3 secrets.

ci: Bump libtelio_build tag

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build reference from v1.1.12 to v1.1.13. 

Bump libtelio-build reference

---

go.mod

Remove no longer needed go.mod file

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Update triggered ref to v1.2.1

Update triggered ref to v1.2.1

---

nat-lab/tests/telio.py

We do sometimes get failures from wireguard adapters in windows, which do not produce any errors.
Get event-log from windows VMs when test ends and append it to test logs.

LLT-5311 Add event-log capture on windows VM in nat-lab

---

.github/workflows/linters.yml
Cargo.lock
Cargo.toml
changelog.md
crates/telio-dns/src/forward.rs
crates/telio-dns/src/nameserver.rs
deny.toml
src/ffi/mod.rs

In same rare cases we observe unexplained burst of failures in DNS resolution on Android. This PR attempts to add some additional information which should help catch the issue.

[LLT-5359] add logging to catch dns errors on android

---

.cargo/config
changelog.md
linkers/d-aarch64-openwrt-linux-musl
linkers/d-x86_64-openwrt-linux-musl
linkers/generate.sh

Same as https://github.com/NordSecurity/libtelio/pull/624

LLT-5325 Add OpenWRT linker backport v4.3

---

nat-lab/tests/utils/vm/windows_vm_util.py

Periodically, nat-lab Windows tests fail with the Timeout while copying the files into the VM.
To be able to monitor the file copy process and gather more information for debugging purposes, there is an option to extend `asyncssh.scp` by adding `progress_handler` method.

[LLT-5387] Add progress handler for files copy in nat-lab 

---

.unreleased/LLT-4641
.unreleased/LLT-4901
.unreleased/LLT-5024
.unreleased/LLT-5077
.unreleased/LLT-5103
.unreleased/LLT-5196
.unreleased/LLT-5211
.unreleased/LLT-5212
.unreleased/LLT-5247
.unreleased/LLT-5248
.unreleased/LLT-5252
.unreleased/LLT-5278
.unreleased/LLT-5279
.unreleased/LLT-5285
.unreleased/LLT-5291
.unreleased/LLT-5292
.unreleased/LLT-5293
.unreleased/LLT-5294
.unreleased/LLT-5359
changelog.md

Bumping changelog for v5.0.0-rc2 release.

Bump for v5.0.0-rc2 release

---

nat-lab/Pipfile
nat-lab/Pipfile.lock

BDSA-2024-2985 was reported for psf-request, Update should be easy, so doing it in this PR.

[LLT-5366] Update requests dependency due to BDSA-2024-2985

---

nat-lab/run_local.py

test might not have enough time to run
increase general timeout

Increase general test timeout

---

.github/workflows/gitlab.yml
.gitlab-ci.yml
Cargo.lock
Cargo.toml
changelog.md
crates/telio-wg/Cargo.toml
crates/telio-wg/src/adapter/boring.rs

Backport https://github.com/NordSecurity/libtelio/pull/673

LLT-5324 Bump boringtun to v1.1.13

---

Cargo.lock
Cargo.toml

Release 4.3.5

---

nat-lab/tests/utils/vm/windows_vm_util.py

With current implementation `_file_copy_progress_handler` called each time when scp copy 16 KB which leads to enormous log file.
Add file copy progress buffer and print it in case of copy failure.

[LLT-5387] Print file copy progress only in case of copy failure

---

crates/telio-wg/src/adapter/windows_native_wg.rs

For some reason adapter.up() failes after sucessful adapter.create(). There is a suspicion in the team that it might be a race condition. For now let's add a few retries and investigate further the root casue.

Add adapter.up() retries for wireguard_nt

---

Cargo.lock
Cargo.toml

Bump boringtun version to include https://github.com/NordSecurity/boringtun/pull/25

Bump boringtun version

---

nat-lab/natlab.py

Something is killing iptables and we don't know who it is and why.
Collect dmesg logs with the intention to check if this is out of memory condition that is causing OOM killer to kill iptables.

Collect dmesg output

---

nat-lab/tests/test_reconnections.py

There is a time gap when meshnet is started in `test_mesh_reconnect` and test starts to wait for derp/node events coming from libtelio. If libtelio fires an even in this time gap when meshnet is already started, but test is still not waiting for event - test will attempt to wait for **second** derp/node event which will never come. This PR removes this time gap.

Fix race condition in test_mesh_reconnect

---

nat-lab/tests/telio.py
nat-lab/tests/utils/connection/connection.py
nat-lab/tests/utils/connection/docker_connection.py
nat-lab/tests/utils/connection/ssh_connection.py

Do not use type command over ssh to copy file. Instead use scp

Natlab: scp instead of type

---

crates/telio-model/src/features.rs

One of the windows peeps mentioned recently while doing in-branch testing that they got incorrect values when deserializing a json feature config with the FFI function we provides for doing the deserialization, and nothing seemed to be wrong with their json. As a way to check that we aren't doing anything weird on our side, I wanted to update the test suite for the feature config.
Add some new more comprehensive and understandable tests, and then remove tests that are either covered by the new tests or that are testing that serde itself works, which we shouldn't do in my opinion. The new tests revealed that deserializing `{}` produced different results compared to `Feature*::default()` in some cases, and those were fixed here.
For now there is a bit more code with manually implementing …

LLT-5469 Feature config tests

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

libtelio-build has relevant changes for libtelio. Bump its triggering version.

Update libtelio-build reference

---

nat-lab/tests/telio.py
nat-lab/tests/uniffi/libtelio_remote.py
nat-lab/tests/utils/connection/connection.py
nat-lab/tests/utils/connection/docker_connection.py
nat-lab/tests/utils/connection/ssh_connection.py

Because of the lack of lock in logger implementation two logs could
overlap leading to missing logs or in our case to malformed utf-8
sequences.

LLT-5466 Fix malformed utf-8 byte sequence in logs

---

nat-lab/tests/test_mesh_firewall.py

Under "normal" circumstances closing connection from server side does not trigger `nc` to close TCP connection from client-side, which can be observed in the following screenshot:
In `test_mesh_firewall` tests there is expectation that `nc` will close connections from both sides once at least once side sends `FIN`. To match these expectations `-d` flag has been added, which tells `nc` to not read from stdin, and as a result close client-side connection immediatelly if server-side is closed.

[LLT-5504] Force nc client to quit and close connection once server-side connection is closed

---

nat-lab/tests/telio.py
nat-lab/tests/test_pinger.py

in `test_ping_pong` receiving socket is currently created in separate thread in an unsychronised manner to sender. Meaning, that sometimes sender may attempt to send ping packet before receiver is ready. This PR breaks this race by waiting for listening socket to appear in the OS.

Wait for listening port to be ready in test_ping_pong

---

nat-lab/tests/test_direct_connection.py

Disable lana/nurse for tests that don't need them

---

nat-lab/tests/test_lana.py
nat-lab/tests/test_lana_validator.py
nat-lab/tests/utils/analytics/event_validator.py

Refactor [event validators](https://github.com/NordSecurity/libtelio/blob/main/nat-lab/tests/utils/analytics/event_validator.py).
[test_lana_validator.py](https://github.com/NordSecurity/libtelio/blob/main/nat-lab/tests/utils/analytics/test_lana_validator.py) also needs to be refactored, will be done in a follow-up task.

natlab: Refactor event validators with decorator pattern

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Update gitlab triggering references

Llt 5517 update gitlab reference

---

crates/telio-model/src/features.rs

The json parsing and testing code has quite some boilerplate which makes writing small focused tests more costly than it should be.
New macro `assert_json` is introduced to remove most if not all of the boilerplate from the tests.

[LLT-5520] Extract common pattern in all features tests into a macro

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build reference from v2.1.0 to v2.2.0

Bump libtelio-build reference to v2.2.0

---

nat-lab/tests/test_events.py

This test starts one of the nodes without any EP and expects to accomplish relay path connection. Then it recreates the node to add the stun server as EP, expecting then a direct path connection.
It was failing locally because although the `telio.Client` instance was dropped it was ran inside the main exit stack, so not collected by the python's gc while inside the exit stack. This resulted in a failed second `telio.Client` init with a `Address already in use` OS error when attempting the Pyro5 connection.
This commit replaces the `setup_mesh()` function by individual exit stacs, so that the dropped node is fully cleaned by the python's garbage collector before recreating the libtelio remote connection.

natlab: Trigger garbage collection when dropping node

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build reference from v2.2.3 to v2.3.0

Bump libtelio-build reference to v2.3.0

---

nat-lab/bin/multicast.py
nat-lab/tests/test_multicast_connection.py
nat-lab/tests/utils/multicast.py
nat-lab/tests/utils/vm/mac_vm_util.py

We want to make sure multicast implementation is working on macOS
Add multicast nat-lab integration tests for macOS.

LLT-5106 macOS multicast integration tests

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Solution was done in build repo, this just updates the build ref

LLT-5592: Fix commit sha in binaries

---

crates/telio-starcast/src/transport.rs

If Telio is run via TCLI and `mesh on <tun_name>` without calling `dev start` and configuring the tunnel interface with meshnet IP, starcast transport socket cannot be bound to meshnet IP.
Starcast now retries binding transport socket to the meshnet IP every 5 seconds until it succeeds. Until then multicast messages captured by the starcast vpeer are buffered in the mpsc channel or ignored if it is full.

Fix starcast transport component failing to open transport socket when meshnet is started before tunnel interface IP is configured

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Investigate if new instability is caused due to multiple runners

Go back to 6 runners

---

nat-lab/Pipfile
nat-lab/Pipfile.lock
nat-lab/bin/core-api.py
nat-lab/pyproject.toml
nat-lab/tests/conftest.py
nat-lab/tests/test_batching.py
nat-lab/tests/test_dns.py
nat-lab/tests/test_lana.py
nat-lab/tests/test_mesh_api.py
nat-lab/tests/test_mesh_off.py
nat-lab/tests/test_nat_type.py
nat-lab/tests/test_notification_center.py
nat-lab/tests/uniffi/libtelio_proxy.py

Enable extra mypy lints, the most important for us being 'unused-awaitable'

Enable extra mypy lints

---

.unreleased/LLT-5638
src/device/wg_controller.rs

Move ep control at the begining of consolidation

---

crates/telio-relay/src/derp.rs
crates/telio-relay/src/derp/proto.rs

Remove FrameChannel which is not used
Not necessary to have, probably legacy code

Remove FrameChannel which is not used

---

crates/telio-traversal/src/endpoint_providers/upnp.rs

UPNP external port range was being set at IGD crate criteria, which is RNG assigned between 32768..65535.
IANA standardized this range on 49152..65535 and this is what should be used. (see: https://www.rfc-editor.org/rfc/rfc6335.html#section-6)
Leave the port random generation to telio, using 49152..65535.

traversal: Set random ports between ephemeral range

---

crates/telio-proxy/src/proxy.rs

We don't know exact reason why we enter the error branch.
Print the relevant values from the match.

Add more detail to the WG Address no available proxy error

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build tag with fixed bug on scheduled pipelines.

ci: Bump libtelio-build tag

---

nat-lab/tests/test_upnp_connection.py

`upnpc` command is prone to race condition, because we're resetting `upnpd` before that.
Add retry logic for `upnpc`.

Add some retry logic to upnpc

---

src/device/wg_controller.rs

Recent changes to endpoint invalidation logic missed a scenario, where connection is downgraded from direct to relayed one, leaving old endpoints in a valid state. This may cause spurious upgrade request, and unnecessary relay->direct->relay cycles.
This PR refactors the logic a bit. First, it exports this invalidation logic into separate consolidation function, and defines (in comments) specific conditions when endpoints should be invalidated.
What is more, it changes when endpoints are considered for invalidation, to be able to catch both cases, when we are roaming from one EP to another (including downgrade-by-roaming) and when we forcefully downgrading by inactivity.
Recently `test_direct_working_paths` started failing sometimes. I was digging into root cause, and the following is …

[LLT-5742] Update endpoint invalidation logic

---

nat-lab/tests/test_wg_adapter.py

Add missing import datetime in test_wg_adapter

---

crates/telio-nurse/src/qos.rs
nat-lab/tests/telio.py
nat-lab/tests/test_lana.py

Added test to to verify correctness of periodic qos collection

---

nat-lab/tests/telio.py
nat-lab/tests/test_lana.py
nat-lab/tests/uniffi/libtelio_remote.py
nat-lab/tests/utils/moose.py
nat-lab/tests/utils/process/docker_process.py

Added moose logs collection in nat-lab

---

qnap/build_sign.csv
qnap/package_routines
qnap/qpkg.cfg
qnap/shared/NordSecMeshnet.sh

Creation of initial template directory for QNAP builds.
It is just a generic setup with basic configuration to serve as basis for the next tasks.

build: Add qnap initial template

---

.unreleased/LLT-4963
.unreleased/LLT-5108
.unreleased/LLT-5183
.unreleased/LLT-5402
.unreleased/LLT-5552
.unreleased/LLT-5553
.unreleased/LLT-5554
.unreleased/LLT-5574
.unreleased/LLT-5593
.unreleased/LLT-5638
.unreleased/LLT-5653
.unreleased/LLT-5660
.unreleased/LLT-5663
.unreleased/LLT-5675
.unreleased/LLT-5681
.unreleased/LLT-5710
.unreleased/LLT-5721
.unreleased/LLT-5770
.unreleased/async-logs
Cargo.lock
Cargo.toml
changelog.md

Prepare versions for next release

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build reference to v2.5.0

Bump libtelio-build reference to v2.5.0

---

.github/workflows/gitlab.yml
.gitlab-ci.yml
nat-lab/tests/test_cleanup.py

- needed new version of windows vm
- update windows vm
- increase adapter count in registry since npcap was added and new item appeared in the list

Resolve LLT-5748: update windows vm

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build v2.6.3

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

bump libtelio build to v2.6.4

---

nat-lab/tests/conftest.py
nat-lab/tests/mesh_api.py

We don't collect tcpdumps from all gateways.
tcpdump pcaps are collected from all gateways, once per session. To make it faster, it's done concurrently.

Collect tcpdumps from gateways

---

nat-lab/docker-compose.yml

DERP tcp values differ from prod.
Adjust values to match prod.

DERP nat-lab TCP values as in production

---

nat-lab/tests/conftest.py

Derp resuable port numbers migrates to next test, therefore messes up the derp server connections.
Have a concrete tcp port range for each test.

Assign random tcp port range at the start of each test for WIN VMs

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

custom hostname on windows VMs was making more issues  than fixes.
reverted custom hostname on windows VM "fix"

bump libtelio build to v2.6.7

---

ci/build_libtelio.py
qnap/package_routines
qnap/qpkg.cfg
qnap/shared/NordSecMeshnet.sh
qnap/shared/teliod.cfg
qnap/shared/web/index.html
qnap/shared/web/script.js
qnap/shared/web/styles.css

This PR replaces `tcli` for `teliod` in the NordSecurityMeshnet qpkg, modifying the installation and also provide a sample web UI that is served by qnap's own http server. 
html/css/js contents are out of scope for this review, please ignore them.

LLT-5781: Add teliod to qnap package

---

nat-lab/docker-compose.yml
nat-lab/tests/conftest.py

Same as https://github.com/NordSecurity/libtelio/pull/980 but for linux and mac as well.

Add ephemeral port randomization-per-test for MAC and Linux also

---

nat-lab/tests/utils/command_grepper.py

We cannot see, if there's anything irregular, when using `CommandGrepper` and timeout happens.
Print last stdout, if timeout happens.

Print last stdout in CommandGrepper, if timeout happens

---

nat-lab/tests/test_pq.py

#991 was merged without rebase and caused the Python lint job to fail
Adjust code to the changes from `main`

Fix `test_pq.py` python code

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build reference to v2.7.0

Bump libtelio-build reference to v2.7.0

---

src/device.rs

Stun packets are being sent on set_config and network change, to print nat type. But we do not have a suitable (double IPs) DERP servers to check that.
Remove nat logging.

Remove log_nat

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

add vagrant --debug and --no-parallel flags

bump libtelio build to v2.7.1

---

.unreleased/LLT-5609-ip-validation
Cargo.lock
Cargo.toml
crates/telio-traversal/Cargo.toml

This version includes fixes that prevent IP spoofing during gateway searching. Removed no longer needed dependencies: h2 and http.

Update rust-igd to our fork, version 0.13.1

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build reference to v2.7.4

Bump libtelio-build reference to v2.7.4

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump `rust_build_utils` and `libtelio-build` tags so that qnap's aarch64 architecture is also built.

LLT-5784: qnap: Add support for aarch64 architectures

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Update build ref

---

src/device/wg_controller.rs

Add debug print to pq restart logic

---

docs/battery.md

Add details about direct connection keepalive
value and usage of link detection together

Add details about link_detection to battery doc

---

Cargo.lock
crates/telio-dns/Cargo.toml

Blocking issue which is difficult to reproduce
Debug logs have been sprinkled in trust-dns to pinpoint the problem. v3.0.2 already contains some logs, after more data, some more logs have been sprinkled around to narrow the problem.

Update dns commit hash

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Some changes to libtelio<->android integration were requested. This updates to include those changes in nightly and other pipelines.

Update gitlab reference to v2.8.4

---

crates/telio-dns/src/nameserver.rs

Dns tests fails sometimes. The issue might be coming from neptun, but thats not certain yet.
Add logs around nameserver.rs to narrow down the issue.

Sprinkle logs in nameserver

---

crates/telio-dns/src/nameserver.rs

These logs are added to debug a nightly natlab failure. We need more information.

Add more DNS logs

---

nat-lab/tests/utils/command_grepper.py
nat-lab/tests/utils/router/windows_router.py

Add logs to windows machine adapter creation

nat-lab more logs

---

ci/env.fish

Just like env.sh, to use it run `source path/to/env.fish`.

Add environment setting script for the fish shell

---

nat-lab/tests/test_direct_connection.py
nat-lab/tests/test_dns.py
nat-lab/tests/test_lana.py
nat-lab/tests/test_network_monitor.py
nat-lab/tests/test_pinging.py
nat-lab/tests/test_pq.py
nat-lab/tests/test_telio_tasks.py
nat-lab/tests/uniffi/libtelio_remote.py

This reverts commit c0ac4d5ca004dec94d974e4596b50ee00964a664, reversing changes made to 0c7b90f7a04962f25697bc3d63942dbe61e27cb8.
Removing logging didn't solve the problem we investigated so let's bring them back

Revert logging removal

---

.github/workflows/gitlab.yml
.gitlab-ci.yml
nat-lab/tests/conftest.py
nat-lab/tests/utils/connection/connection.py
nat-lab/tests/utils/tcpdump.py

Sometimes it's useful to see traffic from the host running the nat-lab tests.

Capture pcaps on host using tcpdump

---

.github/workflows/linters.yml
.github/workflows/tests.yml
Cargo.lock
crates/telio-dns/src/nameserver.rs
crates/telio-utils/Cargo.toml
crates/telio-utils/src/lib.rs
crates/telio-utils/src/utils.rs
nat-lab/tests/telio.py
nat-lab/tests/test_dns.py
nat-lab/tests/uniffi/libtelio_proxy.py
nat-lab/tests/uniffi/libtelio_remote.py
src/device.rs
src/ffi/logging.rs
tests/logger.rs

During the recent debugging of several natlab issues extra logs were added, now that they are no longer needed cleanup should take place.
Remove added logs.

LLT-6027: Cleanup natlab logs

---

Cargo.lock
Cargo.toml

Update neptun to v1.0.4

---

.unreleased/LLT-4749
.unreleased/LLT-5457
.unreleased/LLT-5605
.unreleased/LLT-5609-ip-validation
.unreleased/LLT-5639
.unreleased/LLT-5780-boringtun-neptun-rename
.unreleased/LLT-5785
.unreleased/LLT-5789
.unreleased/LLT-5801
.unreleased/LLT-5814
.unreleased/LLT-5815
.unreleased/LLT-5857
.unreleased/LLT-5884
.unreleased/LLT-5886_protected_pinger
.unreleased/LLT-5892
.unreleased/LLT-5913
.unreleased/LLT-5967
.unreleased/LLT-5968
.unreleased/LLT-6016
Cargo.lock
Cargo.toml
changelog.md

Prepare for v5.3.0-rc

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build reference to v2.9.1

Bump libtelio-build reference to v2.9.1

---

nat-lab/tests/mesh_api.py
nat-lab/tests/test_mesh_api.py

Instead of failing the test in case of duplicate IP just regenerate it

Fix assign_ip function

---

.unreleased/LLT-5972_configure_windows_adapter_according_to_needs
.unreleased/LLT-6041-pq-restart-instant
.unreleased/LLT-6086
changelog.md

Update changelog with v5.3.0-rc2

---

nat-lab/tests/conftest.py

We have no logs from fakefm and when it fails to respond to RADIUS it's hard to find the reason
Save fakefm logs

Copy fakefm logs from NLX container

---

deny.toml

Get rid of ignore list in deny config

---

.github/workflows/tests.yml

Also, add RUST_BACKTRACE=full to test runs.

Stop using (in tests) actions-rs/cargo and use pre-installed cargo

---

nat-lab/tests/test_mesh_plus_vpn.py

There is a race between libtelio `Disconnected` event and it's assert
Run the check in async task before the disconnecting code is actually run

Fix race in test_vpn_plus_mesh

---

Cargo.lock

Cargo dependencies are out of date
Update the dependencies with `cargo update`

update rust deps

---

Cargo.lock
Cargo.toml
clis/derpcli/Cargo.toml
clis/interderpcli/Cargo.toml
clis/tcli/Cargo.toml
clis/teliod/Cargo.toml
clis/teliod/src/command_listener.rs
crates/telio-crypto/Cargo.toml
crates/telio-firewall/Cargo.toml
crates/telio-network-monitors/Cargo.toml
crates/telio-nurse/Cargo.toml
crates/telio-relay/Cargo.toml
crates/telio-sockets/Cargo.toml
crates/telio-traversal/Cargo.toml
crates/telio-utils/Cargo.toml
crates/telio-wg/Cargo.toml
deny.toml

Update rust dependencies

---

ci/build_libtelio.py

The C static runtime for windows was actually turned off for libtelio.
Turn it on

Fix enabling static runtime for windows

---

.unreleased/LLT-6168-serialize-features
Cargo.lock
crates/telio-firewall/src/firewall.rs
crates/telio-model/Cargo.toml
crates/telio-model/src/features.rs
src/ffi.rs
src/lib.rs
src/libtelio.udl

Also, property tests are added to make sure we can deserialize what we produce.

Added a new ffi function do serialize `Feature` to a json string

---

.unreleased/LLT-3424
Cargo.lock
Cargo.toml
crates/telio-network-monitors/src/monitor.rs
crates/telio-wg/src/adapter.rs
crates/telio-wg/src/adapter/linux_native_wg.rs
crates/telio-wg/src/adapter/neptun.rs
crates/telio-wg/src/adapter/windows_native_wg.rs
crates/telio-wg/src/adapter/wireguard_go.rs
crates/telio-wg/src/wg.rs
nat-lab/docker-compose.yml.bak
nat-lab/tests/telio.py
nat-lab/tests/test_start_with_tun.py
nat-lab/tests/uniffi/libtelio_proxy.py
nat-lab/tests/uniffi/libtelio_remote.py
nat-lab/tests/utils/router/linux_router.py
nat-lab/tests/utils/router/mac_router.py
nat-lab/tests/utils/router/router.py
nat-lab/tests/utils/router/windows_router.py
src/device.rs
src/ffi.rs
src/libtelio.udl

This new ffi api works only for the NepTUN adapter.

Expose an api to change TUN interface at runtime

---

Cargo.lock
Cargo.toml
clis/tcli/Cargo.toml
clis/teliod/Cargo.toml
clis/teliod/src/daemon.rs
crates/telio-relay/Cargo.toml

Update rust dependecies

---

nat-lab/tests/test_teliod.py

Recently `test_teliod` failed because `wait_for_teliod` timed out - it called `is_teliod_running` only once though, so probably `is_teliod_running` took longer than expected and couldn’t run another time.
This PR replaces timeout with retry count, so even if one call takes a lot of time there will be some retires

[LLT-6300] Use retries in teliod test

---

.unreleased/LLT-6115
.unreleased/NMACOS-8047
.unreleased/is_link_up_is_always_false_before_first_received_packet
Cargo.lock
Cargo.toml
changelog.md

Prepare for release v5.3.1

---

.unreleased/update_neptun_tag
Cargo.lock
Cargo.toml

Update neptun to version 2.1.0 to include download side optimizations

Update Neptun to v2.1.0

---

.github/workflows/gitlab.yml
.gitlab-ci.yml

Bump libtelio-build to v2.11.5

---

clis/teliod/src/daemon.rs
clis/teliod/src/main.rs

There is no easy way for the user to tell if VPN or meshnet peer exit node is enabled.
`teliod get-status` command is augmented to present exit node status (both VPN or meshnet peer)

LLT-6142: Add exit node to teliod status

---

.github/workflows/gitlab.yml
.github/workflows/gitlab_schedule.yml
.gitlab-ci.yml

A fix was implemented in libtelio build to get more info in nightlies
Bump libtelio-build

Bump libtelio-build to 2.13.4

---

.unreleased/unsafe_fix
Cargo.lock
Cargo.toml
changelog.md
crates/telio-wg/src/windows/tunnel/addressconfig.rs
crates/telio-wg/src/windows/tunnel/mtumonitor.rs
crates/telio-wg/src/windows/tunnel/winipcfg/luid.rs

Libtelio 6.0.0 is crashing on windows due to some incorrect unsafe handling
Backport fix from main and release v6.0.2

Prepare release v6.0.2

---

Cargo.lock

Update dependency crates

---

.github/workflows/nagger.yml
Justfile
clis/derpcli/src/main.rs
clis/tcli/src/bin/tcli.rs
clis/tcli/src/cli.rs
clis/teliod/src/config.rs
clis/teliod/src/configure_interface.rs
crates/telio-crypto/src/lib.rs
crates/telio-dns/src/nameserver.rs
crates/telio-firewall/src/conntrack.rs
crates/telio-firewall/src/firewall.rs
crates/telio-lana/build.rs
crates/telio-pq/src/proto.rs
crates/telio-proto/src/lib.rs
crates/telio-proxy/src/proxy.rs
crates/telio-starcast/src/utils.rs
crates/telio-traversal/src/endpoint_providers/upnp.rs
crates/telio-utils/src/const_ipnet.rs
crates/telio-utils/src/git.rs
crates/telio-wg/src/adapter/windows_native_wg.rs
crates/telio-wg/src/windows/tunnel/winipcfg/types.rs
src/device.rs
src/lib.rs

There are lints checked by nagger which are now supported by clippy
Use clippy for lint checking for supported lints rather than nagger

Add linters in clippy

---

clis/nordvpnlite/src/core_api.rs

We are spamming `Servers not found for '{target_country}' country code.` in the logs for every country we compare, since we are doing it inside the `find_map`.
Log only once if no country is found.

Teliod servers not found log spam
